<?php
/**
 * @author: syafiq <syafiq@my-sands.com>
 * senarai bank & institusi kewangan dalam malaysia + swift code
 * is_listed = 1 // senarai bank yang Sands guna dalam sistem.
 *
 * json format: https://gist.github.com/shah253kt/3c6ba00c881740f3c55f50c40319561e
 */
 
$items = [
    [ 'name' => 'AFFIN BANK BERHAD', 'swift_code' => 'PHBMMYKL', 'bank_code' => 'PHBM', 'is_listed' => 1 ],
    [ 'name' => 'AFFIN HWANG INVESTMENT BANK BERHAD', 'swift_code' => 'HDSBMY2P', 'bank_code' => 'HDSB', 'is_listed' => 0 ],
    [ 'name' => 'AFFIN ISLAMIC BANK BERHAD', 'swift_code' => 'AIBBMYKL', 'bank_code' => 'AIBB', 'is_listed' => 0 ],
    [ 'name' => 'AIA BHD.', 'swift_code' => 'AIACMYKL', 'bank_code' => 'AIAC', 'is_listed' => 0 ],
    [ 'name' => 'BANK PERTANIAN MALAYSIA BERHAD - AGROBANK', 'swift_code' => 'AGOBMYKL', 'bank_code' => 'AGOB', 'is_listed' => 1 ],
    [ 'name' => 'AL RAJHI BANKING AND INVESTMENT CORPORATION (MALAYSIA) BHD', 'swift_code' => 'RJHIMYKL', 'bank_code' => 'RJHI', 'is_listed' => 1 ],
    [ 'name' => 'ALKHAIR INTERNATIONAL ISLAMIC BANK BERHAD', 'swift_code' => 'UIIBMYKL', 'bank_code' => 'UIIB', 'is_listed' => 0 ],
    [ 'name' => 'ALLIANCE BANK MALAYSIA BERHAD', 'swift_code' => 'MFBBMYKL', 'bank_code' => 'MFBB', 'is_listed' => 1 ],
    [ 'name' => 'ALLIANCE INVESTMENT BANK BERHAD', 'swift_code' => 'MBAMMYKL', 'bank_code' => 'MBAM', 'is_listed' => 0 ],
    [ 'name' => 'ALLIANCE ISLAMIC BANK BERHAD', 'swift_code' => 'ALSRMYKL', 'bank_code' => 'ALSR', 'is_listed' => 0 ],
    [ 'name' => 'AMBANK (M) BERHAD', 'swift_code' => 'ARBKMYKL', 'bank_code' => 'ARBK', 'is_listed' => 1 ],
    [ 'name' => 'AMBANK (M) BERHAD LABUAN OFFSHORE BRANCH', 'swift_code' => 'ARBKMYKLLAB', 'bank_code' => 'ARBK', 'is_listed' => 0 ],
    [ 'name' => 'AMINVESTMENT BANK BERHAD', 'swift_code' => 'AMMBMYKL', 'bank_code' => 'AMMB', 'is_listed' => 0 ],
    [ 'name' => 'AMISLAMIC BANK BERHAD', 'swift_code' => 'AISLMYKL', 'bank_code' => 'AISL', 'is_listed' => 0 ],
    [ 'name' => 'ASIAN FINANCE BANK BERHAD', 'swift_code' => 'AFBQMYKL', 'bank_code' => 'AFBQ', 'is_listed' => 0 ],
    [ 'name' => 'ASIAN TRADE INVESTMENT BANK LTD', 'swift_code' => 'ATBLMY2A', 'bank_code' => 'ATBL', 'is_listed' => 0 ],
    [ 'name' => 'BANGKOK BANK BERHAD', 'swift_code' => 'BKKBMYKL', 'bank_code' => 'BKKB', 'is_listed' => 1 ],
    [ 'name' => 'BANK AL HABIB LIMITED', 'swift_code' => 'BAHLMY2A', 'bank_code' => 'BAHL', 'is_listed' => 0 ],
    [ 'name' => 'BANK ISLAM MALAYSIA BERHAD', 'swift_code' => 'BIMBMYKL', 'bank_code' => 'BIMB', 'is_listed' => 1 ],
    [ 'name' => 'BANK ISLAM MALAYSIA BERHAD LABUAN OFFSHORE BRANCH', 'swift_code' => 'BISLMYKA', 'bank_code' => 'BISL', 'is_listed' => 0 ],
    [ 'name' => 'BANK MUAMALAT MALAYSIA BERHAD', 'swift_code' => 'BMMBMYKL', 'bank_code' => 'BMMB', 'is_listed' => 1 ],
    [ 'name' => 'BANK MUAMALAT MALAYSIA BERHAD (TRADE FINANCE)', 'swift_code' => 'BMMBMYKLTFD', 'bank_code' => 'BMMB', 'is_listed' => 0 ],
    [ 'name' => 'BANK NEGARA MALAYSIA (HEAD OFFICE)', 'swift_code' => 'BNMAMYKL', 'bank_code' => 'BNMA', 'is_listed' => 0 ],
    [ 'name' => 'BANK NEGARA MALAYSIA', 'swift_code' => 'BNMAMY2K', 'bank_code' => 'BNMA', 'is_listed' => 0 ],
    [ 'name' => 'BANK OF AMERICA, MALAYSIA BERHAD', 'swift_code' => 'BOFAMY2X', 'bank_code' => 'BOFA', 'is_listed' => 1 ],
    [ 'name' => 'BANK OF AMERICA, MALAYSIA BERHAD', 'swift_code' => 'BOFAMY2XGRC', 'bank_code' => 'BOFA', 'is_listed' => 0 ],
    [ 'name' => 'BANK OF AMERICA, MALAYSIA BERHAD', 'swift_code' => 'BOFAMY2XLMY', 'bank_code' => 'BOFA', 'is_listed' => 0 ],
    [ 'name' => 'BANK OF AMERICA, MALAYSIA BERHAD', 'swift_code' => 'BOFAMY2XLBN', 'bank_code' => 'BOFA', 'is_listed' => 0 ],
    [ 'name' => 'BANK OF CHINA (MALAYSIA) BERHAD', 'swift_code' => 'BKCHMYKL', 'bank_code' => 'BKCH', 'is_listed' => 1 ],
    [ 'name' => 'BANK OF TOKYO-MITSUBISHI UFJ (MALAYSIA) BERHAD', 'swift_code' => 'BOTKMYKX', 'bank_code' => 'BOTK', 'is_listed' => 1 ],
    [ 'name' => 'BANK KERJASAMA RAKYAT MALAYSIA BERHAD (BANK RAKYAT)', 'swift_code' => 'BKRMMYKL', 'bank_code' => 'BKRM', 'is_listed' => 1 ],
    [ 'name' => 'Bank Simpanan Malaysia', 'swift_code' => '', 'bank_code' => '', 'is_listed' => 1 ],
    [ 'name' => 'BNP PARIBAS', 'swift_code' => 'BNPAMYKA', 'bank_code' => 'BNPA', 'is_listed' => 1 ],
    [ 'name' => 'BNP PARIBAS MALAYSIA BERHAD', 'swift_code' => 'BNPAMYKL', 'bank_code' => 'BNPA', 'is_listed' => 0 ],
    [ 'name' => 'BNP PARIBAS MALAYSIA BERHAD (BNPPM ISLAMIC BANKING WINDOW)', 'swift_code' => 'BNPAMYKLSPI', 'bank_code' => 'BNPA', 'is_listed' => 0 ],
    [ 'name' => 'CAGAMAS BERHAD', 'swift_code' => '', 'bank_code' => '', 'is_listed' => 0 ],
    [ 'name' => 'CIMB BANK BERHAD', 'swift_code' => 'CIBBMYKL', 'bank_code' => 'CIBB', 'is_listed' => 1 ],
    [ 'name' => 'CIMB BANK BERHAD (SECURITIES BORROWING AND LENDING)', 'swift_code' => 'CIBBMYKLSBL', 'bank_code' => 'CIBB', 'is_listed' => 0 ],
    [ 'name' => 'CIMB BANK (L) LIMITED', 'swift_code' => 'CIBBMYKA', 'bank_code' => 'CIBB', 'is_listed' => 0 ],
    [ 'name' => 'CIMB BANK BERHAD, LABUAN OFFSHORE BRANCH', 'swift_code' => 'CIBBMY2L', 'bank_code' => 'CIBB', 'is_listed' => 0 ],
    [ 'name' => 'CIMB ISLAMIC BANK BERHAD', 'swift_code' => 'CTBBMYKL', 'bank_code' => 'CTBB', 'is_listed' => 0 ],
    [ 'name' => 'CIMB-PRINCIPAL ASSET MANAGEMENT BERHAD', 'swift_code' => 'CANHMYKL', 'bank_code' => 'CANH', 'is_listed' => 0 ],
    [ 'name' => 'CITIBANK BERHAD (JALAN AMPANG)', 'swift_code' => 'CITIMYKL', 'bank_code' => 'CITI', 'is_listed' => 1 ],
    [ 'name' => 'CITIBANK BERHAD (PENANG BRANCH)', 'swift_code' => 'CITIMYKLPEN', 'bank_code' => 'CITI', 'is_listed' => 0 ],
    [ 'name' => 'CITIBANK BERHAD (JOHOR BAHRU BRANCH)', 'swift_code' => 'CITIMYKLJOD', 'bank_code' => 'CITI', 'is_listed' => 0 ],
    [ 'name' => 'CITIBANK BERHAD (LAB)', 'swift_code' => ' CITIMYKLLAB', 'bank_code' => 'CITI', 'is_listed' => 0 ],
    [ 'name' => 'DBS BANK LTD, LABUAN BRANCH', 'swift_code' => 'DBSSMY2A', 'bank_code' => 'DBSS', 'is_listed' => 0 ],
    [ 'name' => 'DEUTSCHE BANK (MALAYSIA) BERHAD', 'swift_code' => 'DEUTMYKL', 'bank_code' => 'DEUT', 'is_listed' => 1 ],
    [ 'name' => 'DEUTSCHE BANK (MALAYSIA) BERHAD', 'swift_code' => 'DEUTMYKLGMO', 'bank_code' => 'DEUT', 'is_listed' => 0 ],
    [ 'name' => 'DEUTSCHE BANK (MALAYSIA) BERHAD', 'swift_code' => 'DEUTMYKLIBW', 'bank_code' => 'DEUT', 'is_listed' => 0 ],
    [ 'name' => 'DEUTSCHE BANK (MALAYSIA) BERHAD (INTERNATIONAL ISLAMIC BANKING, MALAYSIA BRANCH)', 'swift_code' => 'DEUTMYKLISB', 'bank_code' => 'DEUT', 'is_listed' => 0 ],
    [ 'name' => 'DEUTSCHE BANK (MALAYSIA) BERHAD (LABUAN BRANCH)', 'swift_code' => 'DEUTMYKLBLB', 'bank_code' => 'DEUT', 'is_listed' => 0 ],
    [ 'name' => 'EXPORT-IMPORT BANK OF MALAYSIA BERHAD', 'swift_code' => 'EXMBMYKL', 'bank_code' => 'EXMB', 'is_listed' => 0 ],
    [ 'name' => 'FELDA GLOBAL VENTURES CAPITAL SDN. BHD.', 'swift_code' => 'FGVCMYKL', 'bank_code' => 'FGVC', 'is_listed' => 0 ],
    [ 'name' => 'FIDELITY ASIA BANK LTD', 'swift_code' => 'FABEMY22', 'bank_code' => 'FABE', 'is_listed' => 0 ],
    [ 'name' => 'HONG LEONG BANK BERHAD', 'swift_code' => 'HLBBMYKL', 'bank_code' => 'HLBB', 'is_listed' => 1 ],
    [ 'name' => 'HONG LEONG BANK BERHAD (ISLAMIC BANKING UNIT)', 'swift_code' => 'HLBBMYKLIBU', 'bank_code' => 'HLBB', 'is_listed' => 0 ],
    [ 'name' => 'HONG LEONG BANK BERHAD, JOHOR BAHRU, JOHOR', 'swift_code' => 'HLBBMYKLJBU', 'bank_code' => 'HLBB', 'is_listed' => 0 ],
    [ 'name' => 'HONG LEONG BANK BERHAD, KUCHING, SARAWAK', 'swift_code' => 'HLBBMYKLKCH', 'bank_code' => 'HLBB', 'is_listed' => 0 ],
    [ 'name' => 'HONG LEONG BANK BERHAD, PENANG, PENANG', 'swift_code' => 'HLBBMYKLPNG', 'bank_code' => 'HLBB', 'is_listed' => 0 ],
    [ 'name' => 'HONG LEONG INVESTMENT BANK BERHAD', 'swift_code' => 'HLIVMYKL', 'bank_code' => 'HLIV', 'is_listed' => 0 ],
    [ 'name' => 'HONG LEONG ISLAMIC BANK BERHAD', 'swift_code' => 'HLIBMYKL', 'bank_code' => 'HLIB', 'is_listed' => 0 ],
    [ 'name' => 'THE HONGKONG AND SHANGHAI BANKING CORPORATION LTD.', 'swift_code' => 'HSBCMYKA', 'bank_code' => 'HSBC', 'is_listed' => 0 ],
    [ 'name' => 'HSBC (MALAYSIA) TRUSTEE BERHAD', 'swift_code' => 'HSTMMYKL', 'bank_code' => 'HSTM', 'is_listed' => 0 ],
    [ 'name' => 'HSBC (MALAYSIA) TRUSTEE BERHAD (GLOBAL WEALTH SOLUTIONS)', 'swift_code' => 'HSTMMYKLGWS', 'bank_code' => 'HSTM', 'is_listed' => 0 ],
    [ 'name' => 'HSBC AMANAH MALAYSIA BERHAD', 'swift_code' => 'HMABMYKL', 'bank_code' => 'HMAB', 'is_listed' => 0 ],
    [ 'name' => 'HSBC BANK MALAYSIA BERHAD', 'swift_code' => 'HBMBMYKL', 'bank_code' => 'HBMB', 'is_listed' => 1 ],
    [ 'name' => 'INDIA INTERNATIONAL BANK (MALAYSIA) BERHAD', 'swift_code' => 'IIMBMYKL', 'bank_code' => 'IIMB', 'is_listed' => 0 ],
    [ 'name' => 'INDUSTRIAL AND COMMERCIAL BANK OF CHINA (MALAYSIA) BERHAD.', 'swift_code' => 'ICBKMYKL', 'bank_code' => 'ICBK', 'is_listed' => 1 ],
    [ 'name' => 'INDUSTRIAL AND COMMERCIAL BANK OF CHINA (MALAYSIA) BERHAD., (LABUAN BRANCH)', 'swift_code' => 'ICBKMYKLLAB', 'bank_code' => 'ICBK', 'is_listed' => 0 ],
    [ 'name' => 'J.P.MORGAN CHASE BANK BERHAD', 'swift_code' => 'CHASMYKX', 'bank_code' => 'CHAS', 'is_listed' => 1 ],
    [ 'name' => 'J.P.MORGAN CHASE BANK BERHAD, (JPMORGAN SECURITIES - MALAYSIA)', 'swift_code' => 'CHASMYKXSEC', 'bank_code' => 'CHAS', 'is_listed' => 0 ],
    [ 'name' => 'J.P.MORGAN CHASE BANK BERHAD, (TEST KEY AND BKE ADMINISTRATION)', 'swift_code' => 'CHASMYKXKEY', 'bank_code' => 'CHAS', 'is_listed' => 0 ],
    [ 'name' => 'JPMORGAN CHASE BANK, N.A., LABUAN BRANCH', 'swift_code' => 'CHASMY2A', 'bank_code' => 'CHAS', 'is_listed' => 0 ],
    [ 'name' => 'KAF INVESTMENT BANK BERHAD', 'swift_code' => 'KAFBMYKL', 'bank_code' => 'KAFB', 'is_listed' => 0 ],
    [ 'name' => 'KENANGA INVESTMENT BANK BERHAD', 'swift_code' => 'ECMLMYKL', 'bank_code' => 'ECML', 'is_listed' => 0 ],
    [ 'name' => 'KUWAIT FINANCE HOUSE (MALAYSIA) BERHAD', 'swift_code' => 'KFHOMYKL', 'bank_code' => 'KFHO', 'is_listed' => 1 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK)', 'swift_code' => 'MBBEMYKL', 'bank_code' => 'MBBE', 'is_listed' => 1 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), BUTTERWORTH, PENANG (TRADE FINANCE CENTER) ', 'swift_code' => 'MBBEMYKLBWC', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), IPOH, PERAK', 'swift_code' => 'MBBEMYKLIPH', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), JOHOR BAHRU, JOHOR', 'swift_code' => 'MBBEMYKLJOB', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), KOTA KINABALU, SABAH', 'swift_code' => 'MBBEMYKLKIN', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), KUALA LUMPUR (BANGSAR BARU BRANCH)', 'swift_code' => 'MBBEMYKLBAN', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), KUALA LUMPUR (BUKIT BINTANG BRANCH)', 'swift_code' => 'MBBEMYKLBBG', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), KUALA LUMPUR (CASH MANAGEMENT DEPARTMENT)', 'swift_code' => 'MBBEMYKLWEB', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), KUALA LUMPUR (CUSTODIAN SERVICES DEPARTMENT)', 'swift_code' => 'MBBEMYKLCSD', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), KUALA LUMPUR (KEPONG BRANCH)', 'swift_code' => 'MBBEMYKLKEP', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), KUALA LUMPUR (PUDU BRANCH)', 'swift_code' => 'MBBEMYKLPUD', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), KUALA LUMPUR (SUBANG AIRPORT)', 'swift_code' => 'MBBEMYKLSUB', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), KUALA LUMPUR (TRADE FINANCE CENTER)', 'swift_code' => 'MBBEMYKLKLC', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), KUALA LUMPUR (WISMA SIME DARBY BRANCH)', 'swift_code' => 'MBBEMYKLWSD', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), MALACCA, MALACCA', 'swift_code' => 'MBBEMYKLMAL', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), PASIR GUDANG, JOHOR', 'swift_code' => 'MBBEMYKLPSG', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), PENANG, PENANG (TRADE FINANCE CENTER)', 'swift_code' => 'MBBEMYKLPGC', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), PENANG, PENANG', 'swift_code' => 'MBBEMYKLPEN', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), PETALING JAYA, SELANGOR (TRADE FINANCE CENTER)', 'swift_code' => 'MBBEMYKLPJC', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), PETALING JAYA, SELANGOR (YONG SHOOK LIN BRANCH)', 'swift_code' => 'MBBEMYKLYSL', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), PETALING JAYA, SELANGOR', 'swift_code' => 'MBBEMYKLPJY', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), PORT KLANG, SELANGOR', 'swift_code' => 'MBBEMYKLPKG', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), SEREMBAN, NEGRI SEMBILAN', 'swift_code' => 'MBBEMYKLSBN', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), SHAH ALAM, SELANGOR  (TRADE FINANCE CENTER)', 'swift_code' => 'MBBEMYKLSAC', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), SHAH ALAM, SELANGOR', 'swift_code' => 'MBBEMYKLSHA', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MALAYSIA AIRLINES BERHAD', 'swift_code' => 'MAYHMY22', 'bank_code' => 'MAYH', 'is_listed' => 0 ],
    [ 'name' => 'MAX MONEY SDN BHD', 'swift_code' => 'MMSBMYKL', 'bank_code' => 'MMSB', 'is_listed' => 0 ],
    [ 'name' => 'MAYBANK INTERNATIONAL (L) LTD.', 'swift_code' => 'MBBEMYKA', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MAYBANK INTERNATIONAL LABUAN BRANCH', 'swift_code' => 'MBBEMY2L', 'bank_code' => 'MBBE', 'is_listed' => 0 ],
    [ 'name' => 'MAYBANK INVESTMENT BANK BERHAD', 'swift_code' => 'MBEAMYKL', 'bank_code' => 'MBEA', 'is_listed' => 0 ],
    [ 'name' => 'MAYBANK ISLAMIC BERHAD', 'swift_code' => 'MBISMYKL', 'bank_code' => 'MBIS', 'is_listed' => 0 ],
    [ 'name' => 'MEGA INTERNATIONAL COMMERCIAL BANK CO., LTD. LABUAN BRANCH', 'swift_code' => 'ICBCMY2L', 'bank_code' => 'ICBC', 'is_listed' => 0 ],
    [ 'name' => 'MERCEDES-BENZ MALAYSIA SDN. BHD', 'swift_code' => 'DABEMYKL', 'bank_code' => 'DABE', 'is_listed' => 0 ],
    [ 'name' => 'MERCEDES-BENZ SERVICES MALAYSIA SDN. BHD.', 'swift_code' => 'MBSMMYKL', 'bank_code' => 'MBSM', 'is_listed' => 0 ],
    [ 'name' => 'MIDDLE EAST INVESTMENT BANK LTD', 'swift_code' => 'MEIBMYKA', 'bank_code' => 'MEIB', 'is_listed' => 0 ],
    [ 'name' => 'MIZUHO BANK (MALAYSIA) BERHAD', 'swift_code' => 'MHCBMYKA', 'bank_code' => 'MHCB', 'is_listed' => 1 ],
    [ 'name' => 'MIZUHO BANK, LTD., LABUAN BRANCH', 'swift_code' => 'MHCBMY2L', 'bank_code' => 'MHCB', 'is_listed' => 0 ],
    [ 'name' => 'NATIONAL BANK OF ABU DHABI', 'swift_code' => 'NBADMYKL', 'bank_code' => 'NBAD', 'is_listed' => 0 ],
    [ 'name' => 'NATIONAL BANK OF ABU DHABI, LABUAN', 'swift_code' => 'NBADMYKLLAU', 'bank_code' => 'NBAD', 'is_listed' => 0 ],
    [ 'name' => 'NOMURA ASSET MANAGEMENT MALAYSIA SDN BHD', 'swift_code' => 'NOCMMYKL', 'bank_code' => 'NOCM', 'is_listed' => 0 ],
    [ 'name' => 'OCBC BANK (MALAYSIA) BERHAD', 'swift_code' => 'OCBCMYKL', 'bank_code' => 'OCBC', 'is_listed' => 1 ],
    [ 'name' => 'OCBC AL-AMIN BANK BERHAD', 'swift_code' => 'OABBMYKL', 'bank_code' => 'OABB', 'is_listed' => 0 ],
    [ 'name' => 'PETROLIAM NASIONAL BERHAD', 'swift_code' => 'PTROMYKL', 'bank_code' => 'PTRO', 'is_listed' => 0 ],
    [ 'name' => 'PETROLIAM NASIONAL BERHAD, KUALA LUMPUR (KLCC)', 'swift_code' => 'PTROMYKLFSD', 'bank_code' => 'PTRO', 'is_listed' => 0 ],
    [ 'name' => 'PETRONAS CARIGALI SDN BHD', 'swift_code' => 'PCGLMYKL', 'bank_code' => 'PCGL', 'is_listed' => 0 ],
    [ 'name' => 'PETRONAS TRADING CORPORATION SDN. BHD', 'swift_code' => 'PTRDMYKL', 'bank_code' => 'PTRD', 'is_listed' => 0 ],
    [ 'name' => 'PG ASIA INVESTMENT BANK LTD', 'swift_code' => 'AINEMY22', 'bank_code' => 'AINE', 'is_listed' => 0 ],
    [ 'name' => 'PUBLIC BANK BERHAD', 'swift_code' => 'PBBEMYKL', 'bank_code' => 'PBBE', 'is_listed' => 1 ],
    [ 'name' => 'PUBLIC BANK (L) LTD', 'swift_code' => 'PBLLMYKA', 'bank_code' => 'PBLL', 'is_listed' => 0 ],
    [ 'name' => 'PUBLIC ISLAMIC BANK BERHAD', 'swift_code' => 'PUIBMYKL', 'bank_code' => 'PUIB', 'is_listed' => 0 ],
    [ 'name' => 'RHB BANK BERHAD', 'swift_code' => 'RHBBMYKL', 'bank_code' => 'RHBB', 'is_listed' => 1 ],
    [ 'name' => 'RHB BANK (L) LTD', 'swift_code' => 'RHBBMYKA', 'bank_code' => 'RHBB', 'is_listed' => 0 ],
    [ 'name' => 'RHB INVESTMENT BANK BERHAD', 'swift_code' => 'OSKIMYKL', 'bank_code' => 'OSKI', 'is_listed' => 0 ],
    [ 'name' => 'RHB ISLAMIC BANK BERHAD', 'swift_code' => 'RHBAMYKL', 'bank_code' => 'RHBA', 'is_listed' => 0 ],
    [ 'name' => 'STANDARD CHARTERED BANK MALAYSIA BERHAD', 'swift_code' => 'SCBLMYKX', 'bank_code' => 'SCBL', 'is_listed' => 1 ],
    [ 'name' => 'STANDARD CHARTERED BANK MALAYSIA BERHAD, (LABUAN OFFSHORE BANKING UNIT)', 'swift_code' => 'SCBLMYKXLAB', 'bank_code' => 'SCBL', 'is_listed' => 0 ],
    [ 'name' => 'STANDARD CHARTERED SAADIQ BERHAD', 'swift_code' => 'SCSRMYKK', 'bank_code' => 'SCSR', 'is_listed' => 0 ],
    [ 'name' => 'SUMITOMO MITSUI BANKING CORPORATION MALAYSIA BERHAD', 'swift_code' => 'SMBCMYKL', 'bank_code' => 'SMBC', 'is_listed' => 1 ],
    [ 'name' => 'SUMITOMO MITSUI BANKING CORPORATION', 'swift_code' => 'SMBCMYKA', 'bank_code' => 'SMBC', 'is_listed' => 0 ],
    [ 'name' => 'THE BANK OF NOVA SCOTIA,', 'swift_code' => 'NOSCMY2L', 'bank_code' => 'NOSC', 'is_listed' => 1 ],
    [ 'name' => 'THE BANK OF TOKYO-MITSUBISHI UFJ, LTD. (LABUAN BRANCH)', 'swift_code' => 'BOTKMYKA', 'bank_code' => 'BOTK', 'is_listed' => 0 ],
    [ 'name' => 'THE ROYAL BANK OF SCOTLAND BERHAD ', 'swift_code' => 'ABNAMYKL', 'bank_code' => 'ABNA', 'is_listed' => 1 ],
    [ 'name' => 'THE ROYAL BANK OF SCOTLAND BERHAD, PENANG, PENANG', 'swift_code' => 'ABNAMYKLPNG', 'bank_code' => 'ABNA', 'is_listed' => 0 ],
    [ 'name' => 'THE ROYAL BANK OF SCOTLAND PLC LABUAN BRANCH', 'swift_code' => 'ABNAMY2A', 'bank_code' => 'ABNA', 'is_listed' => 0 ],
    [ 'name' => 'UNITED OVERSEAS BANK (MALAYSIA) BERHAD', 'swift_code' => 'UOVBMYKL', 'bank_code' => 'UOVB', 'is_listed' => 1 ],
    [ 'name' => 'UNITED OVERSEAS BANK (MALAYSIA) BERHAD, (CUSTODIAN AND NOMINEES DEPARTMENT)', 'swift_code' => 'UOVBMYKLCND', 'bank_code' => 'UOVB', 'is_listed' => 0 ],
    [ 'name' => 'UNITED OVERSEAS BANK (MALAYSIA) BERHAD', 'swift_code' => 'UOVBMY2L', 'bank_code' => 'UOVB', 'is_listed' => 0 ],
];
