<?php
/**
 * @author: syafiq <syafiq@my-sands.com>
 * senarai bank & institusi kewangan dalam malaysia + swift code
 * is_listed = 1 // senarai bank yang Sands guna dalam sistem.
 */
 
$items = [
    [ 'name' => 'AFFIN BANK BERHAD', 'swift_code' => 'PHBMMYKL', 'is_listed' => 1 ],
    [ 'name' => 'AFFIN HWANG INVESTMENT BANK BERHAD', 'swift_code' => 'HDSBMY2P', 'is_listed' => 0 ],
    [ 'name' => 'AFFIN ISLAMIC BANK BERHAD', 'swift_code' => 'AIBBMYKL', 'is_listed' => 0 ],
    [ 'name' => 'AIA BHD.', 'swift_code' => 'AIACMYKL', 'is_listed' => 0 ],
    [ 'name' => 'BANK PERTANIAN MALAYSIA BERHAD - AGROBANK', 'swift_code' => 'AGOBMYKL', 'is_listed' => 1 ],
    [ 'name' => 'AL RAJHI BANKING AND INVESTMENT CORPORATION (MALAYSIA) BHD', 'swift_code' => 'RJHIMYKL', 'is_listed' => 1 ],
    [ 'name' => 'ALKHAIR INTERNATIONAL ISLAMIC BANK BERHAD', 'swift_code' => 'UIIBMYKL', 'is_listed' => 0 ],
    [ 'name' => 'ALLIANCE BANK MALAYSIA BERHAD', 'swift_code' => 'MFBBMYKL', 'is_listed' => 1 ],
    [ 'name' => 'ALLIANCE INVESTMENT BANK BERHAD', 'swift_code' => 'MBAMMYKL', 'is_listed' => 0 ],
    [ 'name' => 'ALLIANCE ISLAMIC BANK BERHAD', 'swift_code' => 'ALSRMYKL', 'is_listed' => 0 ],
    [ 'name' => 'AMBANK (M) BERHAD', 'swift_code' => 'ARBKMYKL', 'is_listed' => 1 ],
    [ 'name' => 'AMBANK (M) BERHAD LABUAN OFFSHORE BRANCH', 'swift_code' => 'ARBKMYKLLAB', 'is_listed' => 0 ],
    [ 'name' => 'AMINVESTMENT BANK BERHAD', 'swift_code' => 'AMMBMYKL', 'is_listed' => 0 ],
    [ 'name' => 'AMISLAMIC BANK BERHAD', 'swift_code' => 'AISLMYKL', 'is_listed' => 0 ],
    [ 'name' => 'ASIAN FINANCE BANK BERHAD', 'swift_code' => 'AFBQMYKL', 'is_listed' => 0 ],
    [ 'name' => 'ASIAN TRADE INVESTMENT BANK LTD', 'swift_code' => 'ATBLMY2A', 'is_listed' => 0 ],
    [ 'name' => 'BANGKOK BANK BERHAD', 'swift_code' => 'BKKBMYKL', 'is_listed' => 1 ],
    [ 'name' => 'BANK AL HABIB LIMITED', 'swift_code' => 'BAHLMY2A', 'is_listed' => 0 ],
    [ 'name' => 'BANK ISLAM MALAYSIA BERHAD', 'swift_code' => 'BIMBMYKL', 'is_listed' => 1 ],
    [ 'name' => 'BANK ISLAM MALAYSIA BERHAD LABUAN OFFSHORE BRANCH', 'swift_code' => 'BISLMYKA', 'is_listed' => 0 ],
    [ 'name' => 'BANK MUAMALAT MALAYSIA BERHAD', 'swift_code' => 'BMMBMYKL', 'is_listed' => 1 ],
    [ 'name' => 'BANK MUAMALAT MALAYSIA BERHAD (TRADE FINANCE)', 'swift_code' => 'BMMBMYKLTFD', 'is_listed' => 0 ],
    [ 'name' => 'BANK NEGARA MALAYSIA (HEAD OFFICE)', 'swift_code' => 'BNMAMYKL', 'is_listed' => 0 ],
    [ 'name' => 'BANK NEGARA MALAYSIA', 'swift_code' => 'BNMAMY2K', 'is_listed' => 0 ],
    [ 'name' => 'BANK OF AMERICA, MALAYSIA BERHAD', 'swift_code' => 'BOFAMY2X', 'is_listed' => 1 ],
    [ 'name' => 'BANK OF AMERICA, MALAYSIA BERHAD', 'swift_code' => 'BOFAMY2XGRC', 'is_listed' => 0 ],
    [ 'name' => 'BANK OF AMERICA, MALAYSIA BERHAD', 'swift_code' => 'BOFAMY2XLMY', 'is_listed' => 0 ],
    [ 'name' => 'BANK OF AMERICA, MALAYSIA BERHAD', 'swift_code' => 'BOFAMY2XLBN', 'is_listed' => 0 ],
    [ 'name' => 'BANK OF CHINA (MALAYSIA) BERHAD', 'swift_code' => 'BKCHMYKL', 'is_listed' => 1 ],
    [ 'name' => 'BANK OF TOKYO-MITSUBISHI UFJ (MALAYSIA) BERHAD', 'swift_code' => 'BOTKMYKX', 'is_listed' => 1 ],
    [ 'name' => 'BANK KERJASAMA RAKYAT MALAYSIA BERHAD (BANK RAKYAT)', 'swift_code' => 'BKRMMYKL', 'is_listed' => 1 ],
    [ 'name' => 'Bank Simpanan Malaysia', 'swift_code' => '', 'is_listed' => 1 ],
    [ 'name' => 'BNP PARIBAS', 'swift_code' => 'BNPAMYKA', 'is_listed' => 1 ],
    [ 'name' => 'BNP PARIBAS MALAYSIA BERHAD', 'swift_code' => 'BNPAMYKL', 'is_listed' => 0 ],
    [ 'name' => 'BNP PARIBAS MALAYSIA BERHAD (BNPPM ISLAMIC BANKING WINDOW)', 'swift_code' => 'BNPAMYKLSPI', 'is_listed' => 0 ],
    [ 'name' => 'CAGAMAS BERHAD', 'swift_code' => '', 'is_listed' => 0 ],
    [ 'name' => 'CIMB BANK BERHAD', 'swift_code' => 'CIBBMYKL', 'is_listed' => 1 ],
    [ 'name' => 'CIMB BANK BERHAD (SECURITIES BORROWING AND LENDING)', 'swift_code' => 'CIBBMYKLSBL', 'is_listed' => 0 ],
    [ 'name' => 'CIMB BANK (L) LIMITED', 'swift_code' => 'CIBBMYKA', 'is_listed' => 0 ],
    [ 'name' => 'CIMB BANK BERHAD, LABUAN OFFSHORE BRANCH', 'swift_code' => 'CIBBMY2L', 'is_listed' => 0 ],
    [ 'name' => 'CIMB ISLAMIC BANK BERHAD', 'swift_code' => 'CTBBMYKL', 'is_listed' => 0 ],
    [ 'name' => 'CIMB-PRINCIPAL ASSET MANAGEMENT BERHAD', 'swift_code' => 'CANHMYKL', 'is_listed' => 0 ],
    [ 'name' => 'CITIBANK BERHAD (JALAN AMPANG)', 'swift_code' => 'CITIMYKL', 'is_listed' => 1 ],
    [ 'name' => 'CITIBANK BERHAD (PENANG BRANCH)', 'swift_code' => 'CITIMYKLPEN', 'is_listed' => 0 ],
    [ 'name' => 'CITIBANK BERHAD (JOHOR BAHRU BRANCH)', 'swift_code' => 'CITIMYKLJOD', 'is_listed' => 0 ],
    [ 'name' => 'CITIBANK BERHAD (LAB)', 'swift_code' => ' CITIMYKLLAB', 'is_listed' => 0 ],
    [ 'name' => 'DBS BANK LTD, LABUAN BRANCH', 'swift_code' => 'DBSSMY2A', 'is_listed' => 0 ],
    [ 'name' => 'DEUTSCHE BANK (MALAYSIA) BERHAD', 'swift_code' => 'DEUTMYKL', 'is_listed' => 1 ],
    [ 'name' => 'DEUTSCHE BANK (MALAYSIA) BERHAD', 'swift_code' => 'DEUTMYKLGMO', 'is_listed' => 0 ],
    [ 'name' => 'DEUTSCHE BANK (MALAYSIA) BERHAD', 'swift_code' => 'DEUTMYKLIBW', 'is_listed' => 0 ],
    [ 'name' => 'DEUTSCHE BANK (MALAYSIA) BERHAD (INTERNATIONAL ISLAMIC BANKING, MALAYSIA BRANCH)', 'swift_code' => 'DEUTMYKLISB', 'is_listed' => 0 ],
    [ 'name' => 'DEUTSCHE BANK (MALAYSIA) BERHAD (LABUAN BRANCH)', 'swift_code' => 'DEUTMYKLBLB', 'is_listed' => 0 ],
    [ 'name' => 'EXPORT-IMPORT BANK OF MALAYSIA BERHAD', 'swift_code' => 'EXMBMYKL', 'is_listed' => 0 ],
    [ 'name' => 'FELDA GLOBAL VENTURES CAPITAL SDN. BHD.', 'swift_code' => 'FGVCMYKL', 'is_listed' => 0 ],
    [ 'name' => 'FIDELITY ASIA BANK LTD', 'swift_code' => 'FABEMY22', 'is_listed' => 0 ],
    [ 'name' => 'HONG LEONG BANK BERHAD', 'swift_code' => 'HLBBMYKL', 'is_listed' => 1 ],
    [ 'name' => 'HONG LEONG BANK BERHAD (ISLAMIC BANKING UNIT)', 'swift_code' => 'HLBBMYKLIBU', 'is_listed' => 0 ],
    [ 'name' => 'HONG LEONG BANK BERHAD, JOHOR BAHRU, JOHOR', 'swift_code' => 'HLBBMYKLJBU', 'is_listed' => 0 ],
    [ 'name' => 'HONG LEONG BANK BERHAD, KUCHING, SARAWAK', 'swift_code' => 'HLBBMYKLKCH', 'is_listed' => 0 ],
    [ 'name' => 'HONG LEONG BANK BERHAD, PENANG, PENANG', 'swift_code' => 'HLBBMYKLPNG', 'is_listed' => 0 ],
    [ 'name' => 'HONG LEONG INVESTMENT BANK BERHAD', 'swift_code' => 'HLIVMYKL', 'is_listed' => 0 ],
    [ 'name' => 'HONG LEONG ISLAMIC BANK BERHAD', 'swift_code' => 'HLIBMYKL', 'is_listed' => 0 ],
    [ 'name' => 'THE HONGKONG AND SHANGHAI BANKING CORPORATION LTD.', 'swift_code' => 'HSBCMYKA', 'is_listed' => 0 ],
    [ 'name' => 'HSBC (MALAYSIA) TRUSTEE BERHAD', 'swift_code' => 'HSTMMYKL', 'is_listed' => 0 ],
    [ 'name' => 'HSBC (MALAYSIA) TRUSTEE BERHAD (GLOBAL WEALTH SOLUTIONS)', 'swift_code' => 'HSTMMYKLGWS', 'is_listed' => 0 ],
    [ 'name' => 'HSBC AMANAH MALAYSIA BERHAD', 'swift_code' => 'HMABMYKL', 'is_listed' => 0 ],
    [ 'name' => 'HSBC BANK MALAYSIA BERHAD', 'swift_code' => 'HBMBMYKL', 'is_listed' => 1 ],
    [ 'name' => 'INDIA INTERNATIONAL BANK (MALAYSIA) BERHAD', 'swift_code' => 'IIMBMYKL', 'is_listed' => 0 ],
    [ 'name' => 'INDUSTRIAL AND COMMERCIAL BANK OF CHINA (MALAYSIA) BERHAD.', 'swift_code' => 'ICBKMYKL', 'is_listed' => 1 ],
    [ 'name' => 'INDUSTRIAL AND COMMERCIAL BANK OF CHINA (MALAYSIA) BERHAD., (LABUAN BRANCH)', 'swift_code' => 'ICBKMYKLLAB', 'is_listed' => 0 ],
    [ 'name' => 'J.P.MORGAN CHASE BANK BERHAD', 'swift_code' => 'CHASMYKX', 'is_listed' => 1 ],
    [ 'name' => 'J.P.MORGAN CHASE BANK BERHAD, (JPMORGAN SECURITIES - MALAYSIA)', 'swift_code' => 'CHASMYKXSEC', 'is_listed' => 0 ],
    [ 'name' => 'J.P.MORGAN CHASE BANK BERHAD, (TEST KEY AND BKE ADMINISTRATION)', 'swift_code' => 'CHASMYKXKEY', 'is_listed' => 0 ],
    [ 'name' => 'JPMORGAN CHASE BANK, N.A., LABUAN BRANCH', 'swift_code' => 'CHASMY2A', 'is_listed' => 0 ],
    [ 'name' => 'KAF INVESTMENT BANK BERHAD', 'swift_code' => 'KAFBMYKL', 'is_listed' => 0 ],
    [ 'name' => 'KENANGA INVESTMENT BANK BERHAD', 'swift_code' => 'ECMLMYKL', 'is_listed' => 0 ],
    [ 'name' => 'KUWAIT FINANCE HOUSE (MALAYSIA) BERHAD', 'swift_code' => 'KFHOMYKL', 'is_listed' => 1 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK)', 'swift_code' => 'MBBEMYKL', 'is_listed' => 1 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), BUTTERWORTH, PENANG (TRADE FINANCE CENTER) ', 'swift_code' => 'MBBEMYKLBWC', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), IPOH, PERAK', 'swift_code' => 'MBBEMYKLIPH', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), JOHOR BAHRU, JOHOR', 'swift_code' => 'MBBEMYKLJOB', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), KOTA KINABALU, SABAH', 'swift_code' => 'MBBEMYKLKIN', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), KUALA LUMPUR (BANGSAR BARU BRANCH)', 'swift_code' => 'MBBEMYKLBAN', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), KUALA LUMPUR (BUKIT BINTANG BRANCH)', 'swift_code' => 'MBBEMYKLBBG', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), KUALA LUMPUR (CASH MANAGEMENT DEPARTMENT)', 'swift_code' => 'MBBEMYKLWEB', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), KUALA LUMPUR (CUSTODIAN SERVICES DEPARTMENT)', 'swift_code' => 'MBBEMYKLCSD', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), KUALA LUMPUR (KEPONG BRANCH)', 'swift_code' => 'MBBEMYKLKEP', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), KUALA LUMPUR (PUDU BRANCH)', 'swift_code' => 'MBBEMYKLPUD', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), KUALA LUMPUR (SUBANG AIRPORT)', 'swift_code' => 'MBBEMYKLSUB', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), KUALA LUMPUR (TRADE FINANCE CENTER)', 'swift_code' => 'MBBEMYKLKLC', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), KUALA LUMPUR (WISMA SIME DARBY BRANCH)', 'swift_code' => 'MBBEMYKLWSD', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), MALACCA, MALACCA', 'swift_code' => 'MBBEMYKLMAL', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), PASIR GUDANG, JOHOR', 'swift_code' => 'MBBEMYKLPSG', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), PENANG, PENANG (TRADE FINANCE CENTER)', 'swift_code' => 'MBBEMYKLPGC', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), PENANG, PENANG', 'swift_code' => 'MBBEMYKLPEN', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), PETALING JAYA, SELANGOR (TRADE FINANCE CENTER)', 'swift_code' => 'MBBEMYKLPJC', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), PETALING JAYA, SELANGOR (YONG SHOOK LIN BRANCH)', 'swift_code' => 'MBBEMYKLYSL', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), PETALING JAYA, SELANGOR', 'swift_code' => 'MBBEMYKLPJY', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), PORT KLANG, SELANGOR', 'swift_code' => 'MBBEMYKLPKG', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), SEREMBAN, NEGRI SEMBILAN', 'swift_code' => 'MBBEMYKLSBN', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), SHAH ALAM, SELANGOR  (TRADE FINANCE CENTER)', 'swift_code' => 'MBBEMYKLSAC', 'is_listed' => 0 ],
    [ 'name' => 'MALAYAN BANKING BERHAD (MAYBANK), SHAH ALAM, SELANGOR', 'swift_code' => 'MBBEMYKLSHA', 'is_listed' => 0 ],
    [ 'name' => 'MALAYSIA AIRLINES BERHAD', 'swift_code' => 'MAYHMY22', 'is_listed' => 0 ],
    [ 'name' => 'MAX MONEY SDN BHD', 'swift_code' => 'MMSBMYKL', 'is_listed' => 0 ],
    [ 'name' => 'MAYBANK INTERNATIONAL (L) LTD.', 'swift_code' => 'MBBEMYKA', 'is_listed' => 0 ],
    [ 'name' => 'MAYBANK INTERNATIONAL LABUAN BRANCH', 'swift_code' => 'MBBEMY2L', 'is_listed' => 0 ],
    [ 'name' => 'MAYBANK INVESTMENT BANK BERHAD', 'swift_code' => 'MBEAMYKL', 'is_listed' => 0 ],
    [ 'name' => 'MAYBANK ISLAMIC BERHAD', 'swift_code' => 'MBISMYKL', 'is_listed' => 0 ],
    [ 'name' => 'MEGA INTERNATIONAL COMMERCIAL BANK CO., LTD. LABUAN BRANCH', 'swift_code' => 'ICBCMY2L', 'is_listed' => 0 ],
    [ 'name' => 'MERCEDES-BENZ MALAYSIA SDN. BHD', 'swift_code' => 'DABEMYKL', 'is_listed' => 0 ],
    [ 'name' => 'MERCEDES-BENZ SERVICES MALAYSIA SDN. BHD.', 'swift_code' => 'MBSMMYKL', 'is_listed' => 0 ],
    [ 'name' => 'MIDDLE EAST INVESTMENT BANK LTD', 'swift_code' => 'MEIBMYKA', 'is_listed' => 0 ],
    [ 'name' => 'MIZUHO BANK (MALAYSIA) BERHAD', 'swift_code' => 'MHCBMYKA', 'is_listed' => 1 ],
    [ 'name' => 'MIZUHO BANK, LTD., LABUAN BRANCH', 'swift_code' => 'MHCBMY2L', 'is_listed' => 0 ],
    [ 'name' => 'NATIONAL BANK OF ABU DHABI', 'swift_code' => 'NBADMYKL', 'is_listed' => 0 ],
    [ 'name' => 'NATIONAL BANK OF ABU DHABI, LABUAN', 'swift_code' => 'NBADMYKLLAU', 'is_listed' => 0 ],
    [ 'name' => 'NOMURA ASSET MANAGEMENT MALAYSIA SDN BHD', 'swift_code' => 'NOCMMYKL', 'is_listed' => 0 ],
    [ 'name' => 'OCBC BANK (MALAYSIA) BERHAD', 'swift_code' => 'OCBCMYKL', 'is_listed' => 1 ],
    [ 'name' => 'OCBC AL-AMIN BANK BERHAD', 'swift_code' => 'OABBMYKL', 'is_listed' => 0 ],
    [ 'name' => 'PETROLIAM NASIONAL BERHAD', 'swift_code' => 'PTROMYKL', 'is_listed' => 0 ],
    [ 'name' => 'PETROLIAM NASIONAL BERHAD, KUALA LUMPUR (KLCC)', 'swift_code' => 'PTROMYKLFSD', 'is_listed' => 0 ],
    [ 'name' => 'PETRONAS CARIGALI SDN BHD', 'swift_code' => 'PCGLMYKL', 'is_listed' => 0 ],
    [ 'name' => 'PETRONAS TRADING CORPORATION SDN. BHD', 'swift_code' => 'PTRDMYKL', 'is_listed' => 0 ],
    [ 'name' => 'PG ASIA INVESTMENT BANK LTD', 'swift_code' => 'AINEMY22', 'is_listed' => 0 ],
    [ 'name' => 'PUBLIC BANK BERHAD', 'swift_code' => 'PBBEMYKL', 'is_listed' => 1 ],
    [ 'name' => 'PUBLIC BANK (L) LTD', 'swift_code' => 'PBLLMYKA', 'is_listed' => 0 ],
    [ 'name' => 'PUBLIC ISLAMIC BANK BERHAD', 'swift_code' => 'PUIBMYKL', 'is_listed' => 0 ],
    [ 'name' => 'RHB BANK BERHAD', 'swift_code' => 'RHBBMYKL', 'is_listed' => 1 ],
    [ 'name' => 'RHB BANK (L) LTD', 'swift_code' => 'RHBBMYKA', 'is_listed' => 0 ],
    [ 'name' => 'RHB INVESTMENT BANK BERHAD', 'swift_code' => 'OSKIMYKL', 'is_listed' => 0 ],
    [ 'name' => 'RHB ISLAMIC BANK BERHAD', 'swift_code' => 'RHBAMYKL', 'is_listed' => 0 ],
    [ 'name' => 'STANDARD CHARTERED BANK MALAYSIA BERHAD', 'swift_code' => 'SCBLMYKX', 'is_listed' => 1 ],
    [ 'name' => 'STANDARD CHARTERED BANK MALAYSIA BERHAD, (LABUAN OFFSHORE BANKING UNIT)', 'swift_code' => 'SCBLMYKXLAB', 'is_listed' => 0 ],
    [ 'name' => 'STANDARD CHARTERED SAADIQ BERHAD', 'swift_code' => 'SCSRMYKK', 'is_listed' => 0 ],
    [ 'name' => 'SUMITOMO MITSUI BANKING CORPORATION MALAYSIA BERHAD', 'swift_code' => 'SMBCMYKL', 'is_listed' => 1 ],
    [ 'name' => 'SUMITOMO MITSUI BANKING CORPORATION', 'swift_code' => 'SMBCMYKA', 'is_listed' => 0 ],
    [ 'name' => 'THE BANK OF NOVA SCOTIA,', 'swift_code' => 'NOSCMY2L', 'is_listed' => 1 ],
    [ 'name' => 'THE BANK OF TOKYO-MITSUBISHI UFJ, LTD. (LABUAN BRANCH)', 'swift_code' => 'BOTKMYKA', 'is_listed' => 0 ],
    [ 'name' => 'THE ROYAL BANK OF SCOTLAND BERHAD ', 'swift_code' => 'ABNAMYKL', 'is_listed' => 1 ],
    [ 'name' => 'THE ROYAL BANK OF SCOTLAND BERHAD, PENANG, PENANG', 'swift_code' => 'ABNAMYKLPNG', 'is_listed' => 0 ],
    [ 'name' => 'THE ROYAL BANK OF SCOTLAND PLC LABUAN BRANCH', 'swift_code' => 'ABNAMY2A', 'is_listed' => 0 ],
    [ 'name' => 'UNITED OVERSEAS BANK (MALAYSIA) BERHAD', 'swift_code' => 'UOVBMYKL', 'is_listed' => 1 ],
    [ 'name' => 'UNITED OVERSEAS BANK (MALAYSIA) BERHAD, (CUSTODIAN AND NOMINEES DEPARTMENT)', 'swift_code' => 'UOVBMYKLCND', 'is_listed' => 0 ],
    [ 'name' => 'UNITED OVERSEAS BANK (MALAYSIA) BERHAD', 'swift_code' => 'UOVBMY2L', 'is_listed' => 0 ],
];
