</php

// upgrade from race data. refer to https://www.dosm.gov.my/v1/uploads/files/4_Portal%20Content/Codes_Cassification/Etnik.pdf

$data = [
  ['code' => 1100, 'name' => 'Melayu'],
  ['code' => 2000, 'name' => 'Orang Asli Semenanjung', 'is_collective' => 1, 'child' => [
      ['code' => 2111, 'name' => 'Negrito', 'is_collective' => 1, 'child' => [
          ['code' => 211101, 'name' => 'Bateq'],
          ['code' => 211102, 'name' => 'Jahai'],
          ['code' => 211103, 'name' => 'Kensiu'],
          ['code' => 211104, 'name' => 'Kintak'],
          ['code' => 211105, 'name' => 'Lanoh'],
          ['code' => 211106, 'name' => 'Mendriq'],
      ]],
      ['code' => 2121, 'name' => 'Senoi / Sakai', 'is_collective' => 1, 'child' => [
          ['code' => 212101, 'name' => 'Che Wong'],
          ['code' => 212102, 'name' => 'Jahut'],
          ['code' => 212103, 'name' => 'Mah Meri'],
          ['code' => 212104, 'name' => 'Semai'],
          ['code' => 212105, 'name' => 'Semoq Beri'],
          ['code' => 212106, 'name' => 'Temiar'],
      ]],
      ['code' => 2131, 'name' => 'Melayu Proto', 'is_collective' => 1, 'child' => [
          ['code' => 213101, 'name' => 'Jakun'],
          ['code' => 213102, 'name' => 'Orang Kanaq'],
          ['code' => 213103, 'name' => 'Orang Kuala'],
          ['code' => 213104, 'name' => 'Orang Seletar'],
          ['code' => 213105, 'name' => 'Semalai'],
          ['code' => 213106, 'name' => 'Temuan'],
      ]],
  ]],
  ['code' => 3000, 'name' => 'Bumiputera Sabah', 'is_collective' => 1, 'child' => [
      ['code' => 3110, 'name' => 'Bajau / Sama', 'is_collective' => 1, 'child' => [
          ['code' => 311001, 'name' => 'Bajau Laut / Sama Delaut'],
          ['code' => 311002, 'name' => 'Baugingi / Balangingi'],
          ['code' => 311003, 'name' => 'Binadan / Bannaran'],
          ['code' => 311004, 'name' => 'Kagayun'],
          ['code' => 311005, 'name' => 'Kubang'],
          ['code' => 311006, 'name' => 'Samar Layun'],
          ['code' => 311007, 'name' => "Sibutu'"],
          ['code' => 311008, 'name' => 'Sikubung'],
          ['code' => 311009, 'name' => 'Simunul'],
          ['code' => 311010, 'name' => 'Ubian / Obian'],
      ]],
      ['code' => 3120, 'name' => 'Balabak / Molbog'],
      ['code' => 3130, 'name' => 'Bisaya / Bisayah'],
      ['code' => 3140, 'name' => 'Bulongan'],
      ['code' => 3160, 'name' => "Idahan / Ida'an", 'is_collective' => 1, 'child' => [
          ['code' => 316001, 'name' => 'Begahak / Begaak'],
          ['code' => 316002, 'name' => 'Buludupi'],
          ['code' => 316003, 'name' => "Saba'an"],
          ['code' => 316004, 'name' => "Segai'"],
          ['code' => 316005, 'name' => 'Sibuko'],
          ['code' => 316006, 'name' => 'Tagalong'],
      ]],
      ['code' => 3170, 'name' => 'Iranun / Ilanun'],
      ['code' => 3180, 'name' => 'Kadayan / Kedayan'],
      ['code' => 3190, 'name' => 'Kadazandusun / Dusun / Kadazan', 'is_collective' => 1, 'child' => [
          ['code' => 319001, 'name' => 'Kadazan'],
          ['code' => 319002, 'name' => 'Dusun'],
          ['code' => 319003, 'name' => 'Bangkaakon'],
          ['code' => 319004, 'name' => 'Bisaya'],
          ['code' => 319005, 'name' => 'Bonggi'],
          ['code' => 319006, 'name' => 'Bundu'],
          ['code' => 319007, 'name' => 'Dalamason'],
          ['code' => 319008, 'name' => 'Dumpas'],
          ['code' => 319009, 'name' => 'Gano'],
          ['code' => 319010, 'name' => 'Garo'],
          ['code' => 319011, 'name' => 'Gobukon'],
          ['code' => 319012, 'name' => 'Gunatong'],
          ['code' => 319013, 'name' => 'Kapazan'],
          ['code' => 319014, 'name' => 'Kavananan'],
          ['code' => 319015, 'name' => 'Kawakahan'],
          ['code' => 319016, 'name' => 'Kimaragang'],
          ['code' => 319017, 'name' => 'Kinasaraban'],
          ['code' => 319018, 'name' => 'Kionop'],
          ['code' => 319019, 'name' => 'Kisayap'],
          ['code' => 319020, 'name' => 'Kisoko'],
          ['code' => 319021, 'name' => 'Kiundu'],
          ['code' => 319022, 'name' => 'Kivulu'],
          ['code' => 319023, 'name' => 'Kogibangan'],
          ['code' => 319024, 'name' => 'Kogosingan'],
          ['code' => 319025, 'name' => 'Kohub'],
          ['code' => 319026, 'name' => 'Kolikuan'],
          ['code' => 319027, 'name' => 'Koroli'],
          ['code' => 319028, 'name' => 'Kososoluan'],
          ['code' => 319029, 'name' => 'Kudundung'],
          ['code' => 319030, 'name' => 'Kuijau / Kwijau'],
          ['code' => 319031, 'name' => 'Kuriou'],
          ['code' => 319032, 'name' => 'Kurulu'],
          ['code' => 319033, 'name' => 'Limbutung'],
          ['code' => 319034, 'name' => 'Lingkabau'],
          ['code' => 319035, 'name' => 'Liwan'],
          ['code' => 319036, 'name' => 'Liwogu'],
          ['code' => 319037, 'name' => 'Lotud'],
          ['code' => 319038, 'name' => 'Luba'],
          ['code' => 319039, 'name' => 'Malapi'],
          ['code' => 319040, 'name' => 'Manampahu'],
          ['code' => 319041, 'name' => 'Mangkaak'],
          ['code' => 319042, 'name' => 'Tompias'],
          ['code' => 319043, 'name' => 'Tompulung'],
          ['code' => 319044, 'name' => 'Tonggilan'],
          ['code' => 319045, 'name' => 'Tuhawon'],
          ['code' => 319046, 'name' => 'Turavid'],
          ['code' => 319047, 'name' => 'Tutung'],
      ]],
      ['code' => 3210, 'name' => 'Melayu Brunei / Brunei'],
      ['code' => 3220, 'name' => 'Murut', 'is_collective' => 1, 'child' => [
          ['code' => 322001, 'name' => 'Alumbis'],
          ['code' => 322002, 'name' => 'Baukan'],
          ['code' => 322003, 'name' => 'Bilak'],
          ['code' => 322004, 'name' => 'Gana'],
          ['code' => 322005, 'name' => 'Kalabakan'],
          ['code' => 322006, 'name' => 'Kolod'],
          ['code' => 322007, 'name' => 'Kolor'],
          ['code' => 322008, 'name' => 'Lundayeh'],
          ['code' => 322009, 'name' => 'Mengalong'],
          ['code' => 322010, 'name' => 'Milian'],
          ['code' => 322011, 'name' => 'Mokioliga'],
          ['code' => 322012, 'name' => 'Nabai'],
          ['code' => 322013, 'name' => 'Pagalan'],
          ['code' => 322014, 'name' => 'Paluan'],
          ['code' => 322015, 'name' => 'Pamatang'],
          ['code' => 322016, 'name' => 'Rundum'],
          ['code' => 322017, 'name' => 'Sandiwar'],
          ['code' => 322018, 'name' => 'Selungai'],
          ['code' => 322019, 'name' => 'Semambu'],
          ['code' => 322020, 'name' => 'Sembakung'],
          ['code' => 322021, 'name' => 'Serudung'],
          ['code' => 322022, 'name' => 'Salilir'],
          ['code' => 322023, 'name' => 'Sinambu'],
          ['code' => 322024, 'name' => 'Tagol / Taho'],
          ['code' => 322025, 'name' => 'Takapan'],
          ['code' => 322026, 'name' => 'Tengara'],
          ['code' => 322027, 'name' => 'Timungon'],
          ['code' => 322028, 'name' => 'Tolokoson'],
      ]],
      ['code' => 3230, 'name' => 'Orang Sungai / Sungoi', 'is_collective' => 1, 'child' => [
          ['code' => 323001, 'name' => 'Abai Sungai'],
          ['code' => 323002, 'name' => 'Dewara'],
          ['code' => 323003, 'name' => 'Inukang'],
          ['code' => 323004, 'name' => 'Kolobuan'],
          ['code' => 323005, 'name' => 'Kuamut'],
          ['code' => 323006, 'name' => 'Labuk'],
          ['code' => 323007, 'name' => 'Lamag'],
          ['code' => 323008, 'name' => 'Lingkabau'],
          ['code' => 323009, 'name' => 'Lobu'],
          ['code' => 323010, 'name' => 'Lolobuon'],
          ['code' => 323011, 'name' => 'Makiang'],
          ['code' => 323012, 'name' => 'Marudu'],
          ['code' => 323013, 'name' => 'Mengalong'],
          ['code' => 323014, 'name' => 'Minansut'],
          ['code' => 323015, 'name' => 'Minokok'],
          ['code' => 323016, 'name' => 'Mokioliga'],
          ['code' => 323017, 'name' => 'Molobong'],
          ['code' => 323018, 'name' => 'Nandal'],
          ['code' => 323019, 'name' => 'Pagalan'],
          ['code' => 323020, 'name' => 'Paluan'],
          ['code' => 323021, 'name' => 'Pamatang'],
          ['code' => 323022, 'name' => 'Papar'],
          ['code' => 323023, 'name' => 'Perudou'],
          ['code' => 323024, 'name' => 'Pilantong'],
          ['code' => 323025, 'name' => 'Pinagas'],
          ['code' => 323026, 'name' => 'Pingas'],
          ['code' => 323027, 'name' => 'Pinousuk'],
          ['code' => 323028, 'name' => 'Poiton / Paitan'],
          ['code' => 323029, 'name' => 'Potiukan'],
          ['code' => 323030, 'name' => 'Puawang'],
          ['code' => 323031, 'name' => 'Putih'],
          ['code' => 323032, 'name' => 'Rumanau'],
          ['code' => 323033, 'name' => 'Rungus (Orang Sungai / Sungoi)'],
          ['code' => 323034, 'name' => 'Sabangan'],
          ['code' => 323035, 'name' => 'Sandayo / Sundayo'],
          ['code' => 323036, 'name' => 'Sarayo'],
          ['code' => 323037, 'name' => 'Segama'],
          ['code' => 323038, 'name' => 'Segamo'],
          ['code' => 323039, 'name' => 'Sikubayan'],
          ['code' => 323040, 'name' => 'Sinandapak'],
          ['code' => 323041, 'name' => 'Sinobu'],
          ['code' => 323042, 'name' => 'Sinorupa / Sinorupo'],
          ['code' => 323043, 'name' => 'Sinulihan'],
          ['code' => 323044, 'name' => 'Sogililon'],
          ['code' => 323045, 'name' => 'Sogilitan'],
          ['code' => 323046, 'name' => 'Sogo'],
          ['code' => 323047, 'name' => 'Sonsogon'],
          ['code' => 323048, 'name' => 'Suang Lotud'],
          ['code' => 323049, 'name' => 'Subpan/ Sugpan'],
          ['code' => 323050, 'name' => 'Sugut (Kadazan)'],
          ['code' => 323051, 'name' => 'Sukang'],
          ['code' => 323052, 'name' => 'Sumambu'],
          ['code' => 323053, 'name' => 'Sungai / Sungoi'],
          ['code' => 323054, 'name' => 'Sungangon'],
          ['code' => 323055, 'name' => 'Tagabas'],
          ['code' => 323056, 'name' => 'Talantang'],
          ['code' => 323057, 'name' => 'Tandan'],
          ['code' => 323058, 'name' => 'Tangara'],
          ['code' => 323059, 'name' => 'Tatana'],
          ['code' => 323060, 'name' => 'Tibabar'],
          ['code' => 323061, 'name' => 'Tidung'],
          ['code' => 323062, 'name' => 'Tilau-Ilau'],
          ['code' => 323063, 'name' => 'Tinagas'],
          ['code' => 323064, 'name' => 'Tindakon'],
          ['code' => 323065, 'name' => 'Tindal'],
          ['code' => 323066, 'name' => 'Tingalun'],
          ['code' => 323067, 'name' => 'Tinggalan'],
          ['code' => 323068, 'name' => 'Tobilung'],
          ['code' => 323069, 'name' => 'Tolinting'],
          ['code' => 323070, 'name' => 'Tombonuo'],
      ]],
      ['code' => 3240, 'name' => 'Rungus', 'is_collective' => 1, 'child' => [
          ['code' => 324001, 'name' => 'Gandohon'],
          ['code' => 324002, 'name' => 'Gonsomon'],
          ['code' => 324003, 'name' => 'Nuluu'],
          ['code' => 324004, 'name' => 'Pilapazan'],
      ]],
      ['code' => 3250, 'name' => 'Suluk'],
      ['code' => 3260, 'name' => 'Lundayeh / Lundayuh'],
      ['code' => 3998, 'name' => 'Bumiputera Sabah Lain', 'is_collective' => 1, 'child' => [
          ['code' => 399801, 'name' => 'Jawa, Bugis, Banjar (Sabah)'],
          ['code' => 399802, 'name' => 'Bumiputera Sabah Lain-lain'],
      ]],
  ]],
  ['code' => 4000, 'name' => 'Bumiputera Sarawak', 'is_collective' => 1, 'child' => [
      ['code' => 4010, 'name' => 'Bah Mali'],
      ['code' => 4020, 'name' => 'Bakong'],
      ['code' => 4030, 'name' => 'Berawan'],
      ['code' => 4110, 'name' => 'Bidayuh', 'is_collective' => 1, 'child' => [
          ['code' => 411001, 'name' => 'Bau / Jagoi (Jagoi, Singgai dan Baratak)'],
          ['code' => 411002, 'name' => 'Biatah'],
          ['code' => 411003, 'name' => 'Bukar/ Sadong'],
          ['code' => 411004, 'name' => 'Lara'],
          ['code' => 411005, 'name' => 'Selako'],
      ]],
      ['code' => 4120, 'name' => 'Bisayah (Sarawak)'],
      ['code' => 4130, 'name' => 'Bukitan'],
      ['code' => 4070, 'name' => "Dali'"],
      ['code' => 4080, 'name' => 'Javanese or Jawa (Sarawak)'],
      ['code' => 4140, 'name' => 'Iban', 'is_collective' => 1, 'child' => [
          ['code' => 414001, 'name' => 'Memaloh'],
          ['code' => 414002, 'name' => 'Remun'],
          ['code' => 414003, 'name' => 'Sebuyau'],
          ['code' => 414004, 'name' => 'Seru'],
      ]],
      ['code' => 4150, 'name' => 'Kadayan (Sarawak)'],
      ['code' => 4160, 'name' => 'Kajang', 'is_collective' => 1, 'child' => [
          ['code' => 416001, 'name' => 'Kejaman'],
          ['code' => 416002, 'name' => 'Lahanan'],
          ['code' => 416003, 'name' => 'Punan'],
          ['code' => 416004, 'name' => 'Sekapan'],
      ]],
      ['code' => 4170, 'name' => 'Kanowit'],
      ['code' => 4180, 'name' => 'Kayan', 'is_collective' => 1, 'child' => [
          ['code' => 418001, 'name' => 'Balui Liko'],
          ['code' => 418002, 'name' => 'Balui Ukap'],
          ['code' => 418003, 'name' => 'Uma Aging'],
          ['code' => 418004, 'name' => 'Uma Apan'],
          ['code' => 418005, 'name' => 'Uma Awai'],
          ['code' => 418006, 'name' => 'Uma Bawang'],
          ['code' => 418007, 'name' => 'Uma Belur / Belun'],
          ['code' => 418008, 'name' => 'Uma Beluvuh'],
          ['code' => 418009, 'name' => 'Uma Daro'],
          ['code' => 418010, 'name' => 'Uma Juman'],
          ['code' => 418011, 'name' => 'Uma Kahei'],
          ['code' => 418012, 'name' => 'Uma Lesong'],
          ['code' => 418013, 'name' => 'Uma Nyaving'],
          ['code' => 418014, 'name' => "Uma Pako'"],
          ['code' => 418015, 'name' => 'Uma Peliau'],
          ['code' => 418016, 'name' => 'Uma Pu'],
          ['code' => 418017, 'name' => 'Uma San'],
          ['code' => 418018, 'name' => 'Uma Semuka'],
          ['code' => 418019, 'name' => "Uma Tapo'"],
          ['code' => 418020, 'name' => "Uma Tevo'"],
      ]],
      ['code' => 4200, 'name' => 'Kalabit'],
      ['code' => 4210, 'name' => 'Kenyah', 'is_collective' => 1, 'child' => [
          ['code' => 421001, 'name' => 'Badeng'],
          ['code' => 421002, 'name' => 'Jamok'],
          ['code' => 421003, 'name' => "Lepo' Long Wat"],
          ['code' => 421004, 'name' => "Lepo' Sawa'"],
          ['code' => 421005, 'name' => "Lepo' Abong"],
          ['code' => 421006, 'name' => "Lepo' Aga'"],
          ['code' => 421007, 'name' => "Lepo' Anan"],
          ['code' => 421008, 'name' => "Lepo' Bakong"],
          ['code' => 421009, 'name' => "Lepo' Dikan"],
          ['code' => 421010, 'name' => "Lepo' Ga'"],
          ['code' => 421011, 'name' => "Lepo' Jalan"],
          ['code' => 421012, 'name' => "Lepo' Jengan"],
          ['code' => 421013, 'name' => "Lepo' Key or Kay"],
          ['code' => 421014, 'name' => "Lepo'La'ang"],
          ['code' => 421015, 'name' => "Lepo' Long Akah"],
          ['code' => 421016, 'name' => "Lepo' Tau"],
          ['code' => 421017, 'name' => 'Lirong'],
          ['code' => 421018, 'name' => 'Ngorik (Murek)'],
          ['code' => 421019, 'name' => 'Sebop'],
          ['code' => 421020, 'name' => 'Seping'],
          ['code' => 421021, 'name' => "Uma' Akeh"],
          ['code' => 421022, 'name' => "Uma' Baha / Bakah"],
          ['code' => 421023, 'name' => "Uma' Bangan"],
          ['code' => 421024, 'name' => "Uma' Embo'"],
          ['code' => 421025, 'name' => "Uma' Kelap"],
          ['code' => 421026, 'name' => "Uma' Kulit"],
          ['code' => 421027, 'name' => "Uma' Meleng"],
          ['code' => 421028, 'name' => "Uma' Pawa'"],
          ['code' => 421029, 'name' => "Uma' Sambop"],
          ['code' => 421030, 'name' => "Uma' Tapu'an"],
      ]],
      ['code' => 4290, 'name' => 'Kiput or Lakiput'],
      ['code' => 4230, 'name' => 'Lisum'],
      ['code' => 4240, 'name' => 'Lugat'],
      ['code' => 4250, 'name' => 'Lun Bawang/ Murut (Sarawak)'],
      ['code' => 4260, 'name' => 'Melanau'],
      ['code' => 4211, 'name' => 'Miriek (Miri)'],
      ['code' => 4220, 'name' => 'Narom'],
      ['code' => 4270, 'name' => 'Penan'],
      ['code' => 4241, 'name' => "Sa'ban / Saben"],
      ['code' => 4290, 'name' => 'Sabup'],
      ['code' => 4261, 'name' => 'Segan (Baie)'],
      ['code' => 4310, 'name' => 'Sian'],
      ['code' => 4280, 'name' => 'Sihan'],
      ['code' => 4320, 'name' => 'Sipeng'],
      ['code' => 4330, 'name' => 'Tabun'],
      ['code' => 4340, 'name' => 'Tagal'],
      ['code' => 4350, 'name' => 'Tanjong'],
      ['code' => 4331, 'name' => 'Tetau or Tatau'],
      ['code' => 4341, 'name' => 'Tring'],
      ['code' => 4360, 'name' => 'Ukit'],
      ['code' => 4998, 'name' => 'Bumiputera Sarawak Lain'],
  ]],

  ['code' => 5000, 'name' => 'Cina', 'is_bumiputera' => 0, 'is_collective' => 1, 'child' => [
      ['code' => 5110, 'name' => 'Foochow', 'is_bumiputera' => 0],
      ['code' => 5120, 'name' => 'Hainan', 'is_bumiputera' => 0],
      ['code' => 5130, 'name' => 'Henghua', 'is_bumiputera' => 0],
      ['code' => 5140, 'name' => 'Hokchia', 'is_bumiputera' => 0],
      ['code' => 5150, 'name' => 'Hokchiu', 'is_bumiputera' => 0],
      ['code' => 5160, 'name' => 'Hokkien', 'is_bumiputera' => 0],
      ['code' => 5170, 'name' => 'Kantonis', 'is_bumiputera' => 0],
      ['code' => 5180, 'name' => 'Khek (Hakka)', 'is_bumiputera' => 0],
      ['code' => 5190, 'name' => 'Kwongsai', 'is_bumiputera' => 0],
      ['code' => 5200, 'name' => 'Teochew', 'is_bumiputera' => 0],
      ['code' => 5998, 'name' => 'Orang Cina Lain', 'is_bumiputera' => 0],
  ]],

  ['code' => 6000, 'name' => 'India', 'is_bumiputera' => 0, 'is_collective' => 1, 'child' => [
      ['code' => 6110, 'name' => 'India Muslim / Malabari', 'is_bumiputera' => 0],
      ['code' => 6120, 'name' => 'Malayali', 'is_bumiputera' => 0],
      ['code' => 6130, 'name' => 'Punjabi (kecuali Sikh)', 'is_bumiputera' => 0],
      ['code' => 6140, 'name' => 'Sikh', 'is_bumiputera' => 0],
      ['code' => 6150, 'name' => 'Sinhala', 'is_bumiputera' => 0],
      ['code' => 6160, 'name' => 'Tamil', 'is_bumiputera' => 0],
      ['code' => 6170, 'name' => 'Tamil Sri Lanka', 'is_bumiputera' => 0],
      ['code' => 6180, 'name' => 'Telugu', 'is_bumiputera' => 0],
      ['code' => 6998, 'name' => 'Orang India Lain', 'is_bumiputera' => 0],
  ]],

  ['code' => 7000, 'name' => 'Bangsa Asia', 'is_bumiputera' => 0, 'is_collective' => 1, 'child' => [
      ['code' => 7110, 'name' => 'Arab', 'is_bumiputera' => 0],
      ['code' => 7120, 'name' => 'Bangladesh', 'is_bumiputera' => 0],
      ['code' => 7130, 'name' => 'Indonesia', 'is_bumiputera' => 0],
      ['code' => 7140, 'name' => 'Jepun', 'is_bumiputera' => 0],
      ['code' => 7150, 'name' => 'Kampuchea', 'is_bumiputera' => 0],
      ['code' => 7160, 'name' => 'Keturunan Pulau Kokos', 'is_bumiputera' => 0],
      ['code' => 7170, 'name' => 'Korea', 'is_bumiputera' => 0],
      ['code' => 7180, 'name' => 'Myanmar', 'is_bumiputera' => 0],
      ['code' => 7180, 'name' => 'Nepal', 'is_bumiputera' => 0],
      ['code' => 7180, 'name' => 'Pakistan', 'is_bumiputera' => 0],
      ['code' => 7180, 'name' => 'Filipina', 'is_bumiputera' => 0],
      ['code' => 7180, 'name' => 'Thailand (Siam)', 'is_bumiputera' => 0],
      ['code' => 7180, 'name' => 'Viet Nam', 'is_bumiputera' => 0],
      ['code' => 7998, 'name' => 'Bangsa Asia Lain', 'is_bumiputera' => 0],
  ]],

  ['code' => 8000, 'name' => 'Bangsa Eropah', 'is_bumiputera' => 0, 'is_collective' => 1, 'child' => [
      ['code' => 8110, 'name' => 'Denmark', 'is_bumiputera' => 0],
      ['code' => 8120, 'name' => 'Perancis', 'is_bumiputera' => 0],
      ['code' => 8130, 'name' => 'Jerman', 'is_bumiputera' => 0],
      ['code' => 8140, 'name' => 'Itali', 'is_bumiputera' => 0],
      ['code' => 8150, 'name' => 'Sepanyol', 'is_bumiputera' => 0],
      ['code' => 8160, 'name' => 'United Kingdom', 'is_bumiputera' => 0],
      ['code' => 8998, 'name' => 'Bangsa Eropah Lain', 'is_bumiputera' => 0],
  ]],

  ['code' => 9000, 'name' => 'Bangsa Lain', 'is_bumiputera' => 0, 'is_collective' => 1, 'child' => [
      ['code' => 9110, 'name' => 'Afrika', 'is_bumiputera' => 0],
      ['code' => 9120, 'name' => 'Amerika Syarikat', 'is_bumiputera' => 0],
      ['code' => 9130, 'name' => 'Australia', 'is_bumiputera' => 0],
      ['code' => 9140, 'name' => 'New Zealand', 'is_bumiputera' => 0],
      ['code' => 9150, 'name' => 'Serani', 'is_bumiputera' => 0],
      ['code' => 9998, 'name' => 'Lain', 'is_bumiputera' => 0],
  ]],
];
