 <?php

/**
 * @author    syafiq <syafiq@my-sands.com>
 * @since     1.3
 * retrive date 12 Mac 2016
 */
$perlis = [
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Jawi Matang' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Desa Bintong' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Datuk Wan Ahmad' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Datuk Setia' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Datuk Jaafar Hassan' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Choo Kee' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Ceria' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Cergas' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Cahaya' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Bunga Raya' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Jawi Matang' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Desa Bintong' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Datuk Wan Ahmad' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Datuk Setia' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Datuk Jaafar Hassan' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Choo Kee' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Ceria' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Cergas' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Cahaya' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Bunga Raya' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Bunga Kemboja RPA' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Bumita' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Bukit Kayangan' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Bukit Kaya' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Bintong Utama' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Bintong Setia' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Bintong Maju' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Behor Indah' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Desa Jarak' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Desa Katong' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Jarak' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Jali' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Ira' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Intan' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Indera' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Idaman' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Hijrah' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Guru Jaya' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Guru' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Gembira' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Gasing' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Firdaus' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Fauziah' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Desa Sentua' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Desa Putra' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Desa Pulai' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Desa Kayangan' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Bakau Emas' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Aman' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Abu Bakar Munir' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Ujung Bukit' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tok Sumbing' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tok Pong' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tok Peduka' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tok Larak' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tok Kembong' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tok Kandang' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tok Jepun' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tok Jawa' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tok Gong' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tok Dewa' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Titi Tok Bandar' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Titi Teras' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tengah Abi' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Temak' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Telok Tui' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Telok Kacang' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Utan Aji' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Utan Temak' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Sena Rendang' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Repoh' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Perumahan Awam Santan' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Perumahan Awam Bohor Lateh' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Pengkalan Asam' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Padang Bohor' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Mengkuang Layar' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Lukuk Gajah' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Lorong Sekolah' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Lorong Nisam' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Lorong Kampung Sena' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Lorong Haji Seman' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kubang Arang' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kangar' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Wang Ulu' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Wang Besar' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Wang Belimbing' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Telok Jambu' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Ujung Batu' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Pilihan' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Murni' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Medan' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Manis' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Intan' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Idaman' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Embun' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Bahagia' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Sepadu 1' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Sepadu' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Sentua' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Sena Permai' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Sena Indah' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Sena' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Repoh Jaya' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Repoh Indah' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Repoh' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Puchong' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Pulai 4' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Tok Peduka' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Titi Midin' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Titi Chai'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Wira' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Utara' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Utama Indah' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Utama' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Tok Peduka' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Teratai' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Ten' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Syed Alwi' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Suriani' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Sri Guar Syed Alwi' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Simpang Tiga' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Setia Utama' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Seriab' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Tanjung' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Rasa Sayang' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Putra Putri' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Putera' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Mas Putra' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Mas Muda' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Mada Sepakat' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Lima Naleh' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Lewata' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Koperasi' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Kenanga' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Kemajuan' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Kecor Indah' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Kechor Jaya' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Kechor Indah' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Kayangan Indah' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Kastam' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Kangar' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Jelati' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Jejawi' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Jaya Diri' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Mas Ria' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Medan Sepakat' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Pertiwi Seriab' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Pertiwi Indah' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Pertama' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Permai' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Perlis' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Pengkalan Indah' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Pengkalan Assam' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Pekeliling' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Peduka' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Norma' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Mutiara' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Murni' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Muda Sepakat' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Mewah' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Mesra Jejawi' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Mesra' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Merpati' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Taman Jaya' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bukit Kecil' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Behor Cicar' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Batu Pahat' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Batu 3.5 (Jalan Kaki Bukit)' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Baru Santan' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Baru' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Baroh' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bakong (Jejawi)' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bakau' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Aur' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Asam 6' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Aman' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Alor Sena' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Alor Redeh' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Alor Pulai' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Alor Marus' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Alor Lanchang' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Alor Kabong' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Behor Empiang' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Behor Inai' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bukit Besi Hangit' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bohor Temak' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bohor Inai' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bohor Goncar' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bohor Gelam' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bohor Gandil' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bohor Chichar' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bintong' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Binjal' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bendang Baru' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Belukar (Kangar)' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Belat Santan' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Belangga Pudak' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Behor Temak' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Behor Pulai' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Behor Kebal' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Behor Janggus' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Alor Dalam' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Alor Ara' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Alor' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Medan Kangar' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Masjid Lama' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Kurung Batang' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Kangar' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Kampung Wan Abdullah' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Kaki Bukit (Batu 4 1/2)' ],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Jubli Perak'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Hospital'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Home Guard'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Bukit Meranti'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Bohor Guncar'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Besar Kangar'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Arau'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Alor Sena'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Abi Tok Hashim'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Bohor Gelam'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Alor Tok Terang'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Padang Bohor'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Panglima'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Abi Tok Hashim'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Abi Pokok Asam'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Abi Padang Machang'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Abi Batas Paip'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jejawi'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Tun Razak'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Tok Kandang'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Teluk Kacang'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Taman Bunga Padi'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Syed Omar'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Seruling'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Santan (Km 5)'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Raja Syed Saffi'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Raja Syed Alwi'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Raja Muda'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Penjara'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Jalan Pegawai'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Alor Redeh'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Telok Gelam'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Sempering'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Santan Masjid'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Santan Enam'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Santan Belat'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Santan Aur'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Santan'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Salang'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Repoh Dagang'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Repoh'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Pulau'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Pondok'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Pokok Jawi'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Petai Hilir'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Petai'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Peseri'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Pengkalan Asam'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Penghulu Bakar'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Sena'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Sena Sematang'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Telok Epa'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Telaga Nyiur Manis'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Telaga Idi'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tebing Tinggi'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tanjung Sila'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tanjung Gorah'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tanjung Buluh'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tanjung'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Syed Umar'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Surau'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Sungai Siran'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Sungai Santan'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Sungai Baru'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Sungai Bakong'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Seriab'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Sentua'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Sentang'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Parit Jari'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Panggau'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bunga Pudak'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Kota Keran'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Kota'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Keranji'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Kechor'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Jejawi Sematang'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Jejawi Dalam'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Jarak'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Hutan Melintang'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Hutan Buluh'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Haji Daud'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Guru'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Gunong'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Guar Ujung Batu'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Guar Syed Alwi'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Datuk'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Dasri'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Dagang'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Kota Ulu'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Kubang Arang'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Padang Jawa Seriab'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Padang Katong'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Padang Kedepiang'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Padang Machang'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Padang Nyaring'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Padang Pauh'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Padang Petani'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Padang Seberang'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Padang Behor'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Nyak Adam'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Kubang Badak'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Kubang Cekuang'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Kubang Gajah'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Kurung Batang'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Lin'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Masjid (Kangar)'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Mengkuang Layar'],
    [ 'state_id' => 9, 'code' => '01000', 'name' => 'Kampung Nissam'],
    [ 'state_id' => 9, 'code' => '01007', 'name' => 'Kangar - Peti surat'],
    [ 'state_id' => 9, 'code' => '01009', 'name' => 'Kangar - Beg berkunci'],
    [ 'state_id' => 9, 'code' => '01500', 'name' => 'DYMM Tuanku Raja Perlis'],
    [ 'state_id' => 9, 'code' => '01502', 'name' => 'YAB Menteri Besar Perlis'],
    [ 'state_id' => 9, 'code' => '01503', 'name' => 'Setiausaha Kerajaan Negeri'],
    [ 'state_id' => 9, 'code' => '01504', 'name' => 'Biro Bantuan Guaman'],
    [ 'state_id' => 9, 'code' => '01505', 'name' => 'Biro Pengaduan Awam'],
    [ 'state_id' => 9, 'code' => '01506', 'name' => 'Mahkamah Tinggi'],
    [ 'state_id' => 9, 'code' => '01506', 'name' => 'Mahkamah Sesyen'],
    [ 'state_id' => 9, 'code' => '01508', 'name' => 'Amanah Raya Berhad'],
    [ 'state_id' => 9, 'code' => '01512', 'name' => 'Penasihat Undang-Undang Negeri'],
    [ 'state_id' => 9, 'code' => '01514', 'name' => 'Jabatan Perangkaan'],
    [ 'state_id' => 9, 'code' => '01516', 'name' => 'Jabatan Pemegang Harta'],
    [ 'state_id' => 9, 'code' => '01517', 'name' => 'Jabatan Perpaduan Negara'],
    [ 'state_id' => 9, 'code' => '01518', 'name' => 'Jabatan Audit Negeri'],
    [ 'state_id' => 9, 'code' => '01524', 'name' => 'Setiausaha Keselamatan Negeri'],
    [ 'state_id' => 9, 'code' => '01529', 'name' => 'Unit Penyelidikan Sosio Ekonomi'],
    [ 'state_id' => 9, 'code' => '01532', 'name' => 'Jabatan Sumber Manusia'],
    [ 'state_id' => 9, 'code' => '01538', 'name' => 'Jabatan Keselamatan Sosial (Perkeso)'],
    [ 'state_id' => 9, 'code' => '01540', 'name' => 'Jabatan Tenaga Rakyat'],
    [ 'state_id' => 9, 'code' => '01546', 'name' => 'Unit Pencegah Penyeludupan'],
    [ 'state_id' => 9, 'code' => '01546', 'name' => 'Pejabat Rela Negeri'],
    [ 'state_id' => 9, 'code' => '01550', 'name' => 'Jabatan Imigresen'],
    [ 'state_id' => 9, 'code' => '01551', 'name' => 'Jabatan Pendaftaran Negara'],
    [ 'state_id' => 9, 'code' => '01556', 'name' => 'Jabatan Pertahanan Awam'],
    [ 'state_id' => 9, 'code' => '01560', 'name' => 'Ketua Polis Negeri'],
    [ 'state_id' => 9, 'code' => '01564', 'name' => 'Jabatan Kebajikan Masyarakat'],
    [ 'state_id' => 9, 'code' => '01570', 'name' => 'Jabatan Belia Dan Sukan'],
    [ 'state_id' => 9, 'code' => '01572', 'name' => 'Perpustakaan Awam Negeri'],
    [ 'state_id' => 9, 'code' => '01576', 'name' => 'Jabatan Tanah Dan Galian'],
    [ 'state_id' => 9, 'code' => '01578', 'name' => 'Jabatan Ukur & Pemetaan'],
    [ 'state_id' => 9, 'code' => '01582', 'name' => 'Jabatan Kerja Raya'],
    [ 'state_id' => 9, 'code' => '01586', 'name' => 'Hospital Kangar'],
    [ 'state_id' => 9, 'code' => '01590', 'name' => 'Jabatan Kesihatan'],
    [ 'state_id' => 9, 'code' => '01592', 'name' => 'Pegawai Kewangan Negeri'],
    [ 'state_id' => 9, 'code' => '01594', 'name' => 'Akauntan Negeri'],
    [ 'state_id' => 9, 'code' => '01596', 'name' => 'Jabatan Kastam & Eksais Di Raja'],
    [ 'state_id' => 9, 'code' => '01598', 'name' => 'Kumpulan Wang Simpanan Pekerja'],
    [ 'state_id' => 9, 'code' => '01600', 'name' => 'Lembaga Hasil Dalam Negeri'],
    [ 'state_id' => 9, 'code' => '01604', 'name' => 'Jabatan Pendidikan'],
    [ 'state_id' => 9, 'code' => '01606', 'name' => 'Jabatan Kemajuan Masyarakat (Kemas)'],
    [ 'state_id' => 9, 'code' => '01608', 'name' => 'Jabatan Pembangunan Koperasi'],
    [ 'state_id' => 9, 'code' => '01609', 'name' => 'Pejabat Mara Negeri'],
    [ 'state_id' => 9, 'code' => '01610', 'name' => 'Bahagian Perlesenan - Kementerian Penerangan'],
    [ 'state_id' => 9, 'code' => '01612', 'name' => 'Jabatan Penerangan'],
    [ 'state_id' => 9, 'code' => '01614', 'name' => 'Jabatan Penyiaran'],
    [ 'state_id' => 9, 'code' => '01620', 'name' => 'Jabatan Pengangkutan Jalan'],
    [ 'state_id' => 9, 'code' => '01622', 'name' => 'Unit Penguatkuasa Kem. Perdagangan & Perindustrian'],
    [ 'state_id' => 9, 'code' => '01626', 'name' => 'Jabatan Pengairan Dan Saliran'],
    [ 'state_id' => 9, 'code' => '01628', 'name' => 'Jabatan Perikanan'],
    [ 'state_id' => 9, 'code' => '01630', 'name' => 'Jabatan Haiwan'],
    [ 'state_id' => 9, 'code' => '01632', 'name' => 'Jabatan Pertanian'],
    [ 'state_id' => 9, 'code' => '01634', 'name' => 'Panglima Markas 12 Briged'],
    [ 'state_id' => 9, 'code' => '01644', 'name' => 'Majlis Perbandaran Kangar'],
    [ 'state_id' => 9, 'code' => '01646', 'name' => 'Jabatan Perancang Bandar Dan Desa'],
    [ 'state_id' => 9, 'code' => '01648', 'name' => 'Jabatan Bomba & Penyelamat'],
    [ 'state_id' => 9, 'code' => '01660', 'name' => 'Jabatan Perhutanan'],
    [ 'state_id' => 9, 'code' => '01664', 'name' => 'Jabatan Perhilitan'],
    [ 'state_id' => 9, 'code' => '01670', 'name' => 'Pos Malaysia Berhad'],
    [ 'state_id' => 9, 'code' => '01672', 'name' => 'Telekom Malaysia Berhad'],
    [ 'state_id' => 9, 'code' => '01673', 'name' => 'Tenaga Nasional Berhad'],
    [ 'state_id' => 9, 'code' => '01674', 'name' => 'Pegawai Kemajuan Negeri'],
    [ 'state_id' => 9, 'code' => '01676', 'name' => 'Jabatan Agama Islam Perlis'],
    [ 'state_id' => 9, 'code' => '01680', 'name' => 'Dewan Undangan Negeri'],
    [ 'state_id' => 9, 'code' => '01694', 'name' => 'Jabatan Kebudayaan & Kesenian'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Tanjung Gelam'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Telok'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Tengah'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Tengah Bohor Lateh'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Terus Teritip'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Titi Serong'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Tok Kaya'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Tok Kuning'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Tandiap'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Sungai Mati'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Seberang Tok PI'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Peladang'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Perak'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Pokok Asam'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Puju'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Pulau'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Pulau Ketam'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Seberang Alor'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Seberang Jaya'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Utan Ibus'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Wai'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Taman Bukit Kubu'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Taman Indera Indah'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Taman Kuala Perlis'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Taman Peladang Jaya'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Taman Semarak'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Taman Sentosa'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Taman Seri Bayu'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Taman Seri Semarak'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Taman Berlian'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Sungai Siput'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Wang Pinang'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kawasan Perindustrian Kuala Perlis'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kuala Perlis'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Persiaran Putra Timur 1'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'PPRT Tok Kuning'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Rancangan Perumahan Awam 2 KPS'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Sungai Berembang'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Sungai Manor'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Taman Suria'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Pak Lengah'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Al Marhom Kayang'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Jalan Siakap'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Jalan Simpang Empat (Batu 3 3\/4 - 4 1\/2)'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Bahagia'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Bangsal Lebah'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Baru (Jalan Sarawak)'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Baru Jeti'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Baru Tandiap'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Baru Tok Kuning'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Jalan Serawak'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Jalan Panggong'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Bohor Lateh'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Bohor Mali'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Bukit Puteh'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Bukit Tok Po'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Jalan Besar'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Jalan Lama Kuala Perlis (Batu 4)'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Jalan Masjid'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Jalan Miri'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Batu Buaya'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Batu Lima'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Kota Kayang'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Kuala'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Kurung Tengar'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Langgar'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Nelayan'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Padang Besar Selatan'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Padang Cina'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Padang Jamil'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Kolam Raja'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Hujung Tanjung'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Bukit Papan'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Behor Lateh'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Belakang Kilang'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Besar'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Bohor Ibus'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Bohor Lateh'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Bohor Mesjid'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Bohor Rotan Pahit'],
    [ 'state_id' => 9, 'code' => '02000', 'name' => 'Kampung Bohor Tui'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Tok Wan Nik'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Titi Tinggi Ulu'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Titi Tinggi Hilir'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Titi Tinggi'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Tersusun (Batu 20)'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Syed Abdan'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Sungai Chuchuh'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Sena'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Sahabat'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kem Askar Rimba Mab'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Padang Besar'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Pusat Serenti Bukit Cabang'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Taman Singgah Sana'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Taman Perumahan Awam'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Taman Kim 2'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Taman Kim'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Taman Kastam Baru'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Taman Bunga Cina'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Taman Bunga Cempaka'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Sekolah Menengah Padang Besar'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Taman Utara Jaya (Fasa 1 - 3)'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Petani'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Bukit Cabang'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Alor Dalam (Bukit Chabang)'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Jalan Padang Besar (Km 19)'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Gapura Squre'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Gapura Square'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Felda Rimba Mas'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Felda Mata Ayer'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Felcra Lubuk Sireh'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Emas Kerajang'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Asmara'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Baru'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Baru Bukit Chabang'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Padang Mawa'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Melayu'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Masjid'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Kolam'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Kok Mak'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Guar Tinggi (Titi Tinggi)'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Chantek'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Bukit Chabang'],
    [ 'state_id' => 9, 'code' => '02100', 'name' => 'Kampung Baru Jalan Sahabat'],
    [ 'state_id' => 9, 'code' => '02200', 'name' => 'Taman Singgahsana'],
    [ 'state_id' => 9, 'code' => '02200', 'name' => 'Kampung Wang Kelian'],
    [ 'state_id' => 9, 'code' => '02200', 'name' => 'Kampung Tassoh'],
    [ 'state_id' => 9, 'code' => '02200', 'name' => 'Kaki Bukit'],
    [ 'state_id' => 9, 'code' => '02200', 'name' => 'Jalan Padang Besar (Batu 16)'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Sungai Buloh'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Sungai Jerneh'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Sungai Paya'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Sungai Serai'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Tanjong'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Titi Tampang'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Tunjong Beseri'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Wang Pisang'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Wang Tangga'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Wang Tengku Lembu'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kilang Gula'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Lembaga Pertubuhan Peladang'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Lembaga Tembakau Negara'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Lubuk Besar'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Sungai Baru Serai'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Songla'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Simpang 3 Panggas'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Padang Lati'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Padang Malau'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Padang Melangit'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Paya'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Paya Kelubi'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Paya Senduk'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Paya Ulu'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Penghulu Jaafar'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Perawah'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Raja Conggah'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Semadong'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Sena Rendang'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Simpang 3 Kilang Gula'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Padang Jelutong'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Maktab Rendah Sains Mara'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Taman Beseri Indah'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Taman Beseri Jaya'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Taman Beseri Murni'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Taman Beseri Paya'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Taman Bunga Geti'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Taman Che Long'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Taman Dua Puluh'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Taman Geti'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Taman Has Melati'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Taman Haz Melati'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Taman Mas (Beseri)'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Taman Melati Indah (Beseri)'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Taman Permai'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Taman Bahagia'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Taman Angsana'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Sekolah Menengah semadung'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Padang lati'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Paya Batu 5'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Paya Besar'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Paya Pauh Gembol'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Paya Pauh Gembol'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Paya Senduk'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Paya Tengah'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Perumahan Kilang Gula'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Perumahan Perlis Plantation'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Pusat Haiwan Bukit Temiang'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'RPA Batu 8'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'RPA Bukit Keteri'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'RPA Chuping'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Taman Sempurna Jaya'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Beseri'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Alor Kangar'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Alor Tampang'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Balai Baru'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Baru Ngulang'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Baru Pangas'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Batu Bertangkup'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Batu Hampar (Beseri)'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Behor Kulit Kerang'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Behor Madi'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Belat Batu Beseri'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Belukar Lengga'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Beseri Dalam'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Beseri Jaya'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung  Semadung'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'JKR Bekalan Air Tassoh'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'JKR (bekalan air timah tasoh)'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Beseri Dalam'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Bilal Uduh'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Bohor Madi'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Bukit Keteri'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Empangan Timah Tassoh JPS'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Guar Panji'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Institut Kemahiran Mara'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Jabatan Pertanian Bukit Temiang'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Jalan Asam Paya'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Jalan Beseri - Bukit Keteri'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Jalan Kaki Bukit (Batu 4 3\/4 - 6 1\/4)'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Jalan padang melangit'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Jalan Santan (Batu 3 3\/4 - 5)'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bilal Uduh'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bohor Luar'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Kelang Beseri'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Kepala Batas Dato Kayaman'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Kubang Jeliti'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Kubang Tiga'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Kubang Tiga'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Lembah Biak'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Lubok Batu'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Lubok Gajah'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Lubok Hitam Manis'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Lubuk Machang'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Masjid Beseri'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Mempelas'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Ngulang'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Padang Gelam'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Guar Sanai'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Guar Medan Gatal'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bongkok'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bukit Jernih'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bukit Kedak'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bukit Manek Barat'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bukit Merah'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bukit Merah Hilir'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bukit Merah Hulu'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bukit Merah Hulu'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Guar Jentek'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Datuk Sheikh Ahmad'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Darat Selatan'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Darat'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Chichak Terbelit'],
    [ 'state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bukit Temiang'],
    [ 'state_id' => 9, 'code' => '02450', 'name' => 'Kampung Padang Jelutong'],
    [ 'state_id' => 9, 'code' => '02450', 'name' => 'Kampung Paya Kelubi'],
    [ 'state_id' => 9, 'code' => '02450', 'name' => 'Kampung Perawah'],
    [ 'state_id' => 9, 'code' => '02450', 'name' => 'Kampung Songla'],
    [ 'state_id' => 9, 'code' => '02450', 'name' => 'Kampung Sungai Buloh'],
    [ 'state_id' => 9, 'code' => '02450', 'name' => 'Taman Tunjung'],
    [ 'state_id' => 9, 'code' => '02450', 'name' => 'Kampung Padang Gelam'],
    [ 'state_id' => 9, 'code' => '02450', 'name' => 'Kampung Masjid (Beseri)'],
    [ 'state_id' => 9, 'code' => '02450', 'name' => 'Bukit Keteri'],
    [ 'state_id' => 9, 'code' => '02450', 'name' => 'Guar Panji'],
    [ 'state_id' => 9, 'code' => '02450', 'name' => 'Kampung Belukar Lengga'],
    [ 'state_id' => 9, 'code' => '02450', 'name' => 'Kampung Bukit Jernih'],
    [ 'state_id' => 9, 'code' => '02450', 'name' => 'Kampung Kepala Batas Dato Kaya'],
    [ 'state_id' => 9, 'code' => '02450', 'name' => 'Kampung Kubang Tiga'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Simpang Geti'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Saikla'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Pokok Sena'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Pokok Petai'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Perik'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Paya Burma'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Panggas Kechil'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Panggas Besar'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Panggas'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Padang Nyu'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Oran'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Sungai Mati'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kok Klang'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Lubuk Besar'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Taman Sri Idaman'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Taman Selasih'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Taman Ria'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Taman Permata'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Taman Padang Nyu'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Taman Mata Air (2 - 3)'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Taman Haji Ali (RPA)'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Stesen Meteorilogi'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Sekolah Jenis Kebangsaan Cina Kong Aik'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Pekan Gate Mata Air'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Mata Ayer'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Kubang Peron'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Kersek (Mata Ayer)'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Bukit Chuping'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Changkat Lada'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Bukit Chuping'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Belukar (Mata Ayer)'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Bawah Bukit'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Banggol Sena'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Balik Guar'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Balik Bukit Selatan'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Balik Bukit'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Jalan Mata Ayer (Km 1.6 - 6)'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Hutan Lembah'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Felda Chuping'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Che gu Ali'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Chelong'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Kersek (Kangar)'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Kerisik Hilir'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Hutan Temin'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Hutan Lembah'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Hutan Lembah'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Guar Nangka'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Guar Nangka'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Chuping'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Gial'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Gial Tengah'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Guar Halban'],
    [ 'state_id' => 9, 'code' => '02500', 'name' => 'Kampung Guar Musang'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Telaga Haji Latif'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Tambun Tulang'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Stesen'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Sena'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Pulau Pichai'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Pida 3 Lama'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Pauh'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Paloh'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Padang Telela'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Telok'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Titi Besi'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Ulu Pauh'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'UiTM Arau'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Taman Utara Guar Sanji'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Taman Sri Pauh'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Taman Seri Wangi'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Taman Seri Idaman'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Taman Pauh Indah'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Taman Desa Pauh'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Rani Estate'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Pauh'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Padang Siding'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Padang Biak'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Arau'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Bohor Mengkung'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Belukar'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Belat Raja'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Belat Batu'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Batas Liku'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Banat'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Bakong (Arau)'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Alor Merah'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Guar Sanji'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Bohor Mentalun'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Changkat Jawi'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Kubang Siput'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Kubang Mat Tanggok'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Kuala Tunggang'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Katong'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Jelempok'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Hutan Kandis'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Guring'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Guar Gajah'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Chermai'],
    [ 'state_id' => 9, 'code' => '02600', 'name' => 'Kampung Changkat Kabu'],
    [ 'state_id' => 9, 'code' => '02607', 'name' => 'Arau - Peti surat'],
    [ 'state_id' => 9, 'code' => '02609', 'name' => 'Arau - Beg berkunci'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Serdang'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Sematang Serdang'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Pulau'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Permatang Pauh'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Permatang Limau Manis'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Permatang Bongor'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Pauh Tiga Beradek'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Sungai Baru'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Sungai Belati'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Sungai Bugis'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Sungai Padang'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Tebuk'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Titi Beratap'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Tok Pulau'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Simpang Ampat'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Taman Cendera Wasih'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Taman Pelangi'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Padang Petani'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Padang Benta'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Mua'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Bohor Mali'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Banir Tembus'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Batas Lentang'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Bendang Baru'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Berjaya'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Bohor Lalang'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Bonggor Kudong'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Bunga Mas'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Chantek Bangun'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Che Ok'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Chemumar'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Jawi Endol'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Kenangan'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Lat Seribu'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Long Boh'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Matang Kersek'],
    [ 'state_id' => 9, 'code' => '02700', 'name' => 'Kampung Melintang'],
    [ 'state_id' => 9, 'code' => '02707', 'name' => 'Simpang Ampat - Peti surat'],
    [ 'state_id' => 9, 'code' => '02709', 'name' => 'Simpang Ampat - Beg berkunci'],
    [ 'state_id' => 9, 'code' => '02800', 'name' => 'Kampung Kepala Batas Pauh'],
    [ 'state_id' => 9, 'code' => '02800', 'name' => 'Kampung Kerbau Belaga'],
    [ 'state_id' => 9, 'code' => '02800', 'name' => 'Kampung Matang Keriang'],
    [ 'state_id' => 9, 'code' => '02800', 'name' => 'Kampung Padang Gelam'],
    [ 'state_id' => 9, 'code' => '02800', 'name' => 'Kampung Padang Keria'],
    [ 'state_id' => 9, 'code' => '02800', 'name' => 'Kampung Permatang Pelangu'],
    [ 'state_id' => 9, 'code' => '02800', 'name' => 'Kampung Rama'],
    [ 'state_id' => 9, 'code' => '02800', 'name' => 'Kampung Simpang Sanglang'],
    [ 'state_id' => 9, 'code' => '02800', 'name' => 'Kampung Tanah Timbul']
];
