<?php

/**
 * @author    syafiq <syafiq@my-sands.com>
 * @since     1.3
 * retrive date 12 Mac 2016
 */
$wpPutrajaya = [
	[ 'state_id' => 16, 'code' => '62000', 'name' => 'Putrajaya - (Presint 1)' ],
	[ 'state_id' => 16, 'code' => '62007', 'name' => 'Badan Pencegah Rasuah' ],
	[ 'state_id' => 16, 'code' => '62050', 'name' => 'Bahagian Pilihanraya Parlimen P125 Putrajaya' ],
	[ 'state_id' => 16, 'code' => '62050', 'name' => 'Putrajaya - (Presint 12, 14 & 15)' ],
	[ 'state_id' => 16, 'code' => '62050', 'name' => 'Jalan P15H' ],
	[ 'state_id' => 16, 'code' => '62100', 'name' => 'Suruhanjaya Tenaga' ],
	[ 'state_id' => 16, 'code' => '62100', 'name' => 'Putrajaya - (Presint 2, 3, 4 & 18)' ],
	[ 'state_id' => 16, 'code' => '62100', 'name' => 'Persiaran Perdana (Presint 4)' ],
	[ 'state_id' => 16, 'code' => '62100', 'name' => 'Kementerian Wilayah Persekutuan' ],
	[ 'state_id' => 16, 'code' => '62100', 'name' => 'Jalan Tunku Abdul Rahman (Presint 3)' ],
	[ 'state_id' => 16, 'code' => '62100', 'name' => 'Jalan P18C 1/2' ],
	[ 'state_id' => 16, 'code' => '62100', 'name' => 'Jalan P16G (Presint 16)' ],
	[ 'state_id' => 16, 'code' => '62150', 'name' => 'Putrajaya - (Presint 16 & 17)' ],
	[ 'state_id' => 16, 'code' => '62200', 'name' => 'Former Prime Minister of Malaysia' ],
	[ 'state_id' => 16, 'code' => '62200', 'name' => 'Putrajaya - (Presint 5, 6, 19 & 20)' ],
	[ 'state_id' => 16, 'code' => '62250', 'name' => 'Putrajaya - (Presint 7, 8, 9 & 10)' ],
	[ 'state_id' => 16, 'code' => '62250', 'name' => 'Jalan P9C/1 Presint 9' ],
	[ 'state_id' => 16, 'code' => '62250', 'name' => 'Jalan P8E 2/5-2' ],
	[ 'state_id' => 16, 'code' => '62250', 'name' => 'Jalan P7E' ],
	[ 'state_id' => 16, 'code' => '62250', 'name' => 'Jalan P10/4' ],
	[ 'state_id' => 16, 'code' => '62300', 'name' => 'Bahagian Kerja Tanah Jabatan Perdana Menteri' ],
	[ 'state_id' => 16, 'code' => '62300', 'name' => 'Putrajaya - (Presint 11 & 13)' ],
	[ 'state_id' => 16, 'code' => '62300', 'name' => 'Presint 11' ],
	[ 'state_id' => 16, 'code' => '62502', 'name' => 'Pejabat Timbalan Perdana Menteri' ],
	[ 'state_id' => 16, 'code' => '62502', 'name' => 'Penasihat Agama Islam kepada Yang Amat Berhormat Perdana Menteri' ],
	[ 'state_id' => 16, 'code' => '62502', 'name' => 'Seketrial Permata Jabatan Perdana Menteri' ],
	[ 'state_id' => 16, 'code' => '62502', 'name' => 'Setiausaha Parlimen di Jabatan Perdana Menteri' ],
	[ 'state_id' => 16, 'code' => '62502', 'name' => 'Unit Pemodenan Tadbiran Malaysia' ],
	[ 'state_id' => 16, 'code' => '62502', 'name' => 'Unit Penyelarasan dan Perlaksanaan Jabatan Perdana Menteri' ],
	[ 'state_id' => 16, 'code' => '62502', 'name' => 'Unit Perancang Ekonomi Jabatan Perdana Menteri' ],
	[ 'state_id' => 16, 'code' => '62502', 'name' => 'Pejabat Timbalan Menteri di Jabatan Perdana Menteri' ],
	[ 'state_id' => 16, 'code' => '62502', 'name' => 'Pejabat Perdana Menteri' ],
	[ 'state_id' => 16, 'code' => '62502', 'name' => 'Pejabat Menteri di Jabatan Perdana Menteri' ],
	[ 'state_id' => 16, 'code' => '62502', 'name' => 'Bahagian Keselamatan Negara Jabatan Perdana Menteri' ],
	[ 'state_id' => 16, 'code' => '62502', 'name' => 'Bahagian Pengurusan Harta Tanah Jabatan Perdana Menteri' ],
	[ 'state_id' => 16, 'code' => '62502', 'name' => 'Bahagian Penyelidikan Jabatan Perdana Menteri' ],
	[ 'state_id' => 16, 'code' => '62502', 'name' => 'Biro Tatanegara' ],
	[ 'state_id' => 16, 'code' => '62502', 'name' => 'Jabatan Perdana Menteri' ],
	[ 'state_id' => 16, 'code' => '62502', 'name' => 'Ketua Setiausaha Sulit Kanan Jabatan Perdana Menteri' ],
	[ 'state_id' => 16, 'code' => '62502', 'name' => 'Ketua Unit Kawal Selia Felda' ],
	[ 'state_id' => 16, 'code' => '62502', 'name' => 'Lembaga Penasihat Jabatan Perdana Menteri' ],
	[ 'state_id' => 16, 'code' => '62502', 'name' => 'Koperasi Pekerja-Pekerja Jabatan Perdana Menteri Berhad' ],
	[ 'state_id' => 16, 'code' => '62503', 'name' => 'Ketua Setiausaha Negara' ],
	[ 'state_id' => 16, 'code' => '62504', 'name' => 'Biro Bantuan Guaman Malaysia' ],
	[ 'state_id' => 16, 'code' => '62505', 'name' => 'Biro Pengaduan Awam' ],
	[ 'state_id' => 16, 'code' => '62505', 'name' => 'Mahkamah Majistret Kajang' ],
	[ 'state_id' => 16, 'code' => '62506', 'name' => 'Pejabat Ketua Pendaftar Mahkamah Persekutuan' ],
	[ 'state_id' => 16, 'code' => '62506', 'name' => 'Mahkamah Rayuan Malaysia' ],
	[ 'state_id' => 16, 'code' => '62510', 'name' => 'Jabatan Perkhidmatan Awam' ],
	[ 'state_id' => 16, 'code' => '62512', 'name' => 'Jabatan Peguam Negara' ],
	[ 'state_id' => 16, 'code' => '62514', 'name' => 'Jabatan Perangkaan Malaysia' ],
	[ 'state_id' => 16, 'code' => '62514', 'name' => 'Jabatan Insolvensi Malaysia/Jabatan Pemegang Harta' ],
	[ 'state_id' => 16, 'code' => '62516', 'name' => 'Jabatan Perpaduan Negara dan Integrasi Nasional' ],
	[ 'state_id' => 16, 'code' => '62518', 'name' => 'Pejabat Ketua Audit Negara' ],
	[ 'state_id' => 16, 'code' => '62519', 'name' => 'Jabatan Wakaf Zakat dan Haji' ],
	[ 'state_id' => 16, 'code' => '62519', 'name' => 'Pejabat Menteri di Jabatan Perdana Menteri Hal Ehwal Agama' ],
	[ 'state_id' => 16, 'code' => '62519', 'name' => 'Suruhanjaya Perkhidmatan Awam Malaysia' ],
	[ 'state_id' => 16, 'code' => '62519', 'name' => 'Jabatan Kemajuan Islam Malaysia (JAKIM)' ],
	[ 'state_id' => 16, 'code' => '62520', 'name' => 'Pusat Pengajian Pembangunan Malaysia' ],
	[ 'state_id' => 16, 'code' => '62524', 'name' => 'Pejabat Ketua Pegawai Keselamatan Kerajaan' ],
	[ 'state_id' => 16, 'code' => '62526', 'name' => 'Suruhanjaya Perkhidmatan Pelajaran' ],
	[ 'state_id' => 16, 'code' => '62526', 'name' => 'Unit Pemodenan Tadbiran Perancangan & Pengurusan Malaysia(MAMPU)' ],
	[ 'state_id' => 16, 'code' => '62527', 'name' => 'Jabatan Pembangunan Kemahiran' ],
	[ 'state_id' => 16, 'code' => '62530', 'name' => 'Jabatan Hal Ehwal Kesatuan Sekerja' ],
	[ 'state_id' => 16, 'code' => '62530', 'name' => 'Kementerian Sumber Manusia' ],
	[ 'state_id' => 16, 'code' => '62532', 'name' => 'Majlis Latihan Vokasional Kebangsaan' ],
	[ 'state_id' => 16, 'code' => '62532', 'name' => 'Jabatan Tenaga Kerja' ],
	[ 'state_id' => 16, 'code' => '62532', 'name' => 'Jabatan Perhubungan Perusahaan' ],
	[ 'state_id' => 16, 'code' => '62536', 'name' => 'Jabatan Tenaga Manusia' ],
	[ 'state_id' => 16, 'code' => '62540', 'name' => 'Pendaftar Kesatuan Sekerja' ],
	[ 'state_id' => 16, 'code' => '62542', 'name' => 'Jabatan Pendaftaran Pertubuhan' ],
	[ 'state_id' => 16, 'code' => '62546', 'name' => 'Kementerian Hal Ehwal Dalam Negeri' ],
	[ 'state_id' => 16, 'code' => '62546', 'name' => 'Kementerian Keselamatan Dalam Negeri' ],
	[ 'state_id' => 16, 'code' => '62546', 'name' => 'Ketua Pengarah Agensi Anti Dadah Kebangsaan' ],
	[ 'state_id' => 16, 'code' => '62546', 'name' => 'Ketua Pengarah Jabatan RELA' ],
	[ 'state_id' => 16, 'code' => '62550', 'name' => 'Ketua Pengarah Pendaftaran Negara' ],
	[ 'state_id' => 16, 'code' => '62550', 'name' => 'Ketua Pengarah Jabatan Imigresen Malaysia' ],
	[ 'state_id' => 16, 'code' => '62551', 'name' => 'Jabatan Belia dan Sukan Negara' ],
	[ 'state_id' => 16, 'code' => '62570', 'name' => 'Kementerian Belia Dan Sukan' ],
	[ 'state_id' => 16, 'code' => '62574', 'name' => 'Kementerian Sumber Asli dan Alam Sekitar' ],
	[ 'state_id' => 16, 'code' => '62574', 'name' => 'Ketua Pengarah Jabatan Tanah dan Galian Persekutuan' ],
	[ 'state_id' => 16, 'code' => '62576', 'name' => 'Jabatan Ukur & Pemetaan' ],
	[ 'state_id' => 16, 'code' => '62582', 'name' => 'Jabatan Kawalan Penyakit Bawaan Vektor' ],
	[ 'state_id' => 16, 'code' => '62582', 'name' => 'Jabatan Kerja Raya Wilayah Persekutuan Putrajaya' ],
	[ 'state_id' => 16, 'code' => '62584', 'name' => 'Kementerian Kesihatan' ],
	[ 'state_id' => 16, 'code' => '62590', 'name' => 'Kementerian Kewangan' ],
	[ 'state_id' => 16, 'code' => '62592', 'name' => 'Jabatan Akauntan Negara' ],
	[ 'state_id' => 16, 'code' => '62592', 'name' => 'Ketua Pengarah Jabatan Penilaian dan Perkhidmatan Harta' ],
	[ 'state_id' => 16, 'code' => '62594', 'name' => 'Ibu Pejabat Jabatan Kastam DiRaja Malaysia' ],
	[ 'state_id' => 16, 'code' => '62596', 'name' => 'Jabatan Kerjasama Asean' ],
	[ 'state_id' => 16, 'code' => '62602', 'name' => 'Kementerian Luar Negeri' ],
	[ 'state_id' => 16, 'code' => '62602', 'name' => 'Bahagian Biasiswa Kementerian Pelajaran' ],
	[ 'state_id' => 16, 'code' => '62604', 'name' => 'Kementerian Pengajian Tinggi' ],
	[ 'state_id' => 16, 'code' => '62604', 'name' => 'Pusat Perkembangan Kurikulum' ],
	[ 'state_id' => 16, 'code' => '62604', 'name' => 'Lembaga Peperiksaan Malaysia' ],
	[ 'state_id' => 16, 'code' => '62604', 'name' => 'Bahagian Kewangan Kementerian Pelajaran' ],
	[ 'state_id' => 16, 'code' => '62604', 'name' => 'Kementerian Pelajaran' ],
	[ 'state_id' => 16, 'code' => '62604', 'name' => 'Jemaah Nazir' ],
	[ 'state_id' => 16, 'code' => '62604', 'name' => 'Bahagian Pendidikan Guru' ],
	[ 'state_id' => 16, 'code' => '62604', 'name' => 'Bahagian Sumber Manusia Kementerian Pelajaran' ],
	[ 'state_id' => 16, 'code' => '62604', 'name' => 'Jabatan Pendidikan Teknikal' ],
	[ 'state_id' => 16, 'code' => '62604', 'name' => 'Jabatan Pendidikan Tinggi' ],
	[ 'state_id' => 16, 'code' => '62604', 'name' => 'Jabatan Politeknik dan Kolej Komuniti' ],
	[ 'state_id' => 16, 'code' => '62605', 'name' => 'Jabatan Kemajuan Masayarakat' ],
	[ 'state_id' => 16, 'code' => '62606', 'name' => 'Kementerian Kemajuan Luar Bandar dan Wilayah' ],
	[ 'state_id' => 16, 'code' => '62616', 'name' => 'Kementerian Pengangkutan' ],
	[ 'state_id' => 16, 'code' => '62616', 'name' => 'Jabatan Penerbangan Awam' ],
	[ 'state_id' => 16, 'code' => '62620', 'name' => 'Kementerian Perdagangan Dalam Negeri dan Hal Ehwal Pengguna' ],
	[ 'state_id' => 16, 'code' => '62620', 'name' => 'Ketua Pengarah Jabatan Pengangkutan Jalan' ],
	[ 'state_id' => 16, 'code' => '62623', 'name' => 'Kementerian Pertanian dan Industri Asas Tani' ],
	[ 'state_id' => 16, 'code' => '62624', 'name' => 'Jabatan Perikanan' ],
	[ 'state_id' => 16, 'code' => '62628', 'name' => 'Jabatan Haiwan' ],
	[ 'state_id' => 16, 'code' => '62630', 'name' => 'Jabatan Pertanian' ],
	[ 'state_id' => 16, 'code' => '62632', 'name' => 'Ketua Pengarah Jabatan Bomba Malaysia' ],
	[ 'state_id' => 16, 'code' => '62648', 'name' => 'Kementerian Pembangunan Usahawan dan Koperasi' ],
	[ 'state_id' => 16, 'code' => '62652', 'name' => 'Kementerian Perusahaan Perladangan dan Komoditi' ],
	[ 'state_id' => 16, 'code' => '62652', 'name' => 'Yayasan Tekun Nasional' ],
	[ 'state_id' => 16, 'code' => '62654', 'name' => 'Jabatan Standard Malaysia' ],
	[ 'state_id' => 16, 'code' => '62662', 'name' => 'Kementerian Sains Teknologi dan Inovasi' ],
	[ 'state_id' => 16, 'code' => '62662', 'name' => 'Jabatan Bekalan Air' ],
	[ 'state_id' => 16, 'code' => '62662', 'name' => 'Jabatan Alam Sekitar' ],
	[ 'state_id' => 16, 'code' => '62668', 'name' => 'Kementerian Tenaga, Air dan Komunikasi' ],
	[ 'state_id' => 16, 'code' => '62668', 'name' => 'Pusat Mel Kerajaan Putrajaya' ],
	[ 'state_id' => 16, 'code' => '62674', 'name' => 'Bahagian Kemajuan Wilayah Persekutuan' ],
	[ 'state_id' => 16, 'code' => '62675', 'name' => 'Jabatan Agama Islam Wilayah Putrajaya' ],
	[ 'state_id' => 16, 'code' => '62675', 'name' => 'Perbadanan Putrajaya' ],
	[ 'state_id' => 16, 'code' => '62677', 'name' => 'Jabatan Kehakiman Syariah Malaysia' ],
	[ 'state_id' => 16, 'code' => '62677', 'name' => 'Suruhanjaya Kehakiman' ],
	[ 'state_id' => 16, 'code' => '62690', 'name' => 'Suruhanjaya Pilihan Raya Malaysia' ],
	[ 'state_id' => 16, 'code' => '62692', 'name' => 'Bahagian Hal Ehwal Undang-undang' ],
	[ 'state_id' => 16, 'code' => '62988', 'name' => 'Cyberjaya' ]
];