<?php

$data = [
    ['state_id' => '01', 'code' => '79000', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79050', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79100', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79150', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79200', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79250', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79502', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79503', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79504', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79505', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79511', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79513', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79514', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79517', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79518', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79520', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79521', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79523', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79532', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79538', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79540', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79546', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79548', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79550', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79552', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79555', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79570', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79575', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79576', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79592', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79601', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79603', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79605', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79606', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79612', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79626', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79630', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79632', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79646', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79658', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79660', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79680', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79681', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '79683', 'post_office_id' => 'Iskandar Puteri'],
    ['state_id' => '01', 'code' => '80000', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80050', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80100', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80150', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80200', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80250', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80300', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80350', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80400', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80500', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80506', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80508', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80516', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80519', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80534', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80536', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80542', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80546', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80558', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80560', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80564', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80568', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80578', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80584', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80586', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80590', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80592', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80594', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80596', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80600', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80604', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80608', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80620', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80622', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80628', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80644', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80648', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80662', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80664', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80668', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80670', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80672', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80673', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80676', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80700', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80710', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80720', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80730', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80900', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80902', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80904', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80906', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80908', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80988', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '80990', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '81000', 'post_office_id' => 'Kulai'],
    ['state_id' => '01', 'code' => '81100', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '81200', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '81300', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '81310', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '81400', 'post_office_id' => 'Senai'],
    ['state_id' => '01', 'code' => '81440', 'post_office_id' => 'Bandar Tenggara'],
    ['state_id' => '01', 'code' => '81450', 'post_office_id' => 'Gugusan Taib Andak'],
    ['state_id' => '01', 'code' => '81500', 'post_office_id' => 'Pekan Nenas'],
    ['state_id' => '01', 'code' => '81500', 'post_office_id' => 'Gelang Patah'],
    ['state_id' => '01', 'code' => '81550', 'post_office_id' => 'Gelang Patah'],
    ['state_id' => '01', 'code' => '81550', 'post_office_id' => 'Pulau Satu'],
    ['state_id' => '01', 'code' => '81600', 'post_office_id' => 'Pengerang'],
    ['state_id' => '01', 'code' => '81700', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '81700', 'post_office_id' => 'Pasir Gudang'],
    ['state_id' => '01', 'code' => '81750', 'post_office_id' => 'Masai'],
    ['state_id' => '01', 'code' => '81750', 'post_office_id' => 'Johor Bahru'],
    ['state_id' => '01', 'code' => '81800', 'post_office_id' => 'Ulu Tiram'],
    ['state_id' => '01', 'code' => '81850', 'post_office_id' => 'Layang-Layang'],
    ['state_id' => '01', 'code' => '81900', 'post_office_id' => 'Kota Tinggi'],
    ['state_id' => '01', 'code' => '81920', 'post_office_id' => 'Ayer Tawar 2'],
    ['state_id' => '01', 'code' => '81930', 'post_office_id' => 'Bandar Penawar'],
    ['state_id' => '01', 'code' => '82000', 'post_office_id' => 'Pontian'],
    ['state_id' => '01', 'code' => '82100', 'post_office_id' => 'Ayer Baloi'],
    ['state_id' => '01', 'code' => '82200', 'post_office_id' => 'Benut'],
    ['state_id' => '01', 'code' => '82300', 'post_office_id' => 'Kukup'],
    ['state_id' => '01', 'code' => '83000', 'post_office_id' => 'Batu Pahat'],
    ['state_id' => '01', 'code' => '83100', 'post_office_id' => 'Rengit'],
    ['state_id' => '01', 'code' => '83200', 'post_office_id' => 'Senggarang'],
    ['state_id' => '01', 'code' => '83300', 'post_office_id' => 'Seri Gading'],
    ['state_id' => '01', 'code' => '83300', 'post_office_id' => 'Batu Pahat'],
    ['state_id' => '01', 'code' => '83400', 'post_office_id' => 'Seri Medan'],
    ['state_id' => '01', 'code' => '83500', 'post_office_id' => 'Parit Sulong'],
    ['state_id' => '01', 'code' => '83600', 'post_office_id' => 'Semerah'],
    ['state_id' => '01', 'code' => '83700', 'post_office_id' => 'Yong Peng'],
    ['state_id' => '01', 'code' => '84000', 'post_office_id' => 'Muar'],
    ['state_id' => '01', 'code' => '84150', 'post_office_id' => 'Parit Jawa'],
    ['state_id' => '01', 'code' => '84200', 'post_office_id' => 'Muar'],
    ['state_id' => '01', 'code' => '84300', 'post_office_id' => 'Bukit Pasir'],
    ['state_id' => '01', 'code' => '84400', 'post_office_id' => 'Sungai Mati'],
    ['state_id' => '01', 'code' => '84500', 'post_office_id' => 'Panchor'],
    ['state_id' => '01', 'code' => '84600', 'post_office_id' => 'Pagoh'],
    ['state_id' => '01', 'code' => '84700', 'post_office_id' => 'Gerisek'],
    ['state_id' => '01', 'code' => '84800', 'post_office_id' => 'Bukit Gambir'],
    ['state_id' => '01', 'code' => '84900', 'post_office_id' => 'Tangkak'],
    ['state_id' => '01', 'code' => '85000', 'post_office_id' => 'Segamat'],
    ['state_id' => '01', 'code' => '85100', 'post_office_id' => 'Batu Anam'],
    ['state_id' => '01', 'code' => '85200', 'post_office_id' => 'Jementah'],
    ['state_id' => '01', 'code' => '85300', 'post_office_id' => 'Labis'],
    ['state_id' => '01', 'code' => '85400', 'post_office_id' => 'Chaah'],
    ['state_id' => '01', 'code' => '86000', 'post_office_id' => 'Kluang'],
    ['state_id' => '01', 'code' => '86100', 'post_office_id' => 'Ayer Hitam'],
    ['state_id' => '01', 'code' => '86200', 'post_office_id' => 'Simpang Rengam'],
    ['state_id' => '01', 'code' => '86300', 'post_office_id' => 'Rengam'],
    ['state_id' => '01', 'code' => '86400', 'post_office_id' => 'Parit Raja'],
    ['state_id' => '01', 'code' => '86500', 'post_office_id' => 'Bekok'],
    ['state_id' => '01', 'code' => '86600', 'post_office_id' => 'Paloh'],
    ['state_id' => '01', 'code' => '86700', 'post_office_id' => 'Kahang'],
    ['state_id' => '01', 'code' => '86800', 'post_office_id' => 'Mersing'],
    ['state_id' => '01', 'code' => '86810', 'post_office_id' => 'Mersing'],
    ['state_id' => '01', 'code' => '86888', 'post_office_id' => 'Mersing'],
    ['state_id' => '01', 'code' => '86900', 'post_office_id' => 'Endau'],
];
