<?php

$data = [
    ['state_id' => '02', 'code' => '05000', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05050', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05100', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05150', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05200', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05250', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05300', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05350', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05400', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05460', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05500', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05502', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05503', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05504', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05505', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05506', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05508', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05512', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05514', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05516', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05517', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05518', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05520', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05532', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05534', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05536', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05538', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05550', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05551', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05552', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05556', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05558', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05560', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05564', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05576', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05578', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05580', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05582', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05586', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05590', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05592', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05594', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05600', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05604', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05610', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05612', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05614', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05620', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05621', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05622', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05626', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05628', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05630', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05632', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05644', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05660', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05661', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05664', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05670', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05672', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05673', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05674', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05675', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05676', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05680', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05690', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05696', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05700', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05710', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05720', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '05990', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '06000', 'post_office_id' => 'Jitra'],
    ['state_id' => '02', 'code' => '06007', 'post_office_id' => 'Jitra'],
    ['state_id' => '02', 'code' => '06009', 'post_office_id' => 'Jitra'],
    ['state_id' => '02', 'code' => '06010', 'post_office_id' => 'Changloon'],
    ['state_id' => '02', 'code' => '06010', 'post_office_id' => 'Universiti Utara Malaysia'],
    ['state_id' => '02', 'code' => '06050', 'post_office_id' => 'Bukit Kayu Hitam'],
    ['state_id' => '02', 'code' => '06100', 'post_office_id' => 'Kodiang'],
    ['state_id' => '02', 'code' => '06150', 'post_office_id' => 'Ayer Hitam'],
    ['state_id' => '02', 'code' => '06200', 'post_office_id' => 'Kepala Batas'],
    ['state_id' => '02', 'code' => '06207', 'post_office_id' => 'Kepala Batas'],
    ['state_id' => '02', 'code' => '06209', 'post_office_id' => 'Kepala Batas'],
    ['state_id' => '02', 'code' => '06250', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '06300', 'post_office_id' => 'Kuala Nerang'],
    ['state_id' => '02', 'code' => '06350', 'post_office_id' => 'Pokok Sena'],
    ['state_id' => '02', 'code' => '06400', 'post_office_id' => 'Pokok Sena'],
    ['state_id' => '02', 'code' => '06500', 'post_office_id' => 'Langgar'],
    ['state_id' => '02', 'code' => '06507', 'post_office_id' => 'Langgar'],
    ['state_id' => '02', 'code' => '06509', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '06550', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '06570', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '06600', 'post_office_id' => 'Kuala Kedah'],
    ['state_id' => '02', 'code' => '06650', 'post_office_id' => 'Simpang Empat'],
    ['state_id' => '02', 'code' => '06660', 'post_office_id' => 'Alor Setar'],
    ['state_id' => '02', 'code' => '06700', 'post_office_id' => 'Pendang'],
    ['state_id' => '02', 'code' => '06707', 'post_office_id' => 'Pendang'],
    ['state_id' => '02', 'code' => '06709', 'post_office_id' => 'Pendang'],
    ['state_id' => '02', 'code' => '06710', 'post_office_id' => 'Pendang'],
    ['state_id' => '02', 'code' => '06720', 'post_office_id' => 'Pendang'],
    ['state_id' => '02', 'code' => '06750', 'post_office_id' => 'Pendang'],
    ['state_id' => '02', 'code' => '06760', 'post_office_id' => 'Pokok Sena'],
    ['state_id' => '02', 'code' => '06800', 'post_office_id' => 'Kota Sarang Semut'],
    ['state_id' => '02', 'code' => '06900', 'post_office_id' => 'Yan'],
    ['state_id' => '02', 'code' => '06910', 'post_office_id' => 'Yan'],
    ['state_id' => '02', 'code' => '07000', 'post_office_id' => 'Langkawi'],
    ['state_id' => '02', 'code' => '07007', 'post_office_id' => 'Langkawi'],
    ['state_id' => '02', 'code' => '07009', 'post_office_id' => 'Langkawi'],
    ['state_id' => '02', 'code' => '08000', 'post_office_id' => 'Sungai Petani'],
    ['state_id' => '02', 'code' => '08007', 'post_office_id' => 'Sungai Petani'],
    ['state_id' => '02', 'code' => '08009', 'post_office_id' => 'Sungai Petani'],
    ['state_id' => '02', 'code' => '08010', 'post_office_id' => 'Sungai Petani'],
    ['state_id' => '02', 'code' => '08100', 'post_office_id' => 'Bedong'],
    ['state_id' => '02', 'code' => '08110', 'post_office_id' => 'Bedong'],
    ['state_id' => '02', 'code' => '08200', 'post_office_id' => 'Sik'],
    ['state_id' => '02', 'code' => '08210', 'post_office_id' => 'Sik'],
    ['state_id' => '02', 'code' => '08300', 'post_office_id' => 'Gurun'],
    ['state_id' => '02', 'code' => '08320', 'post_office_id' => 'Jeniang'],
    ['state_id' => '02', 'code' => '08330', 'post_office_id' => 'Gurun'],
    ['state_id' => '02', 'code' => '08340', 'post_office_id' => 'Sik'],
    ['state_id' => '02', 'code' => '08400', 'post_office_id' => 'Merbok'],
    ['state_id' => '02', 'code' => '08407', 'post_office_id' => 'Merbok'],
    ['state_id' => '02', 'code' => '08409', 'post_office_id' => 'Merbok'],
    ['state_id' => '02', 'code' => '08500', 'post_office_id' => 'Kota Kuala Muda'],
    ['state_id' => '02', 'code' => '08507', 'post_office_id' => 'Kota Kuala Muda'],
    ['state_id' => '02', 'code' => '08509', 'post_office_id' => 'Kota Kuala Muda'],
    ['state_id' => '02', 'code' => '08600', 'post_office_id' => 'Sungai Petani'],
    ['state_id' => '02', 'code' => '08700', 'post_office_id' => 'Jeniang'],
    ['state_id' => '02', 'code' => '08800', 'post_office_id' => 'Gurun'],
    ['state_id' => '02', 'code' => '09000', 'post_office_id' => 'Kulim'],
    ['state_id' => '02', 'code' => '09007', 'post_office_id' => 'Kulim'],
    ['state_id' => '02', 'code' => '09009', 'post_office_id' => 'Kulim'],
    ['state_id' => '02', 'code' => '09010', 'post_office_id' => 'Kulim'],
    ['state_id' => '02', 'code' => '09020', 'post_office_id' => 'Kulim'],
    ['state_id' => '02', 'code' => '09100', 'post_office_id' => 'Baling'],
    ['state_id' => '02', 'code' => '09110', 'post_office_id' => 'Kuala Pegang'],
    ['state_id' => '02', 'code' => '09120', 'post_office_id' => 'Baling'],
    ['state_id' => '02', 'code' => '09130', 'post_office_id' => 'Baling'],
    ['state_id' => '02', 'code' => '09200', 'post_office_id' => 'Kupang'],
    ['state_id' => '02', 'code' => '09300', 'post_office_id' => 'Kuala Ketil'],
    ['state_id' => '02', 'code' => '09310', 'post_office_id' => 'Kuala Ketil'],
    ['state_id' => '02', 'code' => '09400', 'post_office_id' => 'Padang Serai'],
    ['state_id' => '02', 'code' => '09410', 'post_office_id' => 'Padang Serai'],
    ['state_id' => '02', 'code' => '09600', 'post_office_id' => 'Lunas'],
    ['state_id' => '02', 'code' => '09700', 'post_office_id' => 'Karangan'],
    ['state_id' => '02', 'code' => '09800', 'post_office_id' => 'Serdang'],
    ['state_id' => '02', 'code' => '09810', 'post_office_id' => 'Serdang'],
    ['state_id' => '02', 'code' => '14290', 'post_office_id' => 'Bandar Baharu'],
    ['state_id' => '02', 'code' => '14390', 'post_office_id' => 'Bandar Baharu'],
    ['state_id' => '02', 'code' => '34950', 'post_office_id' => 'Bandar Baharu'],
];