<?php

$data = [
    ['state_id' => '03', 'code' => '15000', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15050', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15100', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15150', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15159', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15200', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15300', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15350', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15400', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15500', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15502', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15503', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15504', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15505', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15506', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15508', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15512', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15514', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15516', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15517', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15518', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15519', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15520', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15524', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15529', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15532', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15534', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15536', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15538', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15540', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15546', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15548', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15550', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15551', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15556', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15558', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15560', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15564', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15570', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15572', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15576', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15578', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15582', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15586', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15590', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15592', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15594', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15596', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15600', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15604', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15608', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15609', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15612', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15614', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15616', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15622', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15623', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15626', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15628', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15630', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15632', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15634', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15644', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15646', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15648', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15658', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15660', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15661', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15664', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15670', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15672', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15673', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15674', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15676', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15680', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15690', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15710', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15720', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15730', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15740', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15988', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '15990', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '16010', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '16020', 'post_office_id' => 'Bachok'],
    ['state_id' => '03', 'code' => '16030', 'post_office_id' => 'Bachok'],
    ['state_id' => '03', 'code' => '16040', 'post_office_id' => 'Wakaf Bharu'],
    ['state_id' => '03', 'code' => '16050', 'post_office_id' => 'Bachok'],
    ['state_id' => '03', 'code' => '16060', 'post_office_id' => 'Bachok'],
    ['state_id' => '03', 'code' => '16070', 'post_office_id' => 'Bachok'],
    ['state_id' => '03', 'code' => '16080', 'post_office_id' => 'Tumpat'],
    ['state_id' => '03', 'code' => '16090', 'post_office_id' => 'Bachok'],
    ['state_id' => '03', 'code' => '16100', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '16109', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '16150', 'post_office_id' => 'Kota Bharu'],
    ['state_id' => '03', 'code' => '16200', 'post_office_id' => 'Tumpat'],
    ['state_id' => '03', 'code' => '16210', 'post_office_id' => 'Tumpat'],
    ['state_id' => '03', 'code' => '16250', 'post_office_id' => 'Wakaf Bharu'],
    ['state_id' => '03', 'code' => '16300', 'post_office_id' => 'Bachok'],
    ['state_id' => '03', 'code' => '16310', 'post_office_id' => 'Bachok'],
    ['state_id' => '03', 'code' => '16320', 'post_office_id' => 'Bachok'],
    ['state_id' => '03', 'code' => '16400', 'post_office_id' => 'Melor'],
    ['state_id' => '03', 'code' => '16450', 'post_office_id' => 'Ketereh'],
    ['state_id' => '03', 'code' => '16500', 'post_office_id' => 'Kem Desa Pahlawan'],
    ['state_id' => '03', 'code' => '16600', 'post_office_id' => 'Pulai Chondong'],
    ['state_id' => '03', 'code' => '16700', 'post_office_id' => 'Cherang Ruku'],
    ['state_id' => '03', 'code' => '16800', 'post_office_id' => 'Pasir Puteh'],
    ['state_id' => '03', 'code' => '16810', 'post_office_id' => 'Selising'],
    ['state_id' => '03', 'code' => '17000', 'post_office_id' => 'Pasir Mas'],
    ['state_id' => '03', 'code' => '17007', 'post_office_id' => 'Pasir Mas'],
    ['state_id' => '03', 'code' => '17009', 'post_office_id' => 'Pasir Mas'],
    ['state_id' => '03', 'code' => '17010', 'post_office_id' => 'Pasir Mas'],
    ['state_id' => '03', 'code' => '17020', 'post_office_id' => 'Pasir Mas'],
    ['state_id' => '03', 'code' => '17030', 'post_office_id' => 'Pasir Mas'],
    ['state_id' => '03', 'code' => '17040', 'post_office_id' => 'Pasir Mas'],
    ['state_id' => '03', 'code' => '17050', 'post_office_id' => 'Pasir Mas'],
    ['state_id' => '03', 'code' => '17060', 'post_office_id' => 'Pasir Mas'],
    ['state_id' => '03', 'code' => '17070', 'post_office_id' => 'Pasir Mas'],
    ['state_id' => '03', 'code' => '17200', 'post_office_id' => 'Rantau Panjang'],
    ['state_id' => '03', 'code' => '17500', 'post_office_id' => 'Tanah Merah'],
    ['state_id' => '03', 'code' => '17507', 'post_office_id' => 'Tanah Merah'],
    ['state_id' => '03', 'code' => '17509', 'post_office_id' => 'Tanah Merah'],
    ['state_id' => '03', 'code' => '17510', 'post_office_id' => 'Tanah Merah'],
    ['state_id' => '03', 'code' => '17600', 'post_office_id' => 'Jeli'],
    ['state_id' => '03', 'code' => '17610', 'post_office_id' => 'Kuala Balah'],
    ['state_id' => '03', 'code' => '17700', 'post_office_id' => 'Ayer Lanas'],
    ['state_id' => '03', 'code' => '18000', 'post_office_id' => 'Kuala Krai'],
    ['state_id' => '03', 'code' => '18050', 'post_office_id' => 'Kuala Krai'],
    ['state_id' => '03', 'code' => '18200', 'post_office_id' => 'Dabong'],
    ['state_id' => '03', 'code' => '18300', 'post_office_id' => 'Gua Musang'],
    ['state_id' => '03', 'code' => '18400', 'post_office_id' => 'Temangan'],
    ['state_id' => '03', 'code' => '18500', 'post_office_id' => 'Machang'],
];