<?php

$data = [
    ['state_id' => '04', 'code' => '75000', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75050', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75100', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75150', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75200', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75250', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75260', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75300', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75350', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75400', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75450', 'post_office_id' => 'Ayer Keroh'],
    ['state_id' => '04', 'code' => '75460', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75500', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75502', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75503', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75504', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75505', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75506', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75508', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75510', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75512', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75514', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75516', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75517', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75518', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75519', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75532', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75536', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75538', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75540', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75542', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75546', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75550', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75551', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75552', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75560', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75564', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75566', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75570', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75572', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75576', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75578', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75582', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75584', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75586', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75590', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75592', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75594', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75596', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75600', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75604', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75606', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75608', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75609', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75610', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75612', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75618', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75620', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75622', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75626', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75628', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75630', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75632', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75646', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75648', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75662', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75670', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75672', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75673', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75674', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75676', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75690', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75700', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75710', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75720', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75730', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75740', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75750', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75760', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75900', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75902', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75904', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75906', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75908', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75910', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75912', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75914', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75916', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75918', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '75990', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '76100', 'post_office_id' => 'Durian Tunggal'],
    ['state_id' => '04', 'code' => '76109', 'post_office_id' => 'Durian Tunggal'],
    ['state_id' => '04', 'code' => '76200', 'post_office_id' => 'Kem Trendak'],
    ['state_id' => '04', 'code' => '76300', 'post_office_id' => 'Sungai Udang'],
    ['state_id' => '04', 'code' => '76400', 'post_office_id' => 'Tanjong Kling'],
    ['state_id' => '04', 'code' => '76409', 'post_office_id' => 'Tanjong Kling'],
    ['state_id' => '04', 'code' => '76450', 'post_office_id' => 'Melaka'],
    ['state_id' => '04', 'code' => '77000', 'post_office_id' => 'Jasin'],
    ['state_id' => '04', 'code' => '77007', 'post_office_id' => 'Jasin'],
    ['state_id' => '04', 'code' => '77008', 'post_office_id' => 'Jasin'],
    ['state_id' => '04', 'code' => '77009', 'post_office_id' => 'Jasin'],
    ['state_id' => '04', 'code' => '77100', 'post_office_id' => 'Asahan'],
    ['state_id' => '04', 'code' => '77109', 'post_office_id' => 'Asahan'],
    ['state_id' => '04', 'code' => '77200', 'post_office_id' => 'Bemban'],
    ['state_id' => '04', 'code' => '77300', 'post_office_id' => 'Merlimau'],
    ['state_id' => '04', 'code' => '77309', 'post_office_id' => 'Merlimau'],
    ['state_id' => '04', 'code' => '77400', 'post_office_id' => 'Sungai Rambai'],
    ['state_id' => '04', 'code' => '77409', 'post_office_id' => 'Sungai Rambai'],
    ['state_id' => '04', 'code' => '77500', 'post_office_id' => 'Selandar'],
    ['state_id' => '04', 'code' => '78000', 'post_office_id' => 'Alor Gajah'],
    ['state_id' => '04', 'code' => '78009', 'post_office_id' => 'Alor Gajah'],
    ['state_id' => '04', 'code' => '78100', 'post_office_id' => 'Lubok China'],
    ['state_id' => '04', 'code' => '78200', 'post_office_id' => 'Kuala Sungai Baru'],
    ['state_id' => '04', 'code' => '78300', 'post_office_id' => 'Masjid Tanah'],
    ['state_id' => '04', 'code' => '78307', 'post_office_id' => 'Masjid Tanah'],
    ['state_id' => '04', 'code' => '78309', 'post_office_id' => 'Masjid Tanah'],
];
