<?php

$data = [
    ['state_id' => '05', 'code' => '70000', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70100', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70200', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70300', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70400', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70450', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70500', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70502', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70503', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70504', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70505', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70506', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70508', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70512', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70516', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70517', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70518', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70532', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70534', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70536', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70540', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70546', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70548', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70550', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70551', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70558', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70560', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70564', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70570', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70572', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70576', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70578', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70582', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70586', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70590', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70592', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70594', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70596', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70600', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70604', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70606', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70608', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70609', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70610', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70620', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70626', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70628', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70632', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70634', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70644', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70646', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70648', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70658', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70664', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70670', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70672', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70673', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70674', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70676', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70690', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70700', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70710', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70720', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70730', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70740', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70750', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '70990', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '71000', 'post_office_id' => 'Port Dickson'],
    ['state_id' => '05', 'code' => '71007', 'post_office_id' => 'Port Dickson'],
    ['state_id' => '05', 'code' => '71009', 'post_office_id' => 'Port Dickson'],
    ['state_id' => '05', 'code' => '71010', 'post_office_id' => 'Port Dickson'],
    ['state_id' => '05', 'code' => '71050', 'post_office_id' => 'Si Rusa'],
    ['state_id' => '05', 'code' => '71059', 'post_office_id' => 'Si Rusa'],
    ['state_id' => '05', 'code' => '71100', 'post_office_id' => 'Rantau'],
    ['state_id' => '05', 'code' => '71109', 'post_office_id' => 'Rantau'],
    ['state_id' => '05', 'code' => '71150', 'post_office_id' => 'Linggi'],
    ['state_id' => '05', 'code' => '71159', 'post_office_id' => 'Linggi'],
    ['state_id' => '05', 'code' => '71200', 'post_office_id' => 'Rantau'],
    ['state_id' => '05', 'code' => '71209', 'post_office_id' => 'Rantau'],
    ['state_id' => '05', 'code' => '71250', 'post_office_id' => 'Si Rusa'],
    ['state_id' => '05', 'code' => '71259', 'post_office_id' => 'Si Rusa'],
    ['state_id' => '05', 'code' => '71300', 'post_office_id' => 'Rembau'],
    ['state_id' => '05', 'code' => '71309', 'post_office_id' => 'Rembau'],
    ['state_id' => '05', 'code' => '71350', 'post_office_id' => 'Kota'],
    ['state_id' => '05', 'code' => '71359', 'post_office_id' => 'Kota'],
    ['state_id' => '05', 'code' => '71400', 'post_office_id' => 'Rembau'],
    ['state_id' => '05', 'code' => '71409', 'post_office_id' => 'Rembau'],
    ['state_id' => '05', 'code' => '71450', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '71459', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '71500', 'post_office_id' => 'Tanjong Ipoh'],
    ['state_id' => '05', 'code' => '71509', 'post_office_id' => 'Tanjong Ipoh'],
    ['state_id' => '05', 'code' => '71550', 'post_office_id' => 'Tanjong Ipoh'],
    ['state_id' => '05', 'code' => '71559', 'post_office_id' => 'Tanjong Ipoh'],
    ['state_id' => '05', 'code' => '71600', 'post_office_id' => 'Kuala Klawang'],
    ['state_id' => '05', 'code' => '71609', 'post_office_id' => 'Kuala Klawang'],
    ['state_id' => '05', 'code' => '71650', 'post_office_id' => 'Kuala Klawang'],
    ['state_id' => '05', 'code' => '71659', 'post_office_id' => 'Kuala Klawang'],
    ['state_id' => '05', 'code' => '71700', 'post_office_id' => 'Mantin'],
    ['state_id' => '05', 'code' => '71707', 'post_office_id' => 'Mantin'],
    ['state_id' => '05', 'code' => '71709', 'post_office_id' => 'Mantin'],
    ['state_id' => '05', 'code' => '71750', 'post_office_id' => 'Mantin'],
    ['state_id' => '05', 'code' => '71759', 'post_office_id' => 'Mantin'],
    ['state_id' => '05', 'code' => '71760', 'post_office_id' => 'Bandar Enstek'],
    ['state_id' => '05', 'code' => '71770', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '71800', 'post_office_id' => 'Nilai'],
    ['state_id' => '05', 'code' => '71807', 'post_office_id' => 'Nilai'],
    ['state_id' => '05', 'code' => '71809', 'post_office_id' => 'Nilai'],
    ['state_id' => '05', 'code' => '71900', 'post_office_id' => 'Labu'],
    ['state_id' => '05', 'code' => '71907', 'post_office_id' => 'Labu'],
    ['state_id' => '05', 'code' => '71909', 'post_office_id' => 'Labu'],
    ['state_id' => '05', 'code' => '71950', 'post_office_id' => 'Seremban'],
    ['state_id' => '05', 'code' => '71960', 'post_office_id' => 'Port Dickson'],
    ['state_id' => '05', 'code' => '72000', 'post_office_id' => 'Kuala Pilah'],
    ['state_id' => '05', 'code' => '72007', 'post_office_id' => 'Kuala Pilah'],
    ['state_id' => '05', 'code' => '72009', 'post_office_id' => 'Kuala Pilah'],
    ['state_id' => '05', 'code' => '72100', 'post_office_id' => 'Bahau'],
    ['state_id' => '05', 'code' => '72107', 'post_office_id' => 'Bahau'],
    ['state_id' => '05', 'code' => '72109', 'post_office_id' => 'Bahau'],
    ['state_id' => '05', 'code' => '72120', 'post_office_id' => 'Bandar Seri Jempol'],
    ['state_id' => '05', 'code' => '72127', 'post_office_id' => 'Bandar Seri Jempol'],
    ['state_id' => '05', 'code' => '72129', 'post_office_id' => 'Bandar Seri Jempol'],
    ['state_id' => '05', 'code' => '72200', 'post_office_id' => 'Batu Kikir'],
    ['state_id' => '05', 'code' => '72207', 'post_office_id' => 'Batu Kikir'],
    ['state_id' => '05', 'code' => '72209', 'post_office_id' => 'Batu Kikir'],
    ['state_id' => '05', 'code' => '72300', 'post_office_id' => 'Simpang Pertang'],
    ['state_id' => '05', 'code' => '72307', 'post_office_id' => 'Simpang Pertang'],
    ['state_id' => '05', 'code' => '72309', 'post_office_id' => 'Simpang Pertang'],
    ['state_id' => '05', 'code' => '72400', 'post_office_id' => 'Simpang Durian'],
    ['state_id' => '05', 'code' => '72409', 'post_office_id' => 'Simpang Durian'],
    ['state_id' => '05', 'code' => '72500', 'post_office_id' => 'Kuala Pilah'],
    ['state_id' => '05', 'code' => '72507', 'post_office_id' => 'Kuala Pilah'],
    ['state_id' => '05', 'code' => '72509', 'post_office_id' => 'Kuala Pilah'],
    ['state_id' => '05', 'code' => '73000', 'post_office_id' => 'Tampin'],
    ['state_id' => '05', 'code' => '73007', 'post_office_id' => 'Tampin'],
    ['state_id' => '05', 'code' => '73009', 'post_office_id' => 'Tampin'],
    ['state_id' => '05', 'code' => '73100', 'post_office_id' => 'Johol'],
    ['state_id' => '05', 'code' => '73109', 'post_office_id' => 'Johol'],
    ['state_id' => '05', 'code' => '73200', 'post_office_id' => 'Gemencheh'],
    ['state_id' => '05', 'code' => '73207', 'post_office_id' => 'Gemencheh'],
    ['state_id' => '05', 'code' => '73209', 'post_office_id' => 'Gemencheh'],
    ['state_id' => '05', 'code' => '73300', 'post_office_id' => 'Gemencheh'],
    ['state_id' => '05', 'code' => '73309', 'post_office_id' => 'Gemencheh'],
    ['state_id' => '05', 'code' => '73400', 'post_office_id' => 'Gemas'],
    ['state_id' => '05', 'code' => '73409', 'post_office_id' => 'Gemas'],
    ['state_id' => '05', 'code' => '73420', 'post_office_id' => 'Gemas'],
    ['state_id' => '05', 'code' => '73430', 'post_office_id' => 'Pusat Bandar Palong'],
    ['state_id' => '05', 'code' => '73440', 'post_office_id' => 'Pusat Bandar Palong'],
    ['state_id' => '05', 'code' => '73450', 'post_office_id' => 'Pusat Bandar Palong'],
    ['state_id' => '05', 'code' => '73460', 'post_office_id' => 'Pusat Bandar Palong'],
    ['state_id' => '05', 'code' => '73470', 'post_office_id' => 'Pusat Bandar Palong'],
    ['state_id' => '05', 'code' => '73480', 'post_office_id' => 'Gemas'],
    ['state_id' => '05', 'code' => '73500', 'post_office_id' => 'Rompin'],
    ['state_id' => '05', 'code' => '73507', 'post_office_id' => 'Rompin'],
    ['state_id' => '05', 'code' => '73509', 'post_office_id' => 'Rompin'],
    ['state_id' => '05', 'code' => '70300', 'post_office_id' => 'Seremban'],
];