<?php

$data = [
    ['state_id' => '06', 'code' => '25000', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25050', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25100', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25150', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25200', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25250', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25300', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25350', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25500', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25502', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25503', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25504', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25505', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25506', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25508', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25509', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25512', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25514', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25516', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25517', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25518', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25520', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25524', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25529', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25532', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25534', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25536', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25538', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25540', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25546', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25548', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25550', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25551', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25552', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25556', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25558', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25560', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25564', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25570', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25576', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25578', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25582', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25584', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25586', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25590', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25592', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25594', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25596', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25598', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25600', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25604', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25606', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25608', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25609', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25610', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25612', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25614', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25620', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25622', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25626', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25628', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25630', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25632', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25644', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25646', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25648', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25656', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25660', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25661', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25662', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25670', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25672', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25673', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25674', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25676', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25690', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25700', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25710', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25720', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25730', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25740', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25750', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '25990', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '26010', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '26040', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '26050', 'post_office_id' => 'Bukit Goh'],
    ['state_id' => '06', 'code' => '26050', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '26060', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '26070', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '26080', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '26090', 'post_office_id' => 'Bukit Goh'],
    ['state_id' => '06', 'code' => '26100', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '26140', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '26150', 'post_office_id' => 'Balok'],
    ['state_id' => '06', 'code' => '26180', 'post_office_id' => 'Bukit Kuin'],
    ['state_id' => '06', 'code' => '26190', 'post_office_id' => 'Balok'],
    ['state_id' => '06', 'code' => '26200', 'post_office_id' => 'Sungai Lembing'],
    ['state_id' => '06', 'code' => '26250', 'post_office_id' => 'Kuantan'],
    ['state_id' => '06', 'code' => '26300', 'post_office_id' => 'Gambang'],
    ['state_id' => '06', 'code' => '26310', 'post_office_id' => 'Gambang'],
    ['state_id' => '06', 'code' => '26320', 'post_office_id' => 'Gambang'],
    ['state_id' => '06', 'code' => '26330', 'post_office_id' => 'Gambang'],
    ['state_id' => '06', 'code' => '26340', 'post_office_id' => 'Gambang'],
    ['state_id' => '06', 'code' => '26350', 'post_office_id' => 'Gambang'],
    ['state_id' => '06', 'code' => '26360', 'post_office_id' => 'Gambang'],
    ['state_id' => '06', 'code' => '26370', 'post_office_id' => 'Gambang'],
    ['state_id' => '06', 'code' => '26400', 'post_office_id' => 'Bandar Pusat Jengka'],
    ['state_id' => '06', 'code' => '26410', 'post_office_id' => 'Bandar Pusat Jengka'],
    ['state_id' => '06', 'code' => '26420', 'post_office_id' => 'Bandar Pusat Jengka'],
    ['state_id' => '06', 'code' => '26430', 'post_office_id' => 'Bandar Pusat Jengka'],
    ['state_id' => '06', 'code' => '26440', 'post_office_id' => 'Bandar Pusat Jengka'],
    ['state_id' => '06', 'code' => '26450', 'post_office_id' => 'Bandar Pusat Jengka'],
    ['state_id' => '06', 'code' => '26460', 'post_office_id' => 'Bandar Pusat Jengka'],
    ['state_id' => '06', 'code' => '26485', 'post_office_id' => 'Bandar Pusat Jengka'],
    ['state_id' => '06', 'code' => '26490', 'post_office_id' => 'Bandar Pusat Jengka'],
    ['state_id' => '06', 'code' => '26500', 'post_office_id' => 'Maran'],
    ['state_id' => '06', 'code' => '26600', 'post_office_id' => 'Pekan'],
    ['state_id' => '06', 'code' => '26607', 'post_office_id' => 'Pekan'],
    ['state_id' => '06', 'code' => '26609', 'post_office_id' => 'Pekan'],
    ['state_id' => '06', 'code' => '26610', 'post_office_id' => 'Pekan'],
    ['state_id' => '06', 'code' => '26620', 'post_office_id' => 'Pekan'],
    ['state_id' => '06', 'code' => '26630', 'post_office_id' => 'Pekan'],
    ['state_id' => '06', 'code' => '26640', 'post_office_id' => 'Pekan'],
    ['state_id' => '06', 'code' => '26650', 'post_office_id' => 'Pekan'],
    ['state_id' => '06', 'code' => '26660', 'post_office_id' => 'Pekan'],
    ['state_id' => '06', 'code' => '26680', 'post_office_id' => 'Pekan'],
    ['state_id' => '06', 'code' => '26690', 'post_office_id' => 'Chini'],
    ['state_id' => '06', 'code' => '26700', 'post_office_id' => 'Muadzam Shah'],
    ['state_id' => '06', 'code' => '26800', 'post_office_id' => 'Kuala Rompin'],
    ['state_id' => '06', 'code' => '26810', 'post_office_id' => 'Kuala Rompin'],
    ['state_id' => '06', 'code' => '26820', 'post_office_id' => 'Kuala Rompin'],
    ['state_id' => '06', 'code' => '26900', 'post_office_id' => 'Bandar Tun Abdul Razak'],
    ['state_id' => '06', 'code' => '27000', 'post_office_id' => 'Jerantut'],
    ['state_id' => '06', 'code' => '27010', 'post_office_id' => 'Jerantut'],
    ['state_id' => '06', 'code' => '27020', 'post_office_id' => 'Jerantut'],
    ['state_id' => '06', 'code' => '27030', 'post_office_id' => 'Damak'],
    ['state_id' => '06', 'code' => '27040', 'post_office_id' => 'Jerantut'],
    ['state_id' => '06', 'code' => '27050', 'post_office_id' => 'Jerantut'],
    ['state_id' => '06', 'code' => '27060', 'post_office_id' => 'Jerantut'],
    ['state_id' => '06', 'code' => '27070', 'post_office_id' => 'Jerantut'],
    ['state_id' => '06', 'code' => '27090', 'post_office_id' => 'Jerantut'],
    ['state_id' => '06', 'code' => '27100', 'post_office_id' => 'Padang Tengku'],
    ['state_id' => '06', 'code' => '27150', 'post_office_id' => 'Jerantut'],
    ['state_id' => '06', 'code' => '27200', 'post_office_id' => 'Kuala Lipis'],
    ['state_id' => '06', 'code' => '27207', 'post_office_id' => 'Kuala Lipis'],
    ['state_id' => '06', 'code' => '27209', 'post_office_id' => 'Kuala Lipis'],
    ['state_id' => '06', 'code' => '27210', 'post_office_id' => 'Kuala Lipis'],
    ['state_id' => '06', 'code' => '27300', 'post_office_id' => 'Benta'],
    ['state_id' => '06', 'code' => '27310', 'post_office_id' => 'Benta'],
    ['state_id' => '06', 'code' => '27400', 'post_office_id' => 'Dong'],
    ['state_id' => '06', 'code' => '27600', 'post_office_id' => 'Raub'],
    ['state_id' => '06', 'code' => '27607', 'post_office_id' => 'Raub'],
    ['state_id' => '06', 'code' => '27609', 'post_office_id' => 'Raub'],
    ['state_id' => '06', 'code' => '27610', 'post_office_id' => 'Raub'],
    ['state_id' => '06', 'code' => '27620', 'post_office_id' => 'Raub'],
    ['state_id' => '06', 'code' => '27630', 'post_office_id' => 'Raub'],
    ['state_id' => '06', 'code' => '27650', 'post_office_id' => 'Sungai Koyan'],
    ['state_id' => '06', 'code' => '27660', 'post_office_id' => 'Sega'],
    ['state_id' => '06', 'code' => '27670', 'post_office_id' => 'Raub'],
    ['state_id' => '06', 'code' => '28000', 'post_office_id' => 'Temerloh'],
    ['state_id' => '06', 'code' => '28007', 'post_office_id' => 'Temerloh'],
    ['state_id' => '06', 'code' => '28009', 'post_office_id' => 'Temerloh'],
    ['state_id' => '06', 'code' => '28010', 'post_office_id' => 'Temerloh'],
    ['state_id' => '06', 'code' => '28020', 'post_office_id' => 'Temerloh'],
    ['state_id' => '06', 'code' => '28030', 'post_office_id' => 'Temerloh'],
    ['state_id' => '06', 'code' => '28040', 'post_office_id' => 'Temerloh'],
    ['state_id' => '06', 'code' => '28050', 'post_office_id' => 'Kuala Krau'],
    ['state_id' => '06', 'code' => '28100', 'post_office_id' => 'Chenor'],
    ['state_id' => '06', 'code' => '28200', 'post_office_id' => 'Bandar Bera'],
    ['state_id' => '06', 'code' => '28300', 'post_office_id' => 'Triang'],
    ['state_id' => '06', 'code' => '28310', 'post_office_id' => 'Triang'],
    ['state_id' => '06', 'code' => '28320', 'post_office_id' => 'Triang'],
    ['state_id' => '06', 'code' => '28330', 'post_office_id' => 'Triang'],
    ['state_id' => '06', 'code' => '28340', 'post_office_id' => 'Kemayan'],
    ['state_id' => '06', 'code' => '28380', 'post_office_id' => 'Kemayan'],
    ['state_id' => '06', 'code' => '28400', 'post_office_id' => 'Mentakab'],
    ['state_id' => '06', 'code' => '28407', 'post_office_id' => 'Mentakab'],
    ['state_id' => '06', 'code' => '28409', 'post_office_id' => 'Mentakab'],
    ['state_id' => '06', 'code' => '28500', 'post_office_id' => 'Lanchang'],
    ['state_id' => '06', 'code' => '28600', 'post_office_id' => 'Karak'],
    ['state_id' => '06', 'code' => '28610', 'post_office_id' => 'Karak'],
    ['state_id' => '06', 'code' => '28620', 'post_office_id' => 'Karak'],
    ['state_id' => '06', 'code' => '28700', 'post_office_id' => 'Bentong'],
    ['state_id' => '06', 'code' => '28707', 'post_office_id' => 'Bentong'],
    ['state_id' => '06', 'code' => '28709', 'post_office_id' => 'Bentong'],
    ['state_id' => '06', 'code' => '28730', 'post_office_id' => 'Bentong'],
    ['state_id' => '06', 'code' => '28740', 'post_office_id' => 'Bentong'],
    ['state_id' => '06', 'code' => '28750', 'post_office_id' => 'Bentong'],
    ['state_id' => '06', 'code' => '28800', 'post_office_id' => 'Lurah Bilut'],
    ['state_id' => '06', 'code' => '39000', 'post_office_id' => 'Tanah Rata'],
    ['state_id' => '06', 'code' => '39007', 'post_office_id' => 'Tanah Rata'],
    ['state_id' => '06', 'code' => '39009', 'post_office_id' => 'Tanah Rata'],
    ['state_id' => '06', 'code' => '39010', 'post_office_id' => 'Tanah Rata'],
    ['state_id' => '06', 'code' => '39100', 'post_office_id' => 'Brinchang'],
    ['state_id' => '06', 'code' => '39200', 'post_office_id' => 'Ringlet'],
    ['state_id' => '06', 'code' => '49000', 'post_office_id' => 'Bukit Fraser'],
    ['state_id' => '06', 'code' => '69000', 'post_office_id' => 'Genting Highlands'],
];