<?php

$data = [
    ['state_id' => '08', 'code' => '30000', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30010', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30020', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30100', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30200', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30250', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30300', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30350', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30450', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30500', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30502', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30503', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30504', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30505', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30506', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30508', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30510', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30512', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30516', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30517', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30518', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30519', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30520', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30524', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30532', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30534', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30536', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30540', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30542', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30546', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30548', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30550', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30551', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30552', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30554', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30556', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30560', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30564', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30570', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30576', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30580', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30582', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30586', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30590', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30592', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30594', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30596', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30600', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30604', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30606', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30609', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30610', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30612', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30614', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30620', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30621', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30622', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30626', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30628', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30630', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30632', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30634', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30644', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30646', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30648', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30656', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30658', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30660', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30661', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30662', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30664', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30668', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30670', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30673', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30674', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30676', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30682', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30690', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30700', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30710', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30720', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30730', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30740', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30750', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30760', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30770', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30780', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30790', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30800', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30810', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30820', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30830', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30840', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30900', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30902', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30904', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30906', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30908', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30910', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30912', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30988', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '30990', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '31000', 'post_office_id' => 'Batu Gajah'],
    ['state_id' => '08', 'code' => '31007', 'post_office_id' => 'Batu Gajah'],
    ['state_id' => '08', 'code' => '31009', 'post_office_id' => 'Batu Gajah'],
    ['state_id' => '08', 'code' => '31050', 'post_office_id' => 'Sungai Siput'],
    ['state_id' => '08', 'code' => '31100', 'post_office_id' => 'Sungai Siput'],
    ['state_id' => '08', 'code' => '31150', 'post_office_id' => 'Ulu Kinta'],
    ['state_id' => '08', 'code' => '31200', 'post_office_id' => 'Chemor'],
    ['state_id' => '08', 'code' => '31250', 'post_office_id' => 'Tanjong Rambutan'],
    ['state_id' => '08', 'code' => '31300', 'post_office_id' => 'Kampung Kepayang'],
    ['state_id' => '08', 'code' => '31350', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '31400', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '31407', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '31409', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '31450', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '31500', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '31550', 'post_office_id' => 'Pusing'],
    ['state_id' => '08', 'code' => '31560', 'post_office_id' => 'Pusing'],
    ['state_id' => '08', 'code' => '31600', 'post_office_id' => 'Gopeng'],
    ['state_id' => '08', 'code' => '31610', 'post_office_id' => 'Gopeng'],
    ['state_id' => '08', 'code' => '31650', 'post_office_id' => 'Ipoh'],
    ['state_id' => '08', 'code' => '31700', 'post_office_id' => 'Malim Nawar'],
    ['state_id' => '08', 'code' => '31750', 'post_office_id' => 'Tronoh'],
    ['state_id' => '08', 'code' => '31800', 'post_office_id' => 'Tanjong Tualang'],
    ['state_id' => '08', 'code' => '31850', 'post_office_id' => 'Jeram'],
    ['state_id' => '08', 'code' => '31900', 'post_office_id' => 'Kampar'],
    ['state_id' => '08', 'code' => '31907', 'post_office_id' => 'Kampar'],
    ['state_id' => '08', 'code' => '31909', 'post_office_id' => 'Kampar'],
    ['state_id' => '08', 'code' => '31910', 'post_office_id' => 'Kampar'],
    ['state_id' => '08', 'code' => '31920', 'post_office_id' => 'Kampar'],
    ['state_id' => '08', 'code' => '31950', 'post_office_id' => 'Kampar'],
    ['state_id' => '08', 'code' => '32000', 'post_office_id' => 'Sitiawan'],
    ['state_id' => '08', 'code' => '32040', 'post_office_id' => 'Seri Manjung'],
    ['state_id' => '08', 'code' => '32100', 'post_office_id' => 'TLDM Lumut'],
    ['state_id' => '08', 'code' => '32200', 'post_office_id' => 'Lumut'],
    ['state_id' => '08', 'code' => '32300', 'post_office_id' => 'Pangkor'],
    ['state_id' => '08', 'code' => '32400', 'post_office_id' => 'Ayer Tawar'],
    ['state_id' => '08', 'code' => '32500', 'post_office_id' => 'Changkat Keruing'],
    ['state_id' => '08', 'code' => '32600', 'post_office_id' => 'Bota'],
    ['state_id' => '08', 'code' => '32610', 'post_office_id' => 'Bandar Seri Iskandar'],
    ['state_id' => '08', 'code' => '32700', 'post_office_id' => 'Bruas'],
    ['state_id' => '08', 'code' => '32800', 'post_office_id' => 'Parit'],
    ['state_id' => '08', 'code' => '32900', 'post_office_id' => 'Lambor Kanan'],
    ['state_id' => '08', 'code' => '33000', 'post_office_id' => 'Kuala Kangsar'],
    ['state_id' => '08', 'code' => '33007', 'post_office_id' => 'Kuala Kangsar'],
    ['state_id' => '08', 'code' => '33009', 'post_office_id' => 'Kuala Kangsar'],
    ['state_id' => '08', 'code' => '33010', 'post_office_id' => 'Kuala Kangsar'],
    ['state_id' => '08', 'code' => '33020', 'post_office_id' => 'Kuala Kangsar'],
    ['state_id' => '08', 'code' => '33030', 'post_office_id' => 'Kuala Kangsar'],
    ['state_id' => '08', 'code' => '33040', 'post_office_id' => 'Kuala Kangsar'],
    ['state_id' => '08', 'code' => '33100', 'post_office_id' => 'Pengkalan Hulu'],
    ['state_id' => '08', 'code' => '33200', 'post_office_id' => 'Intan'],
    ['state_id' => '08', 'code' => '33300', 'post_office_id' => 'Gerik'],
    ['state_id' => '08', 'code' => '33310', 'post_office_id' => 'Gerik'],
    ['state_id' => '08', 'code' => '33320', 'post_office_id' => 'Gerik'],
    ['state_id' => '08', 'code' => '33400', 'post_office_id' => 'Lenggong'],
    ['state_id' => '08', 'code' => '33410', 'post_office_id' => 'Lenggong'],
    ['state_id' => '08', 'code' => '33420', 'post_office_id' => 'Lenggong'],
    ['state_id' => '08', 'code' => '33500', 'post_office_id' => 'Sauk'],
    ['state_id' => '08', 'code' => '33600', 'post_office_id' => 'Enggor'],
    ['state_id' => '08', 'code' => '33700', 'post_office_id' => 'Padang Rengas'],
    ['state_id' => '08', 'code' => '33800', 'post_office_id' => 'Manong'],
    ['state_id' => '08', 'code' => '34000', 'post_office_id' => 'Taiping'],
    ['state_id' => '08', 'code' => '34007', 'post_office_id' => 'Taiping'],
    ['state_id' => '08', 'code' => '34008', 'post_office_id' => 'Taiping'],
    ['state_id' => '08', 'code' => '34009', 'post_office_id' => 'Taiping'],
    ['state_id' => '08', 'code' => '34010', 'post_office_id' => 'Taiping'],
    ['state_id' => '08', 'code' => '34020', 'post_office_id' => 'Taiping'],
    ['state_id' => '08', 'code' => '34030', 'post_office_id' => 'Taiping'],
    ['state_id' => '08', 'code' => '34100', 'post_office_id' => 'Selama'],
    ['state_id' => '08', 'code' => '34120', 'post_office_id' => 'Selama'],
    ['state_id' => '08', 'code' => '34130', 'post_office_id' => 'Selama'],
    ['state_id' => '08', 'code' => '34140', 'post_office_id' => 'Rantau Panjang'],
    ['state_id' => '08', 'code' => '34200', 'post_office_id' => 'Parit Buntar'],
    ['state_id' => '08', 'code' => '34250', 'post_office_id' => 'Tanjong Piandang'],
    ['state_id' => '08', 'code' => '34300', 'post_office_id' => 'Bagan Serai'],
    ['state_id' => '08', 'code' => '34310', 'post_office_id' => 'Bagan Serai'],
    ['state_id' => '08', 'code' => '34350', 'post_office_id' => 'Kuala Kurau'],
    ['state_id' => '08', 'code' => '34400', 'post_office_id' => 'Simpang Ampat Semanggol'],
    ['state_id' => '08', 'code' => '34500', 'post_office_id' => 'Batu Kurau'],
    ['state_id' => '08', 'code' => '34510', 'post_office_id' => 'Batu Kurau'],
    ['state_id' => '08', 'code' => '34520', 'post_office_id' => 'Batu Kurau'],
    ['state_id' => '08', 'code' => '34600', 'post_office_id' => 'Kamunting'],
    ['state_id' => '08', 'code' => '34650', 'post_office_id' => 'Kuala Sepetang'],
    ['state_id' => '08', 'code' => '34700', 'post_office_id' => 'Simpang'],
    ['state_id' => '08', 'code' => '34750', 'post_office_id' => 'Matang'],
    ['state_id' => '08', 'code' => '34800', 'post_office_id' => 'Trong'],
    ['state_id' => '08', 'code' => '34850', 'post_office_id' => 'Changkat Jering'],
    ['state_id' => '08', 'code' => '34900', 'post_office_id' => 'Pantai Remis'],
    ['state_id' => '08', 'code' => '35000', 'post_office_id' => 'Tapah'],
    ['state_id' => '08', 'code' => '35007', 'post_office_id' => 'Tapah'],
    ['state_id' => '08', 'code' => '35009', 'post_office_id' => 'Tapah'],
    ['state_id' => '08', 'code' => '35300', 'post_office_id' => 'Chenderiang'],
    ['state_id' => '08', 'code' => '35350', 'post_office_id' => 'Temoh'],
    ['state_id' => '08', 'code' => '35400', 'post_office_id' => 'Tapah Road'],
    ['state_id' => '08', 'code' => '35500', 'post_office_id' => 'Bidor'],
    ['state_id' => '08', 'code' => '35600', 'post_office_id' => 'Sungkai'],
    ['state_id' => '08', 'code' => '35700', 'post_office_id' => 'Trolak'],
    ['state_id' => '08', 'code' => '35800', 'post_office_id' => 'Slim River'],
    ['state_id' => '08', 'code' => '35820', 'post_office_id' => 'Slim River'],
    ['state_id' => '08', 'code' => '35900', 'post_office_id' => 'Tanjong Malim'],
    ['state_id' => '08', 'code' => '35907', 'post_office_id' => 'Tanjong Malim'],
    ['state_id' => '08', 'code' => '35909', 'post_office_id' => 'Tanjong Malim'],
    ['state_id' => '08', 'code' => '35910', 'post_office_id' => 'Tanjong Malim'],
    ['state_id' => '08', 'code' => '35950', 'post_office_id' => 'Behrang Stesen'],
    ['state_id' => '08', 'code' => '36000', 'post_office_id' => 'Teluk Intan'],
    ['state_id' => '08', 'code' => '36007', 'post_office_id' => 'Teluk Intan'],
    ['state_id' => '08', 'code' => '36008', 'post_office_id' => 'Teluk Intan'],
    ['state_id' => '08', 'code' => '36009', 'post_office_id' => 'Teluk Intan'],
    ['state_id' => '08', 'code' => '36010', 'post_office_id' => 'Teluk Intan'],
    ['state_id' => '08', 'code' => '36020', 'post_office_id' => 'Teluk Intan'],
    ['state_id' => '08', 'code' => '36030', 'post_office_id' => 'Teluk Intan'],
    ['state_id' => '08', 'code' => '36100', 'post_office_id' => 'Bagan Datoh'],
    ['state_id' => '08', 'code' => '36110', 'post_office_id' => 'Teluk Intan'],
    ['state_id' => '08', 'code' => '36200', 'post_office_id' => 'Selekoh'],
    ['state_id' => '08', 'code' => '36207', 'post_office_id' => 'Selekoh'],
    ['state_id' => '08', 'code' => '36209', 'post_office_id' => 'Selekoh'],
    ['state_id' => '08', 'code' => '36300', 'post_office_id' => 'Sungai Sumun'],
    ['state_id' => '08', 'code' => '36307', 'post_office_id' => 'Sungai Sumun'],
    ['state_id' => '08', 'code' => '36309', 'post_office_id' => 'Sungai Sumun'],
    ['state_id' => '08', 'code' => '36400', 'post_office_id' => 'Hutan Melintang'],
    ['state_id' => '08', 'code' => '36500', 'post_office_id' => 'Ulu Bernam'],
    ['state_id' => '08', 'code' => '36600', 'post_office_id' => 'Chenderong Balai'],
    ['state_id' => '08', 'code' => '36700', 'post_office_id' => 'Langkap'],
    ['state_id' => '08', 'code' => '36750', 'post_office_id' => 'Chikus'],
    ['state_id' => '08', 'code' => '36800', 'post_office_id' => 'Kampung Gajah'],
    ['state_id' => '08', 'code' => '36810', 'post_office_id' => 'Kampung Gajah'],
];