<?php

$data = [
    ['state_id' => '09', 'code' => '01000', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01007', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01009', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01500', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01502', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01503', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01504', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01505', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01506', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01508', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01512', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01514', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01516', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01517', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01518', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01524', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01529', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01532', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01538', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01540', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01546', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01550', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01551', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01556', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01560', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01564', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01570', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01572', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01576', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01578', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01582', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01586', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01590', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01592', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01594', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01596', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01598', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01600', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01604', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01606', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01608', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01609', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01610', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01612', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01614', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01620', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01622', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01626', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01628', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01630', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01632', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01634', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01644', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01646', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01648', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01660', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01664', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01670', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01672', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01673', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01674', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01676', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01680', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '01694', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '02000', 'post_office_id' => 'Kuala Perlis'],
    ['state_id' => '09', 'code' => '02100', 'post_office_id' => 'Padang Besar'],
    ['state_id' => '09', 'code' => '02200', 'post_office_id' => 'Kaki Bukit'],
    ['state_id' => '09', 'code' => '02400', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '02450', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '02500', 'post_office_id' => 'Kangar'],
    ['state_id' => '09', 'code' => '02600', 'post_office_id' => 'Arau'],
    ['state_id' => '09', 'code' => '02607', 'post_office_id' => 'Arau'],
    ['state_id' => '09', 'code' => '02609', 'post_office_id' => 'Arau'],
    ['state_id' => '09', 'code' => '02700', 'post_office_id' => 'Simpang Ampat'],
    ['state_id' => '09', 'code' => '02707', 'post_office_id' => 'Simpang Ampat'],
    ['state_id' => '09', 'code' => '02709', 'post_office_id' => 'Simpang Ampat'],
    ['state_id' => '09', 'code' => '02800', 'post_office_id' => 'Simpang Ampat'],
];