<?php

$data = [
    ['state_id' => '07', 'code' => '10000', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10050', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10100', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10150', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10200', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10250', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10300', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10350', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10400', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10450', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10460', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10470', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10500', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10502', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10503', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10504', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10505', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10506', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10508', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10512', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10514', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10516', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10518', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10524', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10534', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10538', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10540', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10542', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10546', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10550', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10551', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10552', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10558', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10560', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10564', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10566', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10570', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10576', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10578', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10582', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10590', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10592', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10593', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10594', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10596', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10600', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10604', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10609', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10610', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10612', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10620', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10622', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10626', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10628', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10634', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10646', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10648', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10660', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10661', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10662', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10670', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10672', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10673', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10674', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10676', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10690', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10710', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10720', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10730', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10740', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10750', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10760', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10770', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10780', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10790', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10800', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10810', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10820', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10830', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10840', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10850', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10910', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10920', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '10990', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '11000', 'post_office_id' => 'Balik Pulau'],
    ['state_id' => '07', 'code' => '11010', 'post_office_id' => 'Balik Pulau'],
    ['state_id' => '07', 'code' => '11020', 'post_office_id' => 'Balik Pulau'],
    ['state_id' => '07', 'code' => '11050', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '11060', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '11100', 'post_office_id' => 'Batu Ferringhi'],
    ['state_id' => '07', 'code' => '11200', 'post_office_id' => 'Tanjong Bungah'],
    ['state_id' => '07', 'code' => '11300', 'post_office_id' => 'Penang Hill'],
    ['state_id' => '07', 'code' => '11400', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '11409', 'post_office_id' => 'Pulau Pinang'],
    ['state_id' => '07', 'code' => '11500', 'post_office_id' => 'Ayer Itam'],
    ['state_id' => '07', 'code' => '11600', 'post_office_id' => 'Jelutong'],
    ['state_id' => '07', 'code' => '11609', 'post_office_id' => 'Jelutong'],
    ['state_id' => '07', 'code' => '11700', 'post_office_id' => 'Gelugor'],
    ['state_id' => '07', 'code' => '11800', 'post_office_id' => 'USM Pulau Pinang'],
    ['state_id' => '07', 'code' => '11900', 'post_office_id' => 'Bayan Lepas'],
    ['state_id' => '07', 'code' => '11910', 'post_office_id' => 'Bayan Lepas'],
    ['state_id' => '07', 'code' => '11920', 'post_office_id' => 'Bayan Lepas'],
    ['state_id' => '07', 'code' => '11950', 'post_office_id' => 'Bayan Lepas'],
    ['state_id' => '07', 'code' => '11960', 'post_office_id' => 'Batu Maung'],
    ['state_id' => '07', 'code' => '12000', 'post_office_id' => 'Butterworth'],
    ['state_id' => '07', 'code' => '12100', 'post_office_id' => 'Butterworth'],
    ['state_id' => '07', 'code' => '12200', 'post_office_id' => 'Butterworth'],
    ['state_id' => '07', 'code' => '12300', 'post_office_id' => 'Butterworth'],
    ['state_id' => '07', 'code' => '12700', 'post_office_id' => 'Butterworth'],
    ['state_id' => '07', 'code' => '12710', 'post_office_id' => 'Butterworth'],
    ['state_id' => '07', 'code' => '12720', 'post_office_id' => 'Butterworth'],
    ['state_id' => '07', 'code' => '12990', 'post_office_id' => 'Butterworth'],
    ['state_id' => '07', 'code' => '13000', 'post_office_id' => 'Butterworth'],
    ['state_id' => '07', 'code' => '13009', 'post_office_id' => 'Butterworth'],
    ['state_id' => '07', 'code' => '13020', 'post_office_id' => 'Butterworth'],
    ['state_id' => '07', 'code' => '13050', 'post_office_id' => 'Butterworth'],
    ['state_id' => '07', 'code' => '13100', 'post_office_id' => 'Penaga'],
    ['state_id' => '07', 'code' => '13110', 'post_office_id' => 'Penaga'],
    ['state_id' => '07', 'code' => '13200', 'post_office_id' => 'Kepala Batas'],
    ['state_id' => '07', 'code' => '13210', 'post_office_id' => 'Kepala Batas'],
    ['state_id' => '07', 'code' => '13220', 'post_office_id' => 'Kepala Batas'],
    ['state_id' => '07', 'code' => '13300', 'post_office_id' => 'Tasek Gelugor'],
    ['state_id' => '07', 'code' => '13310', 'post_office_id' => 'Tasek Gelugor'],
    ['state_id' => '07', 'code' => '13400', 'post_office_id' => 'Butterworth'],
    ['state_id' => '07', 'code' => '13409', 'post_office_id' => 'Butterworth'],
    ['state_id' => '07', 'code' => '13500', 'post_office_id' => 'Permatang Pauh'],
    ['state_id' => '07', 'code' => '13600', 'post_office_id' => 'Perai'],
    ['state_id' => '07', 'code' => '13700', 'post_office_id' => 'Perai'],
    ['state_id' => '07', 'code' => '13800', 'post_office_id' => 'Butterworth'],
    ['state_id' => '07', 'code' => '14000', 'post_office_id' => 'Bukit Mertajam'],
    ['state_id' => '07', 'code' => '14007', 'post_office_id' => 'Bukit Mertajam'],
    ['state_id' => '07', 'code' => '14009', 'post_office_id' => 'Bukit Mertajam'],
    ['state_id' => '07', 'code' => '14020', 'post_office_id' => 'Bukit Mertajam'],
    ['state_id' => '07', 'code' => '14100', 'post_office_id' => 'Simpang Ampat'],
    ['state_id' => '07', 'code' => '14101', 'post_office_id' => 'Simpang Ampat'],
    ['state_id' => '07', 'code' => '14110', 'post_office_id' => 'Simpang Ampat'],
    ['state_id' => '07', 'code' => '14120', 'post_office_id' => 'Simpang Ampat'],
    ['state_id' => '07', 'code' => '14200', 'post_office_id' => 'Sungai Jawi'],
    ['state_id' => '07', 'code' => '14300', 'post_office_id' => 'Nibong Tebal'],
    ['state_id' => '07', 'code' => '14310', 'post_office_id' => 'Nibong Tebal'],
    ['state_id' => '07', 'code' => '14320', 'post_office_id' => 'Nibong Tebal'],
    ['state_id' => '07', 'code' => '14400', 'post_office_id' => 'Kubang Semang'],
];