<?php

$data = [
    ['state_id' => '12', 'code' => '88000', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88100', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88200', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88300', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88400', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88450', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88460', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88500', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88502', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88504', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88505', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88506', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88508', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88510', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88512', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88514', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88516', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88518', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88520', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88526', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88527', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88532', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88534', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88538', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88540', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88546', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88550', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88551', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88552', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88554', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88556', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88558', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88560', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88562', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88564', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88566', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88568', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88570', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88572', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88576', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88580', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88582', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88586', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88590', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88592', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88594', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88596', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88598', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88600', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88602', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88604', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88606', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88608', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88609', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88610', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88612', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88614', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88617', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88618', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88620', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88621', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88622', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88624', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88626', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88628', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88630', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88632', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88634', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88644', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88646', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88648', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88656', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88658', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88660', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88661', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88662', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88670', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88672', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88673', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88675', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88676', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88680', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88690', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88700', 'post_office_id' => 'Beverly'],
    ['state_id' => '12', 'code' => '88721', 'post_office_id' => 'Putatan'],
    ['state_id' => '12', 'code' => '88722', 'post_office_id' => 'Putatan'],
    ['state_id' => '12', 'code' => '88723', 'post_office_id' => 'Putatan'],
    ['state_id' => '12', 'code' => '88724', 'post_office_id' => 'Putatan'],
    ['state_id' => '12', 'code' => '88725', 'post_office_id' => 'Putatan'],
    ['state_id' => '12', 'code' => '88757', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88758', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88759', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88760', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88761', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88762', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88763', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88764', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88765', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88766', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88767', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88768', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88769', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88770', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88771', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88772', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88773', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88774', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88775', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88776', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88777', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88778', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88779', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88780', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88781', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88782', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88783', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88784', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88785', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88786', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88787', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88788', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88789', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88790', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88800', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88801', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88802', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88803', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88804', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88805', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88806', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88807', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88808', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88809', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88810', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88811', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88812', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88813', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88814', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88815', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88816', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88817', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88818', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88819', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88820', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88821', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88822', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88823', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88824', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88825', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88826', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88827', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88828', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88829', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88830', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88831', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88832', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88833', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88834', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88835', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88836', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88837', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88838', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88839', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88840', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88841', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88842', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88843', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88844', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88845', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88846', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88847', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88848', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88849', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88850', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88851', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88852', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88853', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88854', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88855', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88856', 'post_office_id' => 'Likas'],
    ['state_id' => '12', 'code' => '88857', 'post_office_id' => 'Inanam'],
    ['state_id' => '12', 'code' => '88858', 'post_office_id' => 'Tanjung Aru'],
    ['state_id' => '12', 'code' => '88860', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88861', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88862', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88863', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88865', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88866', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88867', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88868', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88869', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88870', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88871', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88872', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88873', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88874', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88875', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88900', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88901', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88902', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88903', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88904', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88905', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88906', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88988', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88990', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88991', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88992', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88993', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88994', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88995', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88996', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88997', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88998', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '88999', 'post_office_id' => 'Kota Kinabalu'],
    ['state_id' => '12', 'code' => '89000', 'post_office_id' => 'Keningau'],
    ['state_id' => '12', 'code' => '89007', 'post_office_id' => 'Keningau'],
    ['state_id' => '12', 'code' => '89008', 'post_office_id' => 'Keningau'],
    ['state_id' => '12', 'code' => '89009', 'post_office_id' => 'Keningau'],
    ['state_id' => '12', 'code' => '89050', 'post_office_id' => 'Kudat'],
    ['state_id' => '12', 'code' => '89057', 'post_office_id' => 'Kudat'],
    ['state_id' => '12', 'code' => '89058', 'post_office_id' => 'Kudat'],
    ['state_id' => '12', 'code' => '89059', 'post_office_id' => 'Kudat'],
    ['state_id' => '12', 'code' => '89100', 'post_office_id' => 'Kota Marudu'],
    ['state_id' => '12', 'code' => '89107', 'post_office_id' => 'Kota Marudu'],
    ['state_id' => '12', 'code' => '89108', 'post_office_id' => 'Kota Marudu'],
    ['state_id' => '12', 'code' => '89109', 'post_office_id' => 'Kota Marudu'],
    ['state_id' => '12', 'code' => '89130', 'post_office_id' => 'Kota Marudu'],
    ['state_id' => '12', 'code' => '89137', 'post_office_id' => 'Kota Marudu'],
    ['state_id' => '12', 'code' => '89138', 'post_office_id' => 'Kota Marudu'],
    ['state_id' => '12', 'code' => '89139', 'post_office_id' => 'Kota Marudu'],
    ['state_id' => '12', 'code' => '89150', 'post_office_id' => 'Kota Belud'],
    ['state_id' => '12', 'code' => '89157', 'post_office_id' => 'Kota Belud'],
    ['state_id' => '12', 'code' => '89158', 'post_office_id' => 'Kota Belud'],
    ['state_id' => '12', 'code' => '89159', 'post_office_id' => 'Kota Belud'],
    ['state_id' => '12', 'code' => '89200', 'post_office_id' => 'Tuaran'],
    ['state_id' => '12', 'code' => '89207', 'post_office_id' => 'Tuaran'],
    ['state_id' => '12', 'code' => '89208', 'post_office_id' => 'Tuaran'],
    ['state_id' => '12', 'code' => '89209', 'post_office_id' => 'Tuaran'],
    ['state_id' => '12', 'code' => '89250', 'post_office_id' => 'Tamparuli'],
    ['state_id' => '12', 'code' => '89257', 'post_office_id' => 'Tamparuli'],
    ['state_id' => '12', 'code' => '89258', 'post_office_id' => 'Tamparuli'],
    ['state_id' => '12', 'code' => '89259', 'post_office_id' => 'Tamparuli'],
    ['state_id' => '12', 'code' => '89260', 'post_office_id' => 'Tenghilan'],
    ['state_id' => '12', 'code' => '89300', 'post_office_id' => 'Ranau'],
    ['state_id' => '12', 'code' => '89307', 'post_office_id' => 'Ranau'],
    ['state_id' => '12', 'code' => '89308', 'post_office_id' => 'Ranau'],
    ['state_id' => '12', 'code' => '89309', 'post_office_id' => 'Ranau'],
    ['state_id' => '12', 'code' => '89320', 'post_office_id' => 'Ranau'],
    ['state_id' => '12', 'code' => '89327', 'post_office_id' => 'Ranau'],
    ['state_id' => '12', 'code' => '89328', 'post_office_id' => 'Ranau'],
    ['state_id' => '12', 'code' => '89329', 'post_office_id' => 'Ranau'],
    ['state_id' => '12', 'code' => '89330', 'post_office_id' => 'Ranau'],
    ['state_id' => '12', 'code' => '89337', 'post_office_id' => 'Ranau'],
    ['state_id' => '12', 'code' => '89338', 'post_office_id' => 'Ranau'],
    ['state_id' => '12', 'code' => '89339', 'post_office_id' => 'Ranau'],
    ['state_id' => '12', 'code' => '89500', 'post_office_id' => 'Penampang'],
    ['state_id' => '12', 'code' => '89507', 'post_office_id' => 'Penampang'],
    ['state_id' => '12', 'code' => '89508', 'post_office_id' => 'Penampang'],
    ['state_id' => '12', 'code' => '89509', 'post_office_id' => 'Penampang'],
    ['state_id' => '12', 'code' => '89600', 'post_office_id' => 'Papar'],
    ['state_id' => '12', 'code' => '89607', 'post_office_id' => 'Papar'],
    ['state_id' => '12', 'code' => '89608', 'post_office_id' => 'Papar'],
    ['state_id' => '12', 'code' => '89609', 'post_office_id' => 'Papar'],
    ['state_id' => '12', 'code' => '89650', 'post_office_id' => 'Tambunan'],
    ['state_id' => '12', 'code' => '89657', 'post_office_id' => 'Tambunan'],
    ['state_id' => '12', 'code' => '89658', 'post_office_id' => 'Tambunan'],
    ['state_id' => '12', 'code' => '89659', 'post_office_id' => 'Tambunan'],
    ['state_id' => '12', 'code' => '89700', 'post_office_id' => 'Bongawan'],
    ['state_id' => '12', 'code' => '89707', 'post_office_id' => 'Bongawan'],
    ['state_id' => '12', 'code' => '89708', 'post_office_id' => 'Bongawan'],
    ['state_id' => '12', 'code' => '89709', 'post_office_id' => 'Bongawan'],
    ['state_id' => '12', 'code' => '89720', 'post_office_id' => 'Membakut'],
    ['state_id' => '12', 'code' => '89727', 'post_office_id' => 'Membakut'],
    ['state_id' => '12', 'code' => '89728', 'post_office_id' => 'Membakut'],
    ['state_id' => '12', 'code' => '89729', 'post_office_id' => 'Membakut'],
    ['state_id' => '12', 'code' => '89740', 'post_office_id' => 'Kuala Penyu'],
    ['state_id' => '12', 'code' => '89747', 'post_office_id' => 'Kuala Penyu'],
    ['state_id' => '12', 'code' => '89748', 'post_office_id' => 'Kuala Penyu'],
    ['state_id' => '12', 'code' => '89749', 'post_office_id' => 'Kuala Penyu'],
    ['state_id' => '12', 'code' => '89760', 'post_office_id' => 'Menumbok'],
    ['state_id' => '12', 'code' => '89767', 'post_office_id' => 'Menumbok'],
    ['state_id' => '12', 'code' => '89768', 'post_office_id' => 'Menumbok'],
    ['state_id' => '12', 'code' => '89769', 'post_office_id' => 'Menumbok'],
    ['state_id' => '12', 'code' => '89800', 'post_office_id' => 'Beaufort'],
    ['state_id' => '12', 'code' => '89807', 'post_office_id' => 'Beaufort'],
    ['state_id' => '12', 'code' => '89808', 'post_office_id' => 'Beaufort'],
    ['state_id' => '12', 'code' => '89809', 'post_office_id' => 'Beaufort'],
    ['state_id' => '12', 'code' => '89850', 'post_office_id' => 'Sipitang'],
    ['state_id' => '12', 'code' => '89857', 'post_office_id' => 'Sipitang'],
    ['state_id' => '12', 'code' => '89858', 'post_office_id' => 'Sipitang'],
    ['state_id' => '12', 'code' => '89859', 'post_office_id' => 'Sipitang'],
    ['state_id' => '12', 'code' => '89900', 'post_office_id' => 'Tenom'],
    ['state_id' => '12', 'code' => '89907', 'post_office_id' => 'Tenom'],
    ['state_id' => '12', 'code' => '89908', 'post_office_id' => 'Tenom'],
    ['state_id' => '12', 'code' => '89909', 'post_office_id' => 'Tenom'],
    ['state_id' => '12', 'code' => '89950', 'post_office_id' => 'Nabawan'],
    ['state_id' => '12', 'code' => '89957', 'post_office_id' => 'Nabawan'],
    ['state_id' => '12', 'code' => '89958', 'post_office_id' => 'Nabawan'],
    ['state_id' => '12', 'code' => '89959', 'post_office_id' => 'Nabawan'],
    ['state_id' => '12', 'code' => '90000', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90009', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90100', 'post_office_id' => 'Beluran'],
    ['state_id' => '12', 'code' => '90107', 'post_office_id' => 'Beluran'],
    ['state_id' => '12', 'code' => '90109', 'post_office_id' => 'Beluran'],
    ['state_id' => '12', 'code' => '90200', 'post_office_id' => 'Kota Kinabatangan'],
    ['state_id' => '12', 'code' => '90300', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90307', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90400', 'post_office_id' => 'Pamol'],
    ['state_id' => '12', 'code' => '90700', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90701', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90702', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90703', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90704', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90705', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90706', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90707', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90708', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90709', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90711', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90712', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90713', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90714', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90715', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90716', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90717', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90718', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90719', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90720', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90721', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90722', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90723', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90724', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90725', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90726', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90727', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90728', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90729', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90730', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90731', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90732', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90733', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90734', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90735', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90736', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90737', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90738', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90739', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90740', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '90741', 'post_office_id' => 'Sandakan'],
    ['state_id' => '12', 'code' => '91000', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91007', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91008', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91009', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91010', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91011', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91012', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91013', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91014', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91015', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91016', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91017', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91018', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91019', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91020', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91021', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91022', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91023', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91024', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91025', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91026', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91027', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91028', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91029', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91030', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91031', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91032', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91033', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91034', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91035', 'post_office_id' => 'Tawau'],
    ['state_id' => '12', 'code' => '91100', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91109', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91110', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91111', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91112', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91113', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91114', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91115', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91116', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91117', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91118', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91119', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91120', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91121', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91122', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91123', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91124', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91125', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91126', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91127', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91128', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91150', 'post_office_id' => 'Lahad Datu'],
    ['state_id' => '12', 'code' => '91200', 'post_office_id' => 'Kunak'],
    ['state_id' => '12', 'code' => '91207', 'post_office_id' => 'Kunak'],
    ['state_id' => '12', 'code' => '91209', 'post_office_id' => 'Kunak'],
    ['state_id' => '12', 'code' => '91300', 'post_office_id' => 'Semporna'],
    ['state_id' => '12', 'code' => '91307', 'post_office_id' => 'Semporna'],
    ['state_id' => '12', 'code' => '91308', 'post_office_id' => 'Semporna'],
    ['state_id' => '12', 'code' => '91309', 'post_office_id' => 'Semporna'],
];