<?php

$data = [
    ['state_id' => '10', 'code' => '40000', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40100', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40150', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40160', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40170', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40200', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40300', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40400', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40450', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40460', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40470', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40500', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40502', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40503', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40505', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40512', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40517', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40520', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40529', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40542', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40548', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40550', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40551', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40560', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40564', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40570', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40572', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40576', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40578', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40582', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40590', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40592', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40594', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40596', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40598', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40604', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40607', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40608', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40610', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40612', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40620', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40622', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40626', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40632', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40646', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40648', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40660', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40664', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40670', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40672', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40673', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40674', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40675', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40676', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40680', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40690', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40700', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40702', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40704', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40706', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40708', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40710', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40712', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40714', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40716', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40718', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40720', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40722', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40724', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40726', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40728', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40730', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40732', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40800', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40802', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40804', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40806', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40808', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40810', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '40990', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '41000', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41050', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41100', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41150', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41200', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41250', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41300', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41400', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41506', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41560', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41586', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41672', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41700', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41710', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41720', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41900', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41902', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41904', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41906', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41908', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41910', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41912', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41914', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41916', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41918', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '41990', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '42000', 'post_office_id' => 'Pelabuhan Klang'],
    ['state_id' => '10', 'code' => '42009', 'post_office_id' => 'Pelabuhan Klang'],
    ['state_id' => '10', 'code' => '42100', 'post_office_id' => 'Klang'],
    ['state_id' => '10', 'code' => '42200', 'post_office_id' => 'Kapar'],
    ['state_id' => '10', 'code' => '42300', 'post_office_id' => 'Bandar Puncak Alam'],
    ['state_id' => '10', 'code' => '42425', 'post_office_id' => 'Telok Panglima Garang'],
    ['state_id' => '10', 'code' => '42500', 'post_office_id' => 'Telok Panglima Garang'],
    ['state_id' => '10', 'code' => '42507', 'post_office_id' => 'Telok Panglima Garang'],
    ['state_id' => '10', 'code' => '42509', 'post_office_id' => 'Telok Panglima Garang'],
    ['state_id' => '10', 'code' => '42600', 'post_office_id' => 'Jenjarom'],
    ['state_id' => '10', 'code' => '42610', 'post_office_id' => 'Jenjarom'],
    ['state_id' => '10', 'code' => '42700', 'post_office_id' => 'Banting'],
    ['state_id' => '10', 'code' => '42800', 'post_office_id' => 'Tanjong Sepat'],
    ['state_id' => '10', 'code' => '42920', 'post_office_id' => 'Pulau Indah'],
    ['state_id' => '10', 'code' => '42940', 'post_office_id' => 'Pulau Ketam'],
    ['state_id' => '10', 'code' => '42960', 'post_office_id' => 'Pulau Carey'],
    ['state_id' => '10', 'code' => '43000', 'post_office_id' => 'Kajang'],
    ['state_id' => '10', 'code' => '43007', 'post_office_id' => 'Kajang'],
    ['state_id' => '10', 'code' => '43009', 'post_office_id' => 'Kajang'],
    ['state_id' => '10', 'code' => '43100', 'post_office_id' => 'Hulu Langat'],
    ['state_id' => '10', 'code' => '43200', 'post_office_id' => 'Cheras'],
    ['state_id' => '10', 'code' => '43207', 'post_office_id' => 'Cheras'],
    ['state_id' => '10', 'code' => '43300', 'post_office_id' => 'Seri Kembangan'],
    ['state_id' => '10', 'code' => '43400', 'post_office_id' => 'Serdang'],
    ['state_id' => '10', 'code' => '43500', 'post_office_id' => 'Semenyih'],
    ['state_id' => '10', 'code' => '43558', 'post_office_id' => 'Kajang'],
    ['state_id' => '10', 'code' => '43600', 'post_office_id' => 'Bandar Baru Bangi'],
    ['state_id' => '10', 'code' => '43650', 'post_office_id' => 'Bandar Baru Bangi'],
    ['state_id' => '10', 'code' => '43700', 'post_office_id' => 'Beranang'],
    ['state_id' => '10', 'code' => '43800', 'post_office_id' => 'Dengkil'],
    ['state_id' => '10', 'code' => '43807', 'post_office_id' => 'Dengkil'],
    ['state_id' => '10', 'code' => '43900', 'post_office_id' => 'Sepang'],
    ['state_id' => '10', 'code' => '43950', 'post_office_id' => 'Sungai Pelek'],
    ['state_id' => '10', 'code' => '44000', 'post_office_id' => 'Kuala Kubu Baru'],
    ['state_id' => '10', 'code' => '44010', 'post_office_id' => 'Kuala Kubu Baru'],
    ['state_id' => '10', 'code' => '44020', 'post_office_id' => 'Kuala Kubu Baru'],
    ['state_id' => '10', 'code' => '44100', 'post_office_id' => 'Kerling'],
    ['state_id' => '10', 'code' => '44110', 'post_office_id' => 'Kuala Kubu Baru'],
    ['state_id' => '10', 'code' => '44200', 'post_office_id' => 'Rasa'],
    ['state_id' => '10', 'code' => '44300', 'post_office_id' => 'Batang Kali'],
    ['state_id' => '10', 'code' => '45000', 'post_office_id' => 'Kuala Selangor'],
    ['state_id' => '10', 'code' => '45100', 'post_office_id' => 'Sungai Ayer Tawar'],
    ['state_id' => '10', 'code' => '45200', 'post_office_id' => 'Sabak Bernam'],
    ['state_id' => '10', 'code' => '45207', 'post_office_id' => 'Sabak Bernam'],
    ['state_id' => '10', 'code' => '45209', 'post_office_id' => 'Sabak Bernam'],
    ['state_id' => '10', 'code' => '45300', 'post_office_id' => 'Sungai Besar'],
    ['state_id' => '10', 'code' => '45400', 'post_office_id' => 'Sekinchan'],
    ['state_id' => '10', 'code' => '45500', 'post_office_id' => 'Tanjong Karang'],
    ['state_id' => '10', 'code' => '45600', 'post_office_id' => 'Bestari Jaya'],
    ['state_id' => '10', 'code' => '45607', 'post_office_id' => 'Bestari Jaya'],
    ['state_id' => '10', 'code' => '45609', 'post_office_id' => 'Bestari Jaya'],
    ['state_id' => '10', 'code' => '45620', 'post_office_id' => 'Bestari Jaya'],
    ['state_id' => '10', 'code' => '45700', 'post_office_id' => 'Bukit Rotan'],
    ['state_id' => '10', 'code' => '45800', 'post_office_id' => 'Jeram'],
    ['state_id' => '10', 'code' => '46000', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46050', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46100', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46150', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46200', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46300', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46350', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46400', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46506', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46547', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46549', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46551', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46564', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46582', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46598', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46662', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46667', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46668', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46672', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46675', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46700', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46710', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46720', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46730', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46740', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46750', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46760', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46770', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46780', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46781', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46782', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46783', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46784', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46785', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46786', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46787', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46788', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46789', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46790', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46791', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46792', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46793', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46794', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46795', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46796', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46797', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46798', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46799', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46800', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46801', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46802', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46803', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46804', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46805', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46806', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46860', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46870', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46960', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46962', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46964', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46966', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46968', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46970', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46972', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46974', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46976', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '46978', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '47000', 'post_office_id' => 'Sungai Buloh'],
    ['state_id' => '10', 'code' => '47100', 'post_office_id' => 'Puchong'],
    ['state_id' => '10', 'code' => '47110', 'post_office_id' => 'Puchong'],
    ['state_id' => '10', 'code' => '47120', 'post_office_id' => 'Puchong'],
    ['state_id' => '10', 'code' => '47130', 'post_office_id' => 'Puchong'],
    ['state_id' => '10', 'code' => '47140', 'post_office_id' => 'Puchong'],
    ['state_id' => '10', 'code' => '47150', 'post_office_id' => 'Puchong'],
    ['state_id' => '10', 'code' => '47160', 'post_office_id' => 'Puchong'],
    ['state_id' => '10', 'code' => '47170', 'post_office_id' => 'Puchong'],
    ['state_id' => '10', 'code' => '47180', 'post_office_id' => 'Puchong'],
    ['state_id' => '10', 'code' => '47190', 'post_office_id' => 'Puchong'],
    ['state_id' => '10', 'code' => '47200', 'post_office_id' => 'Subang Jaya'],
    ['state_id' => '10', 'code' => '47300', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '47301', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '47307', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '47308', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '47400', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '47410', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '47500', 'post_office_id' => 'Subang Jaya'],
    ['state_id' => '10', 'code' => '47507', 'post_office_id' => 'Subang Jaya'],
    ['state_id' => '10', 'code' => '47600', 'post_office_id' => 'Subang Jaya'],
    ['state_id' => '10', 'code' => '47610', 'post_office_id' => 'Subang Jaya'],
    ['state_id' => '10', 'code' => '47620', 'post_office_id' => 'Subang Jaya'],
    ['state_id' => '10', 'code' => '47630', 'post_office_id' => 'Subang Jaya'],
    ['state_id' => '10', 'code' => '47640', 'post_office_id' => 'Subang Jaya'],
    ['state_id' => '10', 'code' => '47650', 'post_office_id' => 'Subang Jaya'],
    ['state_id' => '10', 'code' => '47800', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '47810', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '47820', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '47830', 'post_office_id' => 'Petaling Jaya'],
    ['state_id' => '10', 'code' => '48000', 'post_office_id' => 'Rawang'],
    ['state_id' => '10', 'code' => '48010', 'post_office_id' => 'Rawang'],
    ['state_id' => '10', 'code' => '48020', 'post_office_id' => 'Rawang'],
    ['state_id' => '10', 'code' => '48050', 'post_office_id' => 'Rawang'],
    ['state_id' => '10', 'code' => '48100', 'post_office_id' => 'Batu Arang'],
    ['state_id' => '10', 'code' => '48200', 'post_office_id' => 'Serendah'],
    ['state_id' => '10', 'code' => '48300', 'post_office_id' => 'Rawang'],
    ['state_id' => '10', 'code' => '63000', 'post_office_id' => 'Cyberjaya'],
    ['state_id' => '10', 'code' => '63100', 'post_office_id' => 'Cyberjaya'],
    ['state_id' => '10', 'code' => '63200', 'post_office_id' => 'Cyberjaya'],
    ['state_id' => '10', 'code' => '63300', 'post_office_id' => 'Cyberjaya'],
    ['state_id' => '10', 'code' => '64000', 'post_office_id' => 'KLIA'],
    ['state_id' => '10', 'code' => '68000', 'post_office_id' => 'Ampang'],
    ['state_id' => '10', 'code' => '68100', 'post_office_id' => 'Batu Caves'],
    ['state_id' => '10', 'code' => '40160', 'post_office_id' => 'Shah Alam'],
    ['state_id' => '10', 'code' => '43000', 'post_office_id' => 'Kajang'],
    ['state_id' => '10', 'code' => '47120', 'post_office_id' => 'Puchong'],
];