<?php

$data = [
    ['state_id' => '11', 'code' => '20000', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20050', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20100', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20200', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20300', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20400', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20500', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20502', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20503', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20504', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20505', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20506', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20508', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20512', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20514', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20516', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20517', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20518', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20519', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20520', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20532', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20534', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20536', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20538', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20540', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20542', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20546', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20548', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20550', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20551', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20552', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20554', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20556', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20560', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20564', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20566', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20568', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20570', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20572', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20576', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20578', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20582', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20586', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20590', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20592', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20596', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20600', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20604', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20606', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20608', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20609', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20610', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20612', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20614', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20618', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20620', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20622', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20626', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20628', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20630', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20632', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20646', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20648', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20656', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20658', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20660', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20661', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20662', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20664', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20668', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20670', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20672', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20673', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20674', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20676', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20680', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20690', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20698', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20700', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20710', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20720', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20900', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20902', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20904', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20906', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20908', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20910', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20912', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20914', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20916', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20918', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20920', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20922', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20924', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20926', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20928', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20930', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '20990', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '21000', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '21009', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '21010', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '21020', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '21030', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '21040', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '21060', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '21070', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '21080', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '21090', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '21100', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '21109', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '21200', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '21209', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '21210', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '21220', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '21300', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '21309', 'post_office_id' => 'Kuala Terengganu'],
    ['state_id' => '11', 'code' => '21400', 'post_office_id' => 'Bukit Payong'],
    ['state_id' => '11', 'code' => '21450', 'post_office_id' => 'Chalok'],
    ['state_id' => '11', 'code' => '21500', 'post_office_id' => 'Sungai Tong'],
    ['state_id' => '11', 'code' => '21600', 'post_office_id' => 'Marang'],
    ['state_id' => '11', 'code' => '21610', 'post_office_id' => 'Marang'],
    ['state_id' => '11', 'code' => '21700', 'post_office_id' => 'Kuala Berang'],
    ['state_id' => '11', 'code' => '21800', 'post_office_id' => 'Ajil'],
    ['state_id' => '11', 'code' => '21810', 'post_office_id' => 'Ajil'],
    ['state_id' => '11', 'code' => '21820', 'post_office_id' => 'Ajil'],
    ['state_id' => '11', 'code' => '22000', 'post_office_id' => 'Jerteh'],
    ['state_id' => '11', 'code' => '22010', 'post_office_id' => 'Jerteh'],
    ['state_id' => '11', 'code' => '22020', 'post_office_id' => 'Jerteh'],
    ['state_id' => '11', 'code' => '22100', 'post_office_id' => 'Permaisuri'],
    ['state_id' => '11', 'code' => '22107', 'post_office_id' => 'Permaisuri'],
    ['state_id' => '11', 'code' => '22109', 'post_office_id' => 'Permaisuri'],
    ['state_id' => '11', 'code' => '22110', 'post_office_id' => 'Permaisuri'],
    ['state_id' => '11', 'code' => '22120', 'post_office_id' => 'Permaisuri'],
    ['state_id' => '11', 'code' => '22200', 'post_office_id' => 'Kampung Raja'],
    ['state_id' => '11', 'code' => '22300', 'post_office_id' => 'Kuala Besut'],
    ['state_id' => '11', 'code' => '22307', 'post_office_id' => 'Kuala Besut'],
    ['state_id' => '11', 'code' => '22309', 'post_office_id' => 'Kuala Besut'],
    ['state_id' => '11', 'code' => '23000', 'post_office_id' => 'Dungun'],
    ['state_id' => '11', 'code' => '23007', 'post_office_id' => 'Dungun'],
    ['state_id' => '11', 'code' => '23009', 'post_office_id' => 'Dungun'],
    ['state_id' => '11', 'code' => '23050', 'post_office_id' => 'Dungun'],
    ['state_id' => '11', 'code' => '23100', 'post_office_id' => 'Paka'],
    ['state_id' => '11', 'code' => '23200', 'post_office_id' => 'Bukit Besi'],
    ['state_id' => '11', 'code' => '23300', 'post_office_id' => 'Ketengah Jaya'],
    ['state_id' => '11', 'code' => '23400', 'post_office_id' => 'Al Muktatfi Billah Shah'],
    ['state_id' => '11', 'code' => '24000', 'post_office_id' => 'Cukai'],
    ['state_id' => '11', 'code' => '24007', 'post_office_id' => 'Cukai'],
    ['state_id' => '11', 'code' => '24009', 'post_office_id' => 'Cukai'],
    ['state_id' => '11', 'code' => '24050', 'post_office_id' => 'Ayer Puteh'],
    ['state_id' => '11', 'code' => '24060', 'post_office_id' => 'Ceneh'],
    ['state_id' => '11', 'code' => '24100', 'post_office_id' => 'Kijal'],
    ['state_id' => '11', 'code' => '24107', 'post_office_id' => 'Kijal'],
    ['state_id' => '11', 'code' => '24109', 'post_office_id' => 'Kijal'],
    ['state_id' => '11', 'code' => '24200', 'post_office_id' => 'Kemasek'],
    ['state_id' => '11', 'code' => '24207', 'post_office_id' => 'Kemasek'],
    ['state_id' => '11', 'code' => '24209', 'post_office_id' => 'Kemasek'],
    ['state_id' => '11', 'code' => '24300', 'post_office_id' => 'Kerteh'],
];