<?php

$data = [
    ['state_id' => '15', 'code' => '87000', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87010', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87011', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87012', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87013', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87014', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87015', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87016', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87017', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87018', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87019', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87020', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87021', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87022', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87023', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87024', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87025', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87026', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87027', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87028', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87029', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87030', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87031', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87032', 'post_office_id' => 'Labuan'],
    ['state_id' => '15', 'code' => '87033', 'post_office_id' => 'Labuan'],
];
