<?php
/**
 * kod gelaran pengguna - user title
 * sddsa : Kategori Data > Data Generik > Biodata > Kod Gelaran
 * code_1 - sddsa
 */
$items = [
      ['ddsa_id' => 'C001', 'name' => "Tun",],
      ['ddsa_id' => 'C002', 'name' => "Tan Sri",],
      ['ddsa_id' => 'C003', 'name' => "Tan Sri Dato'",],
      ['ddsa_id' => 'C004', 'name' => "Tan Sri Dato' Dr",],
      ['ddsa_id' => 'C005', 'name' => "Tan Sri Dato' Ir",],
      ['ddsa_id' => 'C006', 'name' => "Tan Sri Datuk Seri",],
      ['ddsa_id' => 'C007', 'name' => "Tan Sri Datuk",],
      ['ddsa_id' => 'C008', 'name' => "Tan Sri Datuk Dr",],
      ['ddsa_id' => 'C009', 'name' => "Tan Sri Datuk Professor",],
      ['ddsa_id' => 'C010', 'name' => "Tan Sri Datuk Professor Dr",],
      ['ddsa_id' => 'C011', 'name' => "Tan Sri Dr",],
      ['ddsa_id' => 'C012', 'name' => "Tan Sri General",],
      ['ddsa_id' => 'C013', 'name' => "Tan Sri Professor",],
      ['ddsa_id' => 'C014', 'name' => "Dato'",],
      ['ddsa_id' => 'C015', 'name' => "Dato' Dr",],
      ['ddsa_id' => 'C016', 'name' => "Dato' Ir",],
      ['ddsa_id' => 'C017', 'name' => "Dato' Ir Dr.",],
      ['ddsa_id' => 'C018', 'name' => "Dato' Paduka Dr.",],
      ['ddsa_id' => 'C019', 'name' => "Dato' Professor Madya Dr.",],
      ['ddsa_id' => 'C020', 'name' => "Dato' Senara Muda",],
      ['ddsa_id' => 'C021', 'name' => "Dato' Seri",],
      ['ddsa_id' => 'C022', 'name' => "Dato' Sri",],
      ['ddsa_id' => 'C023', 'name' => "Brigidier Jeneral Dato'",],
      ['ddsa_id' => 'C024', 'name' => "Datuk",],
      ['ddsa_id' => 'C025', 'name' => "Datuk Amar",],
      ['ddsa_id' => 'C026', 'name' => "Datuk Bentara Luar",],
      ['ddsa_id' => 'C027', 'name' => "Datuk Bentara Raja",],
      ['ddsa_id' => 'C028', 'name' => "Datuk Dr",],
      ['ddsa_id' => 'C029', 'name' => "Datuk Ir",],
      ['ddsa_id' => 'C030', 'name' => "Datuk Patinggi",],
      ['ddsa_id' => 'C031', 'name' => "Datuk Professor",],
      ['ddsa_id' => 'C032', 'name' => "Datuk Professor Dr",],
      ['ddsa_id' => 'C033', 'name' => "Datuk Setia",],
      ['ddsa_id' => 'C034', 'name' => "Datuk Setia Wangsa",],
      ['ddsa_id' => 'C035', 'name' => "Datuk Sri",],
      ['ddsa_id' => 'C036', 'name' => "Datuk Sri Amar DiRaja",],
      ['ddsa_id' => 'C037', 'name' => "Datuk Sri Dr",],
      ['ddsa_id' => 'C038', 'name' => "Datuk Wira",],
      ['ddsa_id' => 'C039', 'name' => "Datuk Wira Jaya",],
      ['ddsa_id' => 'C040', 'name' => "Doktor",],
      ['ddsa_id' => 'C041', 'name' => "Ir",],
      ['ddsa_id' => 'C042', 'name' => "Ir Dr",],
      ['ddsa_id' => 'C043', 'name' => "Jeneral",],
      ['ddsa_id' => 'C044', 'name' => "Kapten",],
      ['ddsa_id' => 'C045', 'name' => "Kolonel",],
      ['ddsa_id' => 'C046', 'name' => "Lt Kolonel",],
      ['ddsa_id' => 'C047', 'name' => "Major",],
      ['ddsa_id' => 'C048', 'name' => "Professor",],
      ['ddsa_id' => 'C049', 'name' => "Professor DiRaja",],
      ['ddsa_id' => 'C050', 'name' => "Professor Dr",],
      ['ddsa_id' => 'C051', 'name' => "Professor Madya",],
      ['ddsa_id' => 'C052', 'name' => "Prefessor Madya Dr",],
      ['ddsa_id' => 'C053', 'name' => "Datu",],
      ['ddsa_id' => 'C067', 'name' => "Professor Dato’ Dr.",],
      ['ddsa_id' => 'L001', 'name' => "Encik",],
      ['ddsa_id' => 'L002', 'name' => "Tuan",],
      ['ddsa_id' => 'L003', 'name' => "Haji",],
      ['ddsa_id' => 'P001', 'name' => "To' Puan",],
      ['ddsa_id' => 'P002', 'name' => "Toh Puan",],
      ['ddsa_id' => 'P003', 'name' => "Puan Sri",],
      ['ddsa_id' => 'P004', 'name' => "Puan Sri Datin",],
      ['ddsa_id' => 'P005', 'name' => "Puan Sri Datin Professor",],
      ['ddsa_id' => 'P006', 'name' => "Puan Sri Dr",],
      ['ddsa_id' => 'P007', 'name' => "Puan Sri Utama",],
      ['ddsa_id' => 'P008', 'name' => "Datin",],
      ['ddsa_id' => 'P009', 'name' => "Datin Amar",],
      ['ddsa_id' => 'P010', 'name' => "Datin Dr",],
      ['ddsa_id' => 'P011', 'name' => "Datin Paduka",],
      ['ddsa_id' => 'P012', 'name' => "Datin Patinggi",],
      ['ddsa_id' => 'P013', 'name' => "Datin Professor",],
      ['ddsa_id' => 'P014', 'name' => "Datin Professor Dr",],
      ['ddsa_id' => 'P015', 'name' => "Datin Setia",],
      ['ddsa_id' => 'P016', 'name' => "Datin Sri",],
      ['ddsa_id' => 'P017', 'name' => "Datin Sri Cempaka",],
      ['ddsa_id' => 'P018', 'name' => "Datin Sri Dr",],
      ['ddsa_id' => 'P019', 'name' => "Cik",],
      ['ddsa_id' => 'P020', 'name' => "Puan",],
      ['ddsa_id' => 'P021', 'name' => "Hajjah",],
];
